Package = applications/randomBuilder

Source    = \
	randomBuilderCmd.c \
	randomBuilder.cpp \
	
BuiltParallelExe = 0

RmiSource =

Main      = randomBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

