/* randomBuilderCmd.h */

/* File autogenerated by gengetopt version 2.16  */

#ifndef RANDOMBUILDERCMD_H
#define RANDOMBUILDERCMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "randomBuilder"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * output_arg;	/* Output file name.  */
  char * output_orig;	/* Output file name original value given at command line.  */
  char * latticetype_arg;	/* Lattice type string. Valid types are fcc,hcp,bcc and hcp-water. (default='fcc').  */
  char * latticetype_orig;	/* Lattice type string. Valid types are fcc,hcp,bcc and hcp-water. original value given at command line.  */
  double density_arg;	/* density (g/cm^3).  */
  char * density_orig;	/* density (g/cm^3) original value given at command line.  */
  int nx_arg;	/* number of unit cells in x.  */
  char * nx_orig;	/* number of unit cells in x original value given at command line.  */
  int ny_arg;	/* number of unit cells in y.  */
  char * ny_orig;	/* number of unit cells in y original value given at command line.  */
  int nz_arg;	/* number of unit cells in z.  */
  char * nz_orig;	/* number of unit cells in z original value given at command line.  */
  double* molFraction_arg;	/* (Default) Builds a multi-component random mixed nanoparticle. Mole Fraction must be specified for each componet > 1 in MD file..  */
  char ** molFraction_orig;	/* (Default) Builds a multi-component random mixed nanoparticle. Mole Fraction must be specified for each componet > 1 in MD file. original value given at command line.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int output_given ;	/* Whether output was given.  */
  int latticetype_given ;	/* Whether latticetype was given.  */
  int density_given ;	/* Whether density was given.  */
  int nx_given ;	/* Whether nx was given.  */
  int ny_given ;	/* Whether ny was given.  */
  int nz_given ;	/* Whether nz was given.  */
  unsigned int molFraction_given ;	/* Whether molFraction was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* RANDOMBUILDERCMD_H */
