#ifndef _GRAPHENE_INC_
#define _GRAPHENE_INC_

molecule {
  name = "graphene";
  atom[0]  { type = "CJ"; position( 1.235, -42.069, 0);}
  atom[1]  { type = "CJ"; position( 3.705, -42.069, 0);}
  atom[2]  { type = "CJ"; position( 6.175, -42.069, 0);}
  atom[3]  { type = "CJ"; position( 8.645, -42.069, 0);}
  atom[4]  { type = "CJ"; position( 11.115, -42.069, 0);}
  atom[5]  { type = "CJ"; position( 13.585, -42.069, 0);}
  atom[6]  { type = "CJ"; position( 16.055, -42.069, 0);}
  atom[7]  { type = "CJ"; position( 18.525, -42.069, 0);}
  atom[8]  { type = "CJ"; position( 20.995, -42.069, 0);}
  atom[9]  { type = "CJ"; position( 1.235, -40.643, 0);}
  atom[10] { type = "CJ"; position( 3.705, -40.643, 0);}
  atom[11] { type = "CJ"; position( 6.175, -40.643, 0);}
  atom[12] { type = "CJ"; position( 8.645, -40.643, 0);}
  atom[13] { type = "CJ"; position( 11.115, -40.643, 0);}
  atom[14] { type = "CJ"; position( 13.585, -40.643, 0);}
  atom[15] { type = "CJ"; position( 16.055, -40.643, 0);}
  atom[16] { type = "CJ"; position( 18.525, -40.643, 0);}
  atom[17] { type = "CJ"; position( 20.995, -40.643, 0);}
  atom[18] { type = "CJ"; position( 2.47, -39.93, 0);}
  atom[19] { type = "CJ"; position( 4.94, -39.93, 0);}
  atom[20] { type = "CJ"; position( 7.41, -39.93, 0);}
  atom[21] { type = "CJ"; position( 9.88, -39.93, 0);}
  atom[22] { type = "CJ"; position( 12.35, -39.93, 0);}
  atom[23] { type = "CJ"; position( 14.82, -39.93, 0);}
  atom[24] { type = "CJ"; position( 17.29, -39.93, 0);}
  atom[25] { type = "CJ"; position( 19.76, -39.93, 0);}
  atom[26] { type = "CJ"; position( 22.23, -39.93, 0);}
  atom[27] { type = "CJ"; position( 2.47, -38.503, 0);}
  atom[28] { type = "CJ"; position( 4.94, -38.503, 0);}
  atom[29] { type = "CJ"; position( 7.41, -38.503, 0);}
  atom[30] { type = "CJ"; position( 9.88, -38.503, 0);}
  atom[31] { type = "CJ"; position( 12.35, -38.503, 0);}
  atom[32] { type = "CJ"; position( 14.82, -38.503, 0);}
  atom[33] { type = "CJ"; position( 17.29, -38.503, 0);}
  atom[34] { type = "CJ"; position( 19.76, -38.503, 0);}
  atom[35] { type = "CJ"; position( 22.23, -38.503, 0);}
  atom[36] { type = "CJ"; position( 1.235, -37.79, 0);}
  atom[37] { type = "CJ"; position( 3.705, -37.79, 0);}
  atom[38] { type = "CJ"; position( 6.175, -37.79, 0);}
  atom[39] { type = "CJ"; position( 8.645, -37.79, 0);}
  atom[40] { type = "CJ"; position( 11.115, -37.79, 0);}
  atom[41] { type = "CJ"; position( 13.585, -37.79, 0);}
  atom[42] { type = "CJ"; position( 16.055, -37.79, 0);}
  atom[43] { type = "CJ"; position( 18.525, -37.79, 0);}
  atom[44] { type = "CJ"; position( 20.995, -37.79, 0);}
  atom[45] { type = "CJ"; position( 1.235, -36.364, 0);}
  atom[46] { type = "CJ"; position( 3.705, -36.364, 0);}
  atom[47] { type = "CJ"; position( 6.175, -36.364, 0);}
  atom[48] { type = "CJ"; position( 8.645, -36.364, 0);}
  atom[49] { type = "CJ"; position( 11.115, -36.364, 0);}
  atom[50] { type = "CJ"; position( 13.585, -36.364, 0);}
  atom[51] { type = "CJ"; position( 16.055, -36.364, 0);}
  atom[52] { type = "CJ"; position( 18.525, -36.364, 0);}
  atom[53] { type = "CJ"; position( 20.995, -36.364, 0);}
  atom[54] { type = "CJ"; position( 2.47, -35.651, 0);}
  atom[55] { type = "CJ"; position( 4.94, -35.651, 0);}
  atom[56] { type = "CJ"; position( 7.41, -35.651, 0);}
  atom[57] { type = "CJ"; position( 9.88, -35.651, 0);}
  atom[58] { type = "CJ"; position( 12.35, -35.651, 0);}
  atom[59] { type = "CJ"; position( 14.82, -35.651, 0);}
  atom[60] { type = "CJ"; position( 17.29, -35.651, 0);}
  atom[61] { type = "CJ"; position( 19.76, -35.651, 0);}
  atom[62] { type = "CJ"; position( 22.23, -35.651, 0);}
  atom[63] { type = "CJ"; position( 2.47, -34.225, 0);}
  atom[64] { type = "CJ"; position( 4.94, -34.225, 0);}
  atom[65] { type = "CJ"; position( 7.41, -34.225, 0);}
  atom[66] { type = "CJ"; position( 9.88, -34.225, 0);}
  atom[67] { type = "CJ"; position( 12.35, -34.225, 0);}
  atom[68] { type = "CJ"; position( 14.82, -34.225, 0);}
  atom[69] { type = "CJ"; position( 17.29, -34.225, 0);}
  atom[70] { type = "CJ"; position( 19.76, -34.225, 0);}
  atom[71] { type = "CJ"; position( 22.23, -34.225, 0);}
  atom[72] { type = "CJ"; position( 1.235, -33.512, 0);}
  atom[73] { type = "CJ"; position( 3.705, -33.512, 0);}
  atom[74] { type = "CJ"; position( 6.175, -33.512, 0);}
  atom[75] { type = "CJ"; position( 8.645, -33.512, 0);}
  atom[76] { type = "CJ"; position( 11.115, -33.512, 0);}
  atom[77] { type = "CJ"; position( 13.585, -33.512, 0);}
  atom[78] { type = "CJ"; position( 16.055, -33.512, 0);}
  atom[79] { type = "CJ"; position( 18.525, -33.512, 0);}
  atom[80] { type = "CJ"; position( 20.995, -33.512, 0);}
  atom[81] { type = "CJ"; position( 1.235, -32.086, 0);}
  atom[82] { type = "CJ"; position( 3.705, -32.086, 0);}
  atom[83] { type = "CJ"; position( 6.175, -32.086, 0);}
  atom[84] { type = "CJ"; position( 8.645, -32.086, 0);}
  atom[85] { type = "CJ"; position( 11.115, -32.086, 0);}
  atom[86] { type = "CJ"; position( 13.585, -32.086, 0);}
  atom[87] { type = "CJ"; position( 16.055, -32.086, 0);}
  atom[88] { type = "CJ"; position( 18.525, -32.086, 0);}
  atom[89] { type = "CJ"; position( 20.995, -32.086, 0);}
  atom[90] { type = "CJ"; position( 2.47, -31.373, 0);}
  atom[91] { type = "CJ"; position( 4.94, -31.373, 0);}
  atom[92] { type = "CJ"; position( 7.41, -31.373, 0);}
  atom[93] { type = "CJ"; position( 9.88, -31.373, 0);}
  atom[94] { type = "CJ"; position( 12.35, -31.373, 0);}
  atom[95] { type = "CJ"; position( 14.82, -31.373, 0);}
  atom[96] { type = "CJ"; position( 17.29, -31.373, 0);}
  atom[97] { type = "CJ"; position( 19.76, -31.373, 0);}
  atom[98] { type = "CJ"; position( 22.23, -31.373, 0);}
  atom[99] { type = "CJ"; position( 2.47, -29.947, 0);}
  atom[100] { type = "CJ"; position( 4.94, -29.947, 0);}
  atom[101] { type = "CJ"; position( 7.41, -29.947, 0);}
  atom[102] { type = "CJ"; position( 9.88, -29.947, 0);}
  atom[103] { type = "CJ"; position( 12.35, -29.947, 0);}
  atom[104] { type = "CJ"; position( 14.82, -29.947, 0);}
  atom[105] { type = "CJ"; position( 17.29, -29.947, 0);}
  atom[106] { type = "CJ"; position( 19.76, -29.947, 0);}
  atom[107] { type = "CJ"; position( 22.23, -29.947, 0);}
  atom[108] { type = "CJ"; position( 1.235, -29.234, 0);}
  atom[109] { type = "CJ"; position( 3.705, -29.234, 0);}
  atom[110] { type = "CJ"; position( 6.175, -29.234, 0);}
  atom[111] { type = "CJ"; position( 8.645, -29.234, 0);}
  atom[112] { type = "CJ"; position( 11.115, -29.234, 0);}
  atom[113] { type = "CJ"; position( 13.585, -29.234, 0);}
  atom[114] { type = "CJ"; position( 16.055, -29.234, 0);}
  atom[115] { type = "CJ"; position( 18.525, -29.234, 0);}
  atom[116] { type = "CJ"; position( 20.995, -29.234, 0);}
  atom[117] { type = "CJ"; position( 1.235, -27.808, 0);}
  atom[118] { type = "CJ"; position( 3.705, -27.808, 0);}
  atom[119] { type = "CJ"; position( 6.175, -27.808, 0);}
  atom[120] { type = "CJ"; position( 8.645, -27.808, 0);}
  atom[121] { type = "CJ"; position( 11.115, -27.808, 0);}
  atom[122] { type = "CJ"; position( 13.585, -27.808, 0);}
  atom[123] { type = "CJ"; position( 16.055, -27.808, 0);}
  atom[124] { type = "CJ"; position( 18.525, -27.808, 0);}
  atom[125] { type = "CJ"; position( 20.995, -27.808, 0);}
  atom[126] { type = "CJ"; position( 2.47, -27.095, 0);}
  atom[127] { type = "CJ"; position( 4.94, -27.095, 0);}
  atom[128] { type = "CJ"; position( 7.41, -27.095, 0);}
  atom[129] { type = "CJ"; position( 9.88, -27.095, 0);}
  atom[130] { type = "CJ"; position( 12.35, -27.095, 0);}
  atom[131] { type = "CJ"; position( 14.82, -27.095, 0);}
  atom[132] { type = "CJ"; position( 17.29, -27.095, 0);}
  atom[133] { type = "CJ"; position( 19.76, -27.095, 0);}
  atom[134] { type = "CJ"; position( 22.23, -27.095, 0);}
  atom[135] { type = "CJ"; position( 2.47, -25.669, 0);}
  atom[136] { type = "CJ"; position( 4.94, -25.669, 0);}
  atom[137] { type = "CJ"; position( 7.41, -25.669, 0);}
  atom[138] { type = "CJ"; position( 9.88, -25.669, 0);}
  atom[139] { type = "CJ"; position( 12.35, -25.669, 0);}
  atom[140] { type = "CJ"; position( 14.82, -25.669, 0);}
  atom[141] { type = "CJ"; position( 17.29, -25.669, 0);}
  atom[142] { type = "CJ"; position( 19.76, -25.669, 0);}
  atom[143] { type = "CJ"; position( 22.23, -25.669, 0);}
  atom[144] { type = "CJ"; position( 1.235, -24.956, 0);}
  atom[145] { type = "CJ"; position( 3.705, -24.956, 0);}
  atom[146] { type = "CJ"; position( 6.175, -24.956, 0);}
  atom[147] { type = "CJ"; position( 8.645, -24.956, 0);}
  atom[148] { type = "CJ"; position( 11.115, -24.956, 0);}
  atom[149] { type = "CJ"; position( 13.585, -24.956, 0);}
  atom[150] { type = "CJ"; position( 16.055, -24.956, 0);}
  atom[151] { type = "CJ"; position( 18.525, -24.956, 0);}
  atom[152] { type = "CJ"; position( 20.995, -24.956, 0);}
  atom[153] { type = "CJ"; position( 1.235, -23.53, 0);}
  atom[154] { type = "CJ"; position( 3.705, -23.53, 0);}
  atom[155] { type = "CJ"; position( 6.175, -23.53, 0);}
  atom[156] { type = "CJ"; position( 8.645, -23.53, 0);}
  atom[157] { type = "CJ"; position( 11.115, -23.53, 0);}
  atom[158] { type = "CJ"; position( 13.585, -23.53, 0);}
  atom[159] { type = "CJ"; position( 16.055, -23.53, 0);}
  atom[160] { type = "CJ"; position( 18.525, -23.53, 0);}
  atom[161] { type = "CJ"; position( 20.995, -23.53, 0);}
  atom[162] { type = "CJ"; position( 2.47, -22.817, 0);}
  atom[163] { type = "CJ"; position( 4.94, -22.817, 0);}
  atom[164] { type = "CJ"; position( 7.41, -22.817, 0);}
  atom[165] { type = "CJ"; position( 9.88, -22.817, 0);}
  atom[166] { type = "CJ"; position( 12.35, -22.817, 0);}
  atom[167] { type = "CJ"; position( 14.82, -22.817, 0);}
  atom[168] { type = "CJ"; position( 17.29, -22.817, 0);}
  atom[169] { type = "CJ"; position( 19.76, -22.817, 0);}
  atom[170] { type = "CJ"; position( 22.23, -22.817, 0);}
  atom[171] { type = "CJ"; position( 2.47, -21.391, 0);}
  atom[172] { type = "CJ"; position( 4.94, -21.391, 0);}
  atom[173] { type = "CJ"; position( 7.41, -21.391, 0);}
  atom[174] { type = "CJ"; position( 9.88, -21.391, 0);}
  atom[175] { type = "CJ"; position( 12.35, -21.391, 0);}
  atom[176] { type = "CJ"; position( 14.82, -21.391, 0);}
  atom[177] { type = "CJ"; position( 17.29, -21.391, 0);}
  atom[178] { type = "CJ"; position( 19.76, -21.391, 0);}
  atom[179] { type = "CJ"; position( 22.23, -21.391, 0);}
  atom[180] { type = "CJ"; position( 1.235, -20.678, 0);}
  atom[181] { type = "CJ"; position( 3.705, -20.678, 0);}
  atom[182] { type = "CJ"; position( 6.175, -20.678, 0);}
  atom[183] { type = "CJ"; position( 8.645, -20.678, 0);}
  atom[184] { type = "CJ"; position( 11.115, -20.678, 0);}
  atom[185] { type = "CJ"; position( 13.585, -20.678, 0);}
  atom[186] { type = "CJ"; position( 16.055, -20.678, 0);}
  atom[187] { type = "CJ"; position( 18.525, -20.678, 0);}
  atom[188] { type = "CJ"; position( 20.995, -20.678, 0);}
  atom[189] { type = "CJ"; position( 1.235, -19.252, 0);}
  atom[190] { type = "CJ"; position( 3.705, -19.252, 0);}
  atom[191] { type = "CJ"; position( 6.175, -19.252, 0);}
  atom[192] { type = "CJ"; position( 8.645, -19.252, 0);}
  atom[193] { type = "CJ"; position( 11.115, -19.252, 0);}
  atom[194] { type = "CJ"; position( 13.585, -19.252, 0);}
  atom[195] { type = "CJ"; position( 16.055, -19.252, 0);}
  atom[196] { type = "CJ"; position( 18.525, -19.252, 0);}
  atom[197] { type = "CJ"; position( 20.995, -19.252, 0);}
  atom[198] { type = "CJ"; position( 2.47, -18.539, 0);}
  atom[199] { type = "CJ"; position( 4.94, -18.539, 0);}
  atom[200] { type = "CJ"; position( 7.41, -18.539, 0);}
  atom[201] { type = "CJ"; position( 9.88, -18.539, 0);}
  atom[202] { type = "CJ"; position( 12.35, -18.539, 0);}
  atom[203] { type = "CJ"; position( 14.82, -18.539, 0);}
  atom[204] { type = "CJ"; position( 17.29, -18.539, 0);}
  atom[205] { type = "CJ"; position( 19.76, -18.539, 0);}
  atom[206] { type = "CJ"; position( 22.23, -18.539, 0);}
  atom[207] { type = "CJ"; position( 2.47, -17.113, 0);}
  atom[208] { type = "CJ"; position( 4.94, -17.113, 0);}
  atom[209] { type = "CJ"; position( 7.41, -17.113, 0);}
  atom[210] { type = "CJ"; position( 9.88, -17.113, 0);}
  atom[211] { type = "CJ"; position( 12.35, -17.113, 0);}
  atom[212] { type = "CJ"; position( 14.82, -17.113, 0);}
  atom[213] { type = "CJ"; position( 17.29, -17.113, 0);}
  atom[214] { type = "CJ"; position( 19.76, -17.113, 0);}
  atom[215] { type = "CJ"; position( 22.23, -17.113, 0);}
  atom[216] { type = "CJ"; position( 1.235, -16.4, 0);}
  atom[217] { type = "CJ"; position( 3.705, -16.4, 0);}
  atom[218] { type = "CJ"; position( 6.175, -16.4, 0);}
  atom[219] { type = "CJ"; position( 8.645, -16.4, 0);}
  atom[220] { type = "CJ"; position( 11.115, -16.4, 0);}
  atom[221] { type = "CJ"; position( 13.585, -16.4, 0);}
  atom[222] { type = "CJ"; position( 16.055, -16.4, 0);}
  atom[223] { type = "CJ"; position( 18.525, -16.4, 0);}
  atom[224] { type = "CJ"; position( 20.995, -16.4, 0);}
  atom[225] { type = "CJ"; position( 1.235, -14.974, 0);}
  atom[226] { type = "CJ"; position( 3.705, -14.974, 0);}
  atom[227] { type = "CJ"; position( 6.175, -14.974, 0);}
  atom[228] { type = "CJ"; position( 8.645, -14.974, 0);}
  atom[229] { type = "CJ"; position( 11.115, -14.974, 0);}
  atom[230] { type = "CJ"; position( 13.585, -14.974, 0);}
  atom[231] { type = "CJ"; position( 16.055, -14.974, 0);}
  atom[232] { type = "CJ"; position( 18.525, -14.974, 0);}
  atom[233] { type = "CJ"; position( 20.995, -14.974, 0);}
  atom[234] { type = "CJ"; position( 2.47, -14.261, 0);}
  atom[235] { type = "CJ"; position( 4.94, -14.261, 0);}
  atom[236] { type = "CJ"; position( 7.41, -14.261, 0);}
  atom[237] { type = "CJ"; position( 9.88, -14.261, 0);}
  atom[238] { type = "CJ"; position( 12.35, -14.261, 0);}
  atom[239] { type = "CJ"; position( 14.82, -14.261, 0);}
  atom[240] { type = "CJ"; position( 17.29, -14.261, 0);}
  atom[241] { type = "CJ"; position( 19.76, -14.261, 0);}
  atom[242] { type = "CJ"; position( 22.23, -14.261, 0);}
  atom[243] { type = "CJ"; position( 2.47, -12.834, 0);}
  atom[244] { type = "CJ"; position( 4.94, -12.834, 0);}
  atom[245] { type = "CJ"; position( 7.41, -12.834, 0);}
  atom[246] { type = "CJ"; position( 9.88, -12.834, 0);}
  atom[247] { type = "CJ"; position( 12.35, -12.834, 0);}
  atom[248] { type = "CJ"; position( 14.82, -12.834, 0);}
  atom[249] { type = "CJ"; position( 17.29, -12.834, 0);}
  atom[250] { type = "CJ"; position( 19.76, -12.834, 0);}
  atom[251] { type = "CJ"; position( 22.23, -12.834, 0);}
  atom[252] { type = "CJ"; position( 1.235, -12.121, 0);}
  atom[253] { type = "CJ"; position( 3.705, -12.121, 0);}
  atom[254] { type = "CJ"; position( 6.175, -12.121, 0);}
  atom[255] { type = "CJ"; position( 8.645, -12.121, 0);}
  atom[256] { type = "CJ"; position( 11.115, -12.121, 0);}
  atom[257] { type = "CJ"; position( 13.585, -12.121, 0);}
  atom[258] { type = "CJ"; position( 16.055, -12.121, 0);}
  atom[259] { type = "CJ"; position( 18.525, -12.121, 0);}
  atom[260] { type = "CJ"; position( 20.995, -12.121, 0);}
  atom[261] { type = "CJ"; position( 1.235, -10.695, 0);}
  atom[262] { type = "CJ"; position( 3.705, -10.695, 0);}
  atom[263] { type = "CJ"; position( 6.175, -10.695, 0);}
  atom[264] { type = "CJ"; position( 8.645, -10.695, 0);}
  atom[265] { type = "CJ"; position( 11.115, -10.695, 0);}
  atom[266] { type = "CJ"; position( 13.585, -10.695, 0);}
  atom[267] { type = "CJ"; position( 16.055, -10.695, 0);}
  atom[268] { type = "CJ"; position( 18.525, -10.695, 0);}
  atom[269] { type = "CJ"; position( 20.995, -10.695, 0);}
  atom[270] { type = "CJ"; position( 2.47, -9.982, 0);}
  atom[271] { type = "CJ"; position( 4.94, -9.982, 0);}
  atom[272] { type = "CJ"; position( 7.41, -9.982, 0);}
  atom[273] { type = "CJ"; position( 9.88, -9.982, 0);}
  atom[274] { type = "CJ"; position( 12.35, -9.982, 0);}
  atom[275] { type = "CJ"; position( 14.82, -9.982, 0);}
  atom[276] { type = "CJ"; position( 17.29, -9.982, 0);}
  atom[277] { type = "CJ"; position( 19.76, -9.982, 0);}
  atom[278] { type = "CJ"; position( 22.23, -9.982, 0);}
  atom[279] { type = "CJ"; position( 2.47, -8.556, 0);}
  atom[280] { type = "CJ"; position( 4.94, -8.556, 0);}
  atom[281] { type = "CJ"; position( 7.41, -8.556, 0);}
  atom[282] { type = "CJ"; position( 9.88, -8.556, 0);}
  atom[283] { type = "CJ"; position( 12.35, -8.556, 0);}
  atom[284] { type = "CJ"; position( 14.82, -8.556, 0);}
  atom[285] { type = "CJ"; position( 17.29, -8.556, 0);}
  atom[286] { type = "CJ"; position( 19.76, -8.556, 0);}
  atom[287] { type = "CJ"; position( 22.23, -8.556, 0);}
  atom[288] { type = "CJ"; position( 1.235, -7.843, 0);}
  atom[289] { type = "CJ"; position( 3.705, -7.843, 0);}
  atom[290] { type = "CJ"; position( 6.175, -7.843, 0);}
  atom[291] { type = "CJ"; position( 8.645, -7.843, 0);}
  atom[292] { type = "CJ"; position( 11.115, -7.843, 0);}
  atom[293] { type = "CJ"; position( 13.585, -7.843, 0);}
  atom[294] { type = "CJ"; position( 16.055, -7.843, 0);}
  atom[295] { type = "CJ"; position( 18.525, -7.843, 0);}
  atom[296] { type = "CJ"; position( 20.995, -7.843, 0);}
  atom[297] { type = "CJ"; position( 1.235, -6.417, 0);}
  atom[298] { type = "CJ"; position( 3.705, -6.417, 0);}
  atom[299] { type = "CJ"; position( 6.175, -6.417, 0);}
  atom[300] { type = "CJ"; position( 8.645, -6.417, 0);}
  atom[301] { type = "CJ"; position( 11.115, -6.417, 0);}
  atom[302] { type = "CJ"; position( 13.585, -6.417, 0);}
  atom[303] { type = "CJ"; position( 16.055, -6.417, 0);}
  atom[304] { type = "CJ"; position( 18.525, -6.417, 0);}
  atom[305] { type = "CJ"; position( 20.995, -6.417, 0);}
  atom[306] { type = "CJ"; position( 2.47, -5.704, 0);}
  atom[307] { type = "CJ"; position( 4.94, -5.704, 0);}
  atom[308] { type = "CJ"; position( 7.41, -5.704, 0);}
  atom[309] { type = "CJ"; position( 9.88, -5.704, 0);}
  atom[310] { type = "CJ"; position( 12.35, -5.704, 0);}
  atom[311] { type = "CJ"; position( 14.82, -5.704, 0);}
  atom[312] { type = "CJ"; position( 17.29, -5.704, 0);}
  atom[313] { type = "CJ"; position( 19.76, -5.704, 0);}
  atom[314] { type = "CJ"; position( 22.23, -5.704, 0);}
  atom[315] { type = "CJ"; position( 2.47, -4.278, 0);}
  atom[316] { type = "CJ"; position( 4.94, -4.278, 0);}
  atom[317] { type = "CJ"; position( 7.41, -4.278, 0);}
  atom[318] { type = "CJ"; position( 9.88, -4.278, 0);}
  atom[319] { type = "CJ"; position( 12.35, -4.278, 0);}
  atom[320] { type = "CJ"; position( 14.82, -4.278, 0);}
  atom[321] { type = "CJ"; position( 17.29, -4.278, 0);}
  atom[322] { type = "CJ"; position( 19.76, -4.278, 0);}
  atom[323] { type = "CJ"; position( 22.23, -4.278, 0);}
  atom[324] { type = "CJ"; position( 1.235, -3.565, 0);}
  atom[325] { type = "CJ"; position( 3.705, -3.565, 0);}
  atom[326] { type = "CJ"; position( 6.175, -3.565, 0);}
  atom[327] { type = "CJ"; position( 8.645, -3.565, 0);}
  atom[328] { type = "CJ"; position( 11.115, -3.565, 0);}
  atom[329] { type = "CJ"; position( 13.585, -3.565, 0);}
  atom[330] { type = "CJ"; position( 16.055, -3.565, 0);}
  atom[331] { type = "CJ"; position( 18.525, -3.565, 0);}
  atom[332] { type = "CJ"; position( 20.995, -3.565, 0);}
  atom[333] { type = "CJ"; position( 1.235, -2.139, 0);}
  atom[334] { type = "CJ"; position( 3.705, -2.139, 0);}
  atom[335] { type = "CJ"; position( 6.175, -2.139, 0);}
  atom[336] { type = "CJ"; position( 8.645, -2.139, 0);}
  atom[337] { type = "CJ"; position( 11.115, -2.139, 0);}
  atom[338] { type = "CJ"; position( 13.585, -2.139, 0);}
  atom[339] { type = "CJ"; position( 16.055, -2.139, 0);}
  atom[340] { type = "CJ"; position( 18.525, -2.139, 0);}
  atom[341] { type = "CJ"; position( 20.995, -2.139, 0);}
  atom[342] { type = "CJ"; position( 2.47, -1.426, 0);}
  atom[343] { type = "CJ"; position( 4.94, -1.426, 0);}
  atom[344] { type = "CJ"; position( 7.41, -1.426, 0);}
  atom[345] { type = "CJ"; position( 9.88, -1.426, 0);}
  atom[346] { type = "CJ"; position( 12.35, -1.426, 0);}
  atom[347] { type = "CJ"; position( 14.82, -1.426, 0);}
  atom[348] { type = "CJ"; position( 17.29, -1.426, 0);}
  atom[349] { type = "CJ"; position( 19.76, -1.426, 0);}
  atom[350] { type = "CJ"; position( 22.23, -1.426, 0);}
  atom[351] { type = "CJ"; position( 2.47, 0, 0);}
  atom[352] { type = "CJ"; position( 4.94, 0, 0);}
  atom[353] { type = "CJ"; position( 7.41, 0, 0);}
  atom[354] { type = "CJ"; position( 9.88, 0, 0);}
  atom[355] { type = "CJ"; position( 12.35, 0, 0);}
  atom[356] { type = "CJ"; position( 14.82, 0, 0);}
  atom[357] { type = "CJ"; position( 17.29, 0, 0);}
  atom[358] { type = "CJ"; position( 19.76, 0, 0);}
  atom[359] { type = "CJ"; position( 22.23, 0, 0);}

  bond { members(0, 9); }
  bond { members(1, 10); }
  bond { members(2, 11); }
  bond { members(3, 12); }
  bond { members(4, 13); }
  bond { members(5, 14); }
  bond { members(6, 15); }
  bond { members(7, 16); }
  bond { members(8, 17); }
  bond { members(9, 18); }
  bond { members(10, 18); }
  bond { members(10, 19); }
  bond { members(11, 19); }
  bond { members(11, 20); }
  bond { members(12, 20); }
  bond { members(12, 21); }
  bond { members(13, 21); }
  bond { members(13, 22); }
  bond { members(14, 22); }
  bond { members(14, 23); }
  bond { members(15, 23); }
  bond { members(15, 24); }
  bond { members(16, 24); }
  bond { members(16, 25); }
  bond { members(17, 25); }
  bond { members(17, 26); }
  bond { members(18, 27); }
  bond { members(19, 28); }
  bond { members(20, 29); }
  bond { members(21, 30); }
  bond { members(22, 31); }
  bond { members(23, 32); }
  bond { members(24, 33); }
  bond { members(25, 34); }
  bond { members(26, 35); }
  bond { members(27, 36); }
  bond { members(27, 37); }
  bond { members(28, 37); }
  bond { members(28, 38); }
  bond { members(29, 38); }
  bond { members(29, 39); }
  bond { members(30, 39); }
  bond { members(30, 40); }
  bond { members(31, 40); }
  bond { members(31, 41); }
  bond { members(32, 41); }
  bond { members(32, 42); }
  bond { members(33, 42); }
  bond { members(33, 43); }
  bond { members(34, 43); }
  bond { members(34, 44); }
  bond { members(35, 44); }
  bond { members(36, 45); }
  bond { members(37, 46); }
  bond { members(38, 47); }
  bond { members(39, 48); }
  bond { members(40, 49); }
  bond { members(41, 50); }
  bond { members(42, 51); }
  bond { members(43, 52); }
  bond { members(44, 53); }
  bond { members(45, 54); }
  bond { members(46, 54); }
  bond { members(46, 55); }
  bond { members(47, 55); }
  bond { members(47, 56); }
  bond { members(48, 56); }
  bond { members(48, 57); }
  bond { members(49, 57); }
  bond { members(49, 58); }
  bond { members(50, 58); }
  bond { members(50, 59); }
  bond { members(51, 59); }
  bond { members(51, 60); }
  bond { members(52, 60); }
  bond { members(52, 61); }
  bond { members(53, 61); }
  bond { members(53, 62); }
  bond { members(54, 63); }
  bond { members(55, 64); }
  bond { members(56, 65); }
  bond { members(57, 66); }
  bond { members(58, 67); }
  bond { members(59, 68); }
  bond { members(60, 69); }
  bond { members(61, 70); }
  bond { members(62, 71); }
  bond { members(63, 72); }
  bond { members(63, 73); }
  bond { members(64, 73); }
  bond { members(64, 74); }
  bond { members(65, 74); }
  bond { members(65, 75); }
  bond { members(66, 75); }
  bond { members(66, 76); }
  bond { members(67, 76); }
  bond { members(67, 77); }
  bond { members(68, 77); }
  bond { members(68, 78); }
  bond { members(69, 78); }
  bond { members(69, 79); }
  bond { members(70, 79); }
  bond { members(70, 80); }
  bond { members(71, 80); }
  bond { members(72, 81); }
  bond { members(73, 82); }
  bond { members(74, 83); }
  bond { members(75, 84); }
  bond { members(76, 85); }
  bond { members(77, 86); }
  bond { members(78, 87); }
  bond { members(79, 88); }
  bond { members(80, 89); }
  bond { members(81, 90); }
  bond { members(82, 90); }
  bond { members(82, 91); }
  bond { members(83, 91); }
  bond { members(83, 92); }
  bond { members(84, 92); }
  bond { members(84, 93); }
  bond { members(85, 93); }
  bond { members(85, 94); }
  bond { members(86, 94); }
  bond { members(86, 95); }
  bond { members(87, 95); }
  bond { members(87, 96); }
  bond { members(88, 96); }
  bond { members(88, 97); }
  bond { members(89, 97); }
  bond { members(89, 98); }
  bond { members(90, 99); }
  bond { members(91, 100); }
  bond { members(92, 101); }
  bond { members(93, 102); }
  bond { members(94, 103); }
  bond { members(95, 104); }
  bond { members(96, 105); }
  bond { members(97, 106); }
  bond { members(98, 107); }
  bond { members(99, 108); }
  bond { members(99, 109); }
  bond { members(100, 109); }
  bond { members(100, 110); }
  bond { members(101, 110); }
  bond { members(101, 111); }
  bond { members(102, 111); }
  bond { members(102, 112); }
  bond { members(103, 112); }
  bond { members(103, 113); }
  bond { members(104, 113); }
  bond { members(104, 114); }
  bond { members(105, 114); }
  bond { members(105, 115); }
  bond { members(106, 115); }
  bond { members(106, 116); }
  bond { members(107, 116); }
  bond { members(108, 117); }
  bond { members(109, 118); }
  bond { members(110, 119); }
  bond { members(111, 120); }
  bond { members(112, 121); }
  bond { members(113, 122); }
  bond { members(114, 123); }
  bond { members(115, 124); }
  bond { members(116, 125); }
  bond { members(117, 126); }
  bond { members(118, 126); }
  bond { members(118, 127); }
  bond { members(119, 127); }
  bond { members(119, 128); }
  bond { members(120, 128); }
  bond { members(120, 129); }
  bond { members(121, 129); }
  bond { members(121, 130); }
  bond { members(122, 130); }
  bond { members(122, 131); }
  bond { members(123, 131); }
  bond { members(123, 132); }
  bond { members(124, 132); }
  bond { members(124, 133); }
  bond { members(125, 133); }
  bond { members(125, 134); }
  bond { members(126, 135); }
  bond { members(127, 136); }
  bond { members(128, 137); }
  bond { members(129, 138); }
  bond { members(130, 139); }
  bond { members(131, 140); }
  bond { members(132, 141); }
  bond { members(133, 142); }
  bond { members(134, 143); }
  bond { members(135, 144); }
  bond { members(135, 145); }
  bond { members(136, 145); }
  bond { members(136, 146); }
  bond { members(137, 146); }
  bond { members(137, 147); }
  bond { members(138, 147); }
  bond { members(138, 148); }
  bond { members(139, 148); }
  bond { members(139, 149); }
  bond { members(140, 149); }
  bond { members(140, 150); }
  bond { members(141, 150); }
  bond { members(141, 151); }
  bond { members(142, 151); }
  bond { members(142, 152); }
  bond { members(143, 152); }
  bond { members(144, 153); }
  bond { members(145, 154); }
  bond { members(146, 155); }
  bond { members(147, 156); }
  bond { members(148, 157); }
  bond { members(149, 158); }
  bond { members(150, 159); }
  bond { members(151, 160); }
  bond { members(152, 161); }
  bond { members(153, 162); }
  bond { members(154, 162); }
  bond { members(154, 163); }
  bond { members(155, 163); }
  bond { members(155, 164); }
  bond { members(156, 164); }
  bond { members(156, 165); }
  bond { members(157, 165); }
  bond { members(157, 166); }
  bond { members(158, 166); }
  bond { members(158, 167); }
  bond { members(159, 167); }
  bond { members(159, 168); }
  bond { members(160, 168); }
  bond { members(160, 169); }
  bond { members(161, 169); }
  bond { members(161, 170); }
  bond { members(162, 171); }
  bond { members(163, 172); }
  bond { members(164, 173); }
  bond { members(165, 174); }
  bond { members(166, 175); }
  bond { members(167, 176); }
  bond { members(168, 177); }
  bond { members(169, 178); }
  bond { members(170, 179); }
  bond { members(171, 180); }
  bond { members(171, 181); }
  bond { members(172, 181); }
  bond { members(172, 182); }
  bond { members(173, 182); }
  bond { members(173, 183); }
  bond { members(174, 183); }
  bond { members(174, 184); }
  bond { members(175, 184); }
  bond { members(175, 185); }
  bond { members(176, 185); }
  bond { members(176, 186); }
  bond { members(177, 186); }
  bond { members(177, 187); }
  bond { members(178, 187); }
  bond { members(178, 188); }
  bond { members(179, 188); }
  bond { members(180, 189); }
  bond { members(181, 190); }
  bond { members(182, 191); }
  bond { members(183, 192); }
  bond { members(184, 193); }
  bond { members(185, 194); }
  bond { members(186, 195); }
  bond { members(187, 196); }
  bond { members(188, 197); }
  bond { members(189, 198); }
  bond { members(190, 198); }
  bond { members(190, 199); }
  bond { members(191, 199); }
  bond { members(191, 200); }
  bond { members(192, 200); }
  bond { members(192, 201); }
  bond { members(193, 201); }
  bond { members(193, 202); }
  bond { members(194, 202); }
  bond { members(194, 203); }
  bond { members(195, 203); }
  bond { members(195, 204); }
  bond { members(196, 204); }
  bond { members(196, 205); }
  bond { members(197, 205); }
  bond { members(197, 206); }
  bond { members(198, 207); }
  bond { members(199, 208); }
  bond { members(200, 209); }
  bond { members(201, 210); }
  bond { members(202, 211); }
  bond { members(203, 212); }
  bond { members(204, 213); }
  bond { members(205, 214); }
  bond { members(206, 215); }
  bond { members(207, 216); }
  bond { members(207, 217); }
  bond { members(208, 217); }
  bond { members(208, 218); }
  bond { members(209, 218); }
  bond { members(209, 219); }
  bond { members(210, 219); }
  bond { members(210, 220); }
  bond { members(211, 220); }
  bond { members(211, 221); }
  bond { members(212, 221); }
  bond { members(212, 222); }
  bond { members(213, 222); }
  bond { members(213, 223); }
  bond { members(214, 223); }
  bond { members(214, 224); }
  bond { members(215, 224); }
  bond { members(216, 225); }
  bond { members(217, 226); }
  bond { members(218, 227); }
  bond { members(219, 228); }
  bond { members(220, 229); }
  bond { members(221, 230); }
  bond { members(222, 231); }
  bond { members(223, 232); }
  bond { members(224, 233); }
  bond { members(225, 234); }
  bond { members(226, 234); }
  bond { members(226, 235); }
  bond { members(227, 235); }
  bond { members(227, 236); }
  bond { members(228, 236); }
  bond { members(228, 237); }
  bond { members(229, 237); }
  bond { members(229, 238); }
  bond { members(230, 238); }
  bond { members(230, 239); }
  bond { members(231, 239); }
  bond { members(231, 240); }
  bond { members(232, 240); }
  bond { members(232, 241); }
  bond { members(233, 241); }
  bond { members(233, 242); }
  bond { members(234, 243); }
  bond { members(235, 244); }
  bond { members(236, 245); }
  bond { members(237, 246); }
  bond { members(238, 247); }
  bond { members(239, 248); }
  bond { members(240, 249); }
  bond { members(241, 250); }
  bond { members(242, 251); }
  bond { members(243, 252); }
  bond { members(243, 253); }
  bond { members(244, 253); }
  bond { members(244, 254); }
  bond { members(245, 254); }
  bond { members(245, 255); }
  bond { members(246, 255); }
  bond { members(246, 256); }
  bond { members(247, 256); }
  bond { members(247, 257); }
  bond { members(248, 257); }
  bond { members(248, 258); }
  bond { members(249, 258); }
  bond { members(249, 259); }
  bond { members(250, 259); }
  bond { members(250, 260); }
  bond { members(251, 260); }
  bond { members(252, 261); }
  bond { members(253, 262); }
  bond { members(254, 263); }
  bond { members(255, 264); }
  bond { members(256, 265); }
  bond { members(257, 266); }
  bond { members(258, 267); }
  bond { members(259, 268); }
  bond { members(260, 269); }
  bond { members(261, 270); }
  bond { members(262, 270); }
  bond { members(262, 271); }
  bond { members(263, 271); }
  bond { members(263, 272); }
  bond { members(264, 272); }
  bond { members(264, 273); }
  bond { members(265, 273); }
  bond { members(265, 274); }
  bond { members(266, 274); }
  bond { members(266, 275); }
  bond { members(267, 275); }
  bond { members(267, 276); }
  bond { members(268, 276); }
  bond { members(268, 277); }
  bond { members(269, 277); }
  bond { members(269, 278); }
  bond { members(270, 279); }
  bond { members(271, 280); }
  bond { members(272, 281); }
  bond { members(273, 282); }
  bond { members(274, 283); }
  bond { members(275, 284); }
  bond { members(276, 285); }
  bond { members(277, 286); }
  bond { members(278, 287); }
  bond { members(279, 288); }
  bond { members(279, 289); }
  bond { members(280, 289); }
  bond { members(280, 290); }
  bond { members(281, 290); }
  bond { members(281, 291); }
  bond { members(282, 291); }
  bond { members(282, 292); }
  bond { members(283, 292); }
  bond { members(283, 293); }
  bond { members(284, 293); }
  bond { members(284, 294); }
  bond { members(285, 294); }
  bond { members(285, 295); }
  bond { members(286, 295); }
  bond { members(286, 296); }
  bond { members(287, 296); }
  bond { members(288, 297); }
  bond { members(289, 298); }
  bond { members(290, 299); }
  bond { members(291, 300); }
  bond { members(292, 301); }
  bond { members(293, 302); }
  bond { members(294, 303); }
  bond { members(295, 304); }
  bond { members(296, 305); }
  bond { members(297, 306); }
  bond { members(298, 306); }
  bond { members(298, 307); }
  bond { members(299, 307); }
  bond { members(299, 308); }
  bond { members(300, 308); }
  bond { members(300, 309); }
  bond { members(301, 309); }
  bond { members(301, 310); }
  bond { members(302, 310); }
  bond { members(302, 311); }
  bond { members(303, 311); }
  bond { members(303, 312); }
  bond { members(304, 312); }
  bond { members(304, 313); }
  bond { members(305, 313); }
  bond { members(305, 314); }
  bond { members(306, 315); }
  bond { members(307, 316); }
  bond { members(308, 317); }
  bond { members(309, 318); }
  bond { members(310, 319); }
  bond { members(311, 320); }
  bond { members(312, 321); }
  bond { members(313, 322); }
  bond { members(314, 323); }
  bond { members(315, 324); }
  bond { members(315, 325); }
  bond { members(316, 325); }
  bond { members(316, 326); }
  bond { members(317, 326); }
  bond { members(317, 327); }
  bond { members(318, 327); }
  bond { members(318, 328); }
  bond { members(319, 328); }
  bond { members(319, 329); }
  bond { members(320, 329); }
  bond { members(320, 330); }
  bond { members(321, 330); }
  bond { members(321, 331); }
  bond { members(322, 331); }
  bond { members(322, 332); }
  bond { members(323, 332); }
  bond { members(324, 333); }
  bond { members(325, 334); }
  bond { members(326, 335); }
  bond { members(327, 336); }
  bond { members(328, 337); }
  bond { members(329, 338); }
  bond { members(330, 339); }
  bond { members(331, 340); }
  bond { members(332, 341); }
  bond { members(333, 342); }
  bond { members(334, 342); }
  bond { members(334, 343); }
  bond { members(335, 343); }
  bond { members(335, 344); }
  bond { members(336, 344); }
  bond { members(336, 345); }
  bond { members(337, 345); }
  bond { members(337, 346); }
  bond { members(338, 346); }
  bond { members(338, 347); }
  bond { members(339, 347); }
  bond { members(339, 348); }
  bond { members(340, 348); }
  bond { members(340, 349); }
  bond { members(341, 349); }
  bond { members(341, 350); }
  bond { members(342, 351); }
  bond { members(343, 352); }
  bond { members(344, 353); }
  bond { members(345, 354); }
  bond { members(346, 355); }
  bond { members(347, 356); }
  bond { members(348, 357); }
  bond { members(349, 358); }
  bond { members(350, 359); }
  // extra bonds used to span across the other side of the box:
  bond { members(0, 351); }
  bond { members(1, 352); }
  bond { members(2, 353); }
  bond { members(3, 354); }
  bond { members(4, 355); }
  bond { members(5, 356); }
  bond { members(6, 357); }
  bond { members(7, 358); }
  bond { members(8, 359); }
  bond { members(0, 359); }
  bond { members(1, 351); }
  bond { members(2, 352); }
  bond { members(3, 353); }
  bond { members(4, 354); }
  bond { members(5, 355); }
  bond { members(6, 356); }
  bond { members(7, 357); }
  bond { members(8, 358); }
  bond { members(9, 26); }
  bond { members(36, 35); }
  bond { members(45, 62); }
  bond { members(72, 71); }
  bond { members(81, 98); }
  bond { members(108, 107); }
  bond { members(117, 134); }
  bond { members(144, 143); }
  bond { members(153, 170); }
  bond { members(180, 179); }
  bond { members(189, 206); }
  bond { members(216, 215); }
  bond { members(225, 242); }
  bond { members(252, 251); }
  bond { members(261, 278); }
  bond { members(288, 287); }
  bond { members(297, 314); }
  bond { members(324, 323); }
  bond { members(333, 350); }
}

#endif
