Source    = \

RmiSource =

Main      = 

SampleFiles =  \
               Au_nanoparticle_FCC.md \
               Au_nanoparticle.in \
               metals.md

DEV_ROOT=../../../..
include $(DEV_ROOT)/make/Makefile

