#!/opt/local/bin/python

__author__ = "Patrick Louden (plouden@nd.edu)"
__copyright__ = "Copyright (c) 2016 by the University of Notre Dame"
__license__ = "OpenMD"

import sys
import argparse
import textwrap
import numpy as np
from argparse import RawDescriptionHelpFormatter
from mayavi.mlab import *

def usage():
    print __doc__


def plotVectorField(inputFileName):
    inputFile = open(inputFileName, 'r')

    x = np.array([])
    y = np.array([])
    z = np.array([])
    vx = np.array([])
    vy = np.array([])
    vz = np.array([])

    for line in inputFile:
        if line.split()[0] != "#":
            x = np.append(x, line.strip().split()[0])
            y = np.append(y, line.strip().split()[1])
            z = np.append(z, line.strip().split()[2])
            vx = np.append(vx, line.strip().split()[3])
            vy = np.append(vy, line.strip().split()[4])
            vz = np.append(vz, line.strip().split()[5])
    
        
    obj = quiver3d(x, y, z, u, v, w, line_width=3, scale_factor=1)                                                                                                                                                   
    return obj    


def main(argv):
    parser = argparse.ArgumentParser(
        description='A python script used to generate 3d plots of vectors.\n Designed to work with OpenMD (.vectorField) files.',
        formatter_class=RawDescriptionHelpFormatter,
        epilog="Example: vectorFieldViewer -i sim.vectorField")
    parser.add_argument("-i","--inputFile=", action="store",dest="inputFileName", help="the input file name") 
        
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(2)
    
    args = parser.parse_args()

    if (not args.inputFileName):
        parser.print_help()
        parser.error("No input file was specified")

    #Call functions here
    plotVectorField(args.inputFileName)



if __name__ == "__main__":
    #if len(sys.argv) == 1:
        #parser.print_help()
        #usage() # need to change to call argeparse stuffs
        #sys.exit()
    main(sys.argv[1:])
