Package = applications/thermalizer

Source    = \
	thermalizerCmd.c \
	thermalizer.cpp \
	
BuiltParallelExe = 0

RmiSource =

Main      = thermalizer

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

