#ifndef _LJ_INC_
#define _LJ_INC_

molecule{
  name = "Ar";
  
  atom[0]{
     type="Ar";
     position( 0.0, 0.0, 0.0 );
  }
}
molecule{
  name = "Ne";
  
  atom[0]{
     type="Ne";
     position( 0.0, 0.0, 0.0 );
  }
}
molecule{
  name = "He";
  
  atom[0]{
     type="He";
     position( 0.0, 0.0, 0.0 );
  }
}
molecule{
  name = "C";
  
  atom[0]{
     type="C";
     position( 0.0, 0.0, 0.0 );
  }
}
#endif
