Source    = \

RmiSource =

Main      = 

SampleFiles = \
	2gb.in \
	2gb.md \
	gb2lj1.in \
	gb2lj1.md \
	gb.md \
	gbRotRoundX.in \
	gbRotRoundX.md \
	gbRotRoundY.in \
	gbRotRoundY.md \
	gbRotRoundZ.in \
	gbRotRoundZ.md \
	lj.md \


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

