/* GofRCmd.h */

/* File autogenerated by gengetopt version 2.11  */

#ifndef GOFRCMD_H
#define GOFRCMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "gofr"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.00"
#endif

struct gengetopt_args_info
{
  char * input_arg;	/* input dump file.  */
  char * output_arg;	/* output file name.  */
  int frame_arg;	/* print every n frame (default='1').  */
  int nbins_arg;	/* number of bins (default='50').  */
  double length_arg;	/* maximum length.  */
  char * sele1_arg;	/* select first stuntdouble set.  */
  char * sele2_arg;	/* select second stuntdouble set.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_given ;	/* Whether input was given.  */
  int output_given ;	/* Whether output was given.  */
  int frame_given ;	/* Whether frame was given.  */
  int nbins_given ;	/* Whether nbins was given.  */
  int length_given ;	/* Whether length was given.  */
  int sele1_given ;	/* Whether sele1 was given.  */
  int sele2_given ;	/* Whether sele2 was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* GOFRCMD_H */
