Package = applications/staticProps

Source    = \
        GofAngle2.cpp \
        GofRAngle.cpp \
        GofR.cpp  \
        GofZ.cpp  \
        GofXyz.cpp \
        RadialDistrFunc.cpp \
	P2OrderParameter.cpp \
	SCDOrderParameter.cpp \
	DensityPlot.cpp \
	StaticPropsCmd.c \
	StaticProps.cpp \
	RhoZ.cpp \
	Hxy.cpp \
        RippleOP.cpp \
	BondOrderParameter.cpp \
	BOPofR.cpp \
	RhoR.cpp \
	BondAngleDistribution.cpp \
	pAngle.cpp \
	NanoVolume.cpp
BuiltParallelExe = 0

RmiSource =

Main      = StaticProps

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

