Package = applications/staticProps

Source    = \
RadialDistrFunc.cpp \   
GofR.cpp \	    
GofRCmd.c \
GofRMain.cpp \

RmiSource =

Main      = GofRMain 

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

