/*
  File autogenerated by gengetopt version 2.19.1
  generated with the following command:
  gengetopt -i StaticProps.ggo -F StaticPropsCmd -u 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "StaticPropsCmd.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: StaticProps [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=filename          input dump file",
  "  -o, --output=filename         output file name",
  "  -n, --step=INT                process every n frame  (default=`1')",
  "  -b, --nbins=INT               number of bins (general purpose)  \n                                  (default=`100')",
  "  -x, --nbins_x=INT             number of bins in x axis  (default=`100')",
  "  -y, --nbins_y=INT             number of bins in y axis  (default=`100')",
  "  -a, --nanglebins=INT          number of bins for cos(angle)  (default=`50')",
  "      --length=DOUBLE           maximum length (Defaults to 1/2 smallest length \n                                  of first frame)",
  "  -c, --rcut=DOUBLE             cutoff radius (rcut)",
  "  -z, --zoffset=DOUBLE          Where to set the zero for the slab_density \n                                  calculation  (default=`0')",
  "      --sele1=selection script  select the first stuntdouble set",
  "      --sele2=selection script  select the second stuntdouble set",
  "      --sele3=selection script  select the third stuntdouble set",
  "      --refsele=selection script\n                                select reference (use and only use with --gxyz)",
  "      --molname=STRING          molecule name",
  "      --begin=INT               begin internal index",
  "      --end=INT                 end internal index",
  "      --radius=DOUBLE           nanoparticle radius",
  "\n Group: staticProps\n   an option of this group is required",
  "      --bo                      bond order parameter (--rcut must be specified)",
  "      --bor                     bond order parameter as a function of radius \n                                  (--rcut must be specified)",
  "  -g, --gofr                    g(r)",
  "      --r_theta                 g(r, cos(theta))",
  "      --r_omega                 g(r, cos(omega))",
  "      --theta_omega             g(cos(theta), cos(omega))",
  "      --gxyz                    g(x, y, z)",
  "  -p, --p2                      p2 order parameter (--sele1 and --sele2 must be \n                                  specified)",
  "      --rp2                     rp2 order parameter (--sele1 and --sele2 must \n                                  be specified)",
  "  -s, --scd                     scd order parameter (either --sele1, --sele2, \n                                  --sele3 are specified or --molname, --begin, \n                                  --end are specified)",
  "  -d, --density                 density plot",
  "      --slab_density            slab density",
  "      --hxy                     hxy",
  "      --rho_r                   rho of R",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->step_given = 0 ;
  args_info->nbins_given = 0 ;
  args_info->nbins_x_given = 0 ;
  args_info->nbins_y_given = 0 ;
  args_info->nanglebins_given = 0 ;
  args_info->length_given = 0 ;
  args_info->rcut_given = 0 ;
  args_info->zoffset_given = 0 ;
  args_info->sele1_given = 0 ;
  args_info->sele2_given = 0 ;
  args_info->sele3_given = 0 ;
  args_info->refsele_given = 0 ;
  args_info->molname_given = 0 ;
  args_info->begin_given = 0 ;
  args_info->end_given = 0 ;
  args_info->radius_given = 0 ;
  args_info->bo_given = 0 ;
  args_info->bor_given = 0 ;
  args_info->gofr_given = 0 ;
  args_info->r_theta_given = 0 ;
  args_info->r_omega_given = 0 ;
  args_info->theta_omega_given = 0 ;
  args_info->gxyz_given = 0 ;
  args_info->p2_given = 0 ;
  args_info->rp2_given = 0 ;
  args_info->scd_given = 0 ;
  args_info->density_given = 0 ;
  args_info->slab_density_given = 0 ;
  args_info->hxy_given = 0 ;
  args_info->rho_r_given = 0 ;
  args_info->staticProps_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->step_arg = 1;
  args_info->step_orig = NULL;
  args_info->nbins_arg = 100;
  args_info->nbins_orig = NULL;
  args_info->nbins_x_arg = 100;
  args_info->nbins_x_orig = NULL;
  args_info->nbins_y_arg = 100;
  args_info->nbins_y_orig = NULL;
  args_info->nanglebins_arg = 50;
  args_info->nanglebins_orig = NULL;
  args_info->length_orig = NULL;
  args_info->rcut_orig = NULL;
  args_info->zoffset_arg = 0;
  args_info->zoffset_orig = NULL;
  args_info->sele1_arg = NULL;
  args_info->sele1_orig = NULL;
  args_info->sele2_arg = NULL;
  args_info->sele2_orig = NULL;
  args_info->sele3_arg = NULL;
  args_info->sele3_orig = NULL;
  args_info->refsele_arg = NULL;
  args_info->refsele_orig = NULL;
  args_info->molname_arg = NULL;
  args_info->molname_orig = NULL;
  args_info->begin_orig = NULL;
  args_info->end_orig = NULL;
  args_info->radius_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->output_help = gengetopt_args_info_help[3] ;
  args_info->step_help = gengetopt_args_info_help[4] ;
  args_info->nbins_help = gengetopt_args_info_help[5] ;
  args_info->nbins_x_help = gengetopt_args_info_help[6] ;
  args_info->nbins_y_help = gengetopt_args_info_help[7] ;
  args_info->nanglebins_help = gengetopt_args_info_help[8] ;
  args_info->length_help = gengetopt_args_info_help[9] ;
  args_info->rcut_help = gengetopt_args_info_help[10] ;
  args_info->zoffset_help = gengetopt_args_info_help[11] ;
  args_info->sele1_help = gengetopt_args_info_help[12] ;
  args_info->sele2_help = gengetopt_args_info_help[13] ;
  args_info->sele3_help = gengetopt_args_info_help[14] ;
  args_info->refsele_help = gengetopt_args_info_help[15] ;
  args_info->molname_help = gengetopt_args_info_help[16] ;
  args_info->begin_help = gengetopt_args_info_help[17] ;
  args_info->end_help = gengetopt_args_info_help[18] ;
  args_info->radius_help = gengetopt_args_info_help[19] ;
  args_info->bo_help = gengetopt_args_info_help[20] ;
  args_info->bor_help = gengetopt_args_info_help[21] ;
  args_info->gofr_help = gengetopt_args_info_help[22] ;
  args_info->r_theta_help = gengetopt_args_info_help[23] ;
  args_info->r_omega_help = gengetopt_args_info_help[24] ;
  args_info->theta_omega_help = gengetopt_args_info_help[25] ;
  args_info->gxyz_help = gengetopt_args_info_help[26] ;
  args_info->p2_help = gengetopt_args_info_help[27] ;
  args_info->rp2_help = gengetopt_args_info_help[28] ;
  args_info->scd_help = gengetopt_args_info_help[29] ;
  args_info->density_help = gengetopt_args_info_help[30] ;
  args_info->slab_density_help = gengetopt_args_info_help[31] ;
  args_info->hxy_help = gengetopt_args_info_help[32] ;
  args_info->rho_r_help = gengetopt_args_info_help[33] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->input_orig)
    {
      free (args_info->input_orig); /* free previous argument */
      args_info->input_orig = 0;
    }
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->output_orig)
    {
      free (args_info->output_orig); /* free previous argument */
      args_info->output_orig = 0;
    }
  if (args_info->step_orig)
    {
      free (args_info->step_orig); /* free previous argument */
      args_info->step_orig = 0;
    }
  if (args_info->nbins_orig)
    {
      free (args_info->nbins_orig); /* free previous argument */
      args_info->nbins_orig = 0;
    }
  if (args_info->nbins_x_orig)
    {
      free (args_info->nbins_x_orig); /* free previous argument */
      args_info->nbins_x_orig = 0;
    }
  if (args_info->nbins_y_orig)
    {
      free (args_info->nbins_y_orig); /* free previous argument */
      args_info->nbins_y_orig = 0;
    }
  if (args_info->nanglebins_orig)
    {
      free (args_info->nanglebins_orig); /* free previous argument */
      args_info->nanglebins_orig = 0;
    }
  if (args_info->length_orig)
    {
      free (args_info->length_orig); /* free previous argument */
      args_info->length_orig = 0;
    }
  if (args_info->rcut_orig)
    {
      free (args_info->rcut_orig); /* free previous argument */
      args_info->rcut_orig = 0;
    }
  if (args_info->zoffset_orig)
    {
      free (args_info->zoffset_orig); /* free previous argument */
      args_info->zoffset_orig = 0;
    }
  if (args_info->sele1_arg)
    {
      free (args_info->sele1_arg); /* free previous argument */
      args_info->sele1_arg = 0;
    }
  if (args_info->sele1_orig)
    {
      free (args_info->sele1_orig); /* free previous argument */
      args_info->sele1_orig = 0;
    }
  if (args_info->sele2_arg)
    {
      free (args_info->sele2_arg); /* free previous argument */
      args_info->sele2_arg = 0;
    }
  if (args_info->sele2_orig)
    {
      free (args_info->sele2_orig); /* free previous argument */
      args_info->sele2_orig = 0;
    }
  if (args_info->sele3_arg)
    {
      free (args_info->sele3_arg); /* free previous argument */
      args_info->sele3_arg = 0;
    }
  if (args_info->sele3_orig)
    {
      free (args_info->sele3_orig); /* free previous argument */
      args_info->sele3_orig = 0;
    }
  if (args_info->refsele_arg)
    {
      free (args_info->refsele_arg); /* free previous argument */
      args_info->refsele_arg = 0;
    }
  if (args_info->refsele_orig)
    {
      free (args_info->refsele_orig); /* free previous argument */
      args_info->refsele_orig = 0;
    }
  if (args_info->molname_arg)
    {
      free (args_info->molname_arg); /* free previous argument */
      args_info->molname_arg = 0;
    }
  if (args_info->molname_orig)
    {
      free (args_info->molname_orig); /* free previous argument */
      args_info->molname_orig = 0;
    }
  if (args_info->begin_orig)
    {
      free (args_info->begin_orig); /* free previous argument */
      args_info->begin_orig = 0;
    }
  if (args_info->end_orig)
    {
      free (args_info->end_orig); /* free previous argument */
      args_info->end_orig = 0;
    }
  if (args_info->radius_orig)
    {
      free (args_info->radius_orig); /* free previous argument */
      args_info->radius_orig = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->input_given) {
    if (args_info->input_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "input", args_info->input_orig);
    } else {
      fprintf(outfile, "%s\n", "input");
    }
  }
  if (args_info->output_given) {
    if (args_info->output_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output", args_info->output_orig);
    } else {
      fprintf(outfile, "%s\n", "output");
    }
  }
  if (args_info->step_given) {
    if (args_info->step_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "step", args_info->step_orig);
    } else {
      fprintf(outfile, "%s\n", "step");
    }
  }
  if (args_info->nbins_given) {
    if (args_info->nbins_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "nbins", args_info->nbins_orig);
    } else {
      fprintf(outfile, "%s\n", "nbins");
    }
  }
  if (args_info->nbins_x_given) {
    if (args_info->nbins_x_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "nbins_x", args_info->nbins_x_orig);
    } else {
      fprintf(outfile, "%s\n", "nbins_x");
    }
  }
  if (args_info->nbins_y_given) {
    if (args_info->nbins_y_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "nbins_y", args_info->nbins_y_orig);
    } else {
      fprintf(outfile, "%s\n", "nbins_y");
    }
  }
  if (args_info->nanglebins_given) {
    if (args_info->nanglebins_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "nanglebins", args_info->nanglebins_orig);
    } else {
      fprintf(outfile, "%s\n", "nanglebins");
    }
  }
  if (args_info->length_given) {
    if (args_info->length_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "length", args_info->length_orig);
    } else {
      fprintf(outfile, "%s\n", "length");
    }
  }
  if (args_info->rcut_given) {
    if (args_info->rcut_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "rcut", args_info->rcut_orig);
    } else {
      fprintf(outfile, "%s\n", "rcut");
    }
  }
  if (args_info->zoffset_given) {
    if (args_info->zoffset_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "zoffset", args_info->zoffset_orig);
    } else {
      fprintf(outfile, "%s\n", "zoffset");
    }
  }
  if (args_info->sele1_given) {
    if (args_info->sele1_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "sele1", args_info->sele1_orig);
    } else {
      fprintf(outfile, "%s\n", "sele1");
    }
  }
  if (args_info->sele2_given) {
    if (args_info->sele2_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "sele2", args_info->sele2_orig);
    } else {
      fprintf(outfile, "%s\n", "sele2");
    }
  }
  if (args_info->sele3_given) {
    if (args_info->sele3_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "sele3", args_info->sele3_orig);
    } else {
      fprintf(outfile, "%s\n", "sele3");
    }
  }
  if (args_info->refsele_given) {
    if (args_info->refsele_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "refsele", args_info->refsele_orig);
    } else {
      fprintf(outfile, "%s\n", "refsele");
    }
  }
  if (args_info->molname_given) {
    if (args_info->molname_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "molname", args_info->molname_orig);
    } else {
      fprintf(outfile, "%s\n", "molname");
    }
  }
  if (args_info->begin_given) {
    if (args_info->begin_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "begin", args_info->begin_orig);
    } else {
      fprintf(outfile, "%s\n", "begin");
    }
  }
  if (args_info->end_given) {
    if (args_info->end_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "end", args_info->end_orig);
    } else {
      fprintf(outfile, "%s\n", "end");
    }
  }
  if (args_info->radius_given) {
    if (args_info->radius_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "radius", args_info->radius_orig);
    } else {
      fprintf(outfile, "%s\n", "radius");
    }
  }
  if (args_info->bo_given) {
    fprintf(outfile, "%s\n", "bo");
  }
  if (args_info->bor_given) {
    fprintf(outfile, "%s\n", "bor");
  }
  if (args_info->gofr_given) {
    fprintf(outfile, "%s\n", "gofr");
  }
  if (args_info->r_theta_given) {
    fprintf(outfile, "%s\n", "r_theta");
  }
  if (args_info->r_omega_given) {
    fprintf(outfile, "%s\n", "r_omega");
  }
  if (args_info->theta_omega_given) {
    fprintf(outfile, "%s\n", "theta_omega");
  }
  if (args_info->gxyz_given) {
    fprintf(outfile, "%s\n", "gxyz");
  }
  if (args_info->p2_given) {
    fprintf(outfile, "%s\n", "p2");
  }
  if (args_info->rp2_given) {
    fprintf(outfile, "%s\n", "rp2");
  }
  if (args_info->scd_given) {
    fprintf(outfile, "%s\n", "scd");
  }
  if (args_info->density_given) {
    fprintf(outfile, "%s\n", "density");
  }
  if (args_info->slab_density_given) {
    fprintf(outfile, "%s\n", "slab_density");
  }
  if (args_info->hxy_given) {
    fprintf(outfile, "%s\n", "hxy");
  }
  if (args_info->rho_r_given) {
    fprintf(outfile, "%s\n", "rho_r");
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_staticProps(struct gengetopt_args_info *args_info);

static void
reset_group_staticProps(struct gengetopt_args_info *args_info)
{
  if (! args_info->staticProps_group_counter)
    return;
  
  args_info->bo_given = 0 ;
  args_info->bor_given = 0 ;
  args_info->gofr_given = 0 ;
  args_info->r_theta_given = 0 ;
  args_info->r_omega_given = 0 ;
  args_info->theta_omega_given = 0 ;
  args_info->gxyz_given = 0 ;
  args_info->p2_given = 0 ;
  args_info->rp2_given = 0 ;
  args_info->scd_given = 0 ;
  args_info->density_given = 0 ;
  args_info->slab_density_given = 0 ;
  args_info->hxy_given = 0 ;
  args_info->rho_r_given = 0 ;

  args_info->staticProps_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->staticProps_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group staticProps were given. One is required.%s\n", prog_name, args_info->staticProps_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  

  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "step",	1, NULL, 'n' },
        { "nbins",	1, NULL, 'b' },
        { "nbins_x",	1, NULL, 'x' },
        { "nbins_y",	1, NULL, 'y' },
        { "nanglebins",	1, NULL, 'a' },
        { "length",	1, NULL, 0 },
        { "rcut",	1, NULL, 'c' },
        { "zoffset",	1, NULL, 'z' },
        { "sele1",	1, NULL, 0 },
        { "sele2",	1, NULL, 0 },
        { "sele3",	1, NULL, 0 },
        { "refsele",	1, NULL, 0 },
        { "molname",	1, NULL, 0 },
        { "begin",	1, NULL, 0 },
        { "end",	1, NULL, 0 },
        { "radius",	1, NULL, 0 },
        { "bo",	0, NULL, 0 },
        { "bor",	0, NULL, 0 },
        { "gofr",	0, NULL, 'g' },
        { "r_theta",	0, NULL, 0 },
        { "r_omega",	0, NULL, 0 },
        { "theta_omega",	0, NULL, 0 },
        { "gxyz",	0, NULL, 0 },
        { "p2",	0, NULL, 'p' },
        { "rp2",	0, NULL, 0 },
        { "scd",	0, NULL, 's' },
        { "density",	0, NULL, 'd' },
        { "slab_density",	0, NULL, 0 },
        { "hxy",	0, NULL, 0 },
        { "rho_r",	0, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:o:n:b:x:y:a:c:z:gpsd", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* input dump file.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          if (args_info->input_orig)
            free (args_info->input_orig); /* free previous string */
          args_info->input_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* output file name.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          if (args_info->output_orig)
            free (args_info->output_orig); /* free previous string */
          args_info->output_orig = gengetopt_strdup (optarg);
          break;

        case 'n':	/* process every n frame.  */
          if (local_args_info.step_given)
            {
              fprintf (stderr, "%s: `--step' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->step_given && ! override)
            continue;
          local_args_info.step_given = 1;
          args_info->step_given = 1;
          args_info->step_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->step_orig)
            free (args_info->step_orig); /* free previous string */
          args_info->step_orig = gengetopt_strdup (optarg);
          break;

        case 'b':	/* number of bins (general purpose).  */
          if (local_args_info.nbins_given)
            {
              fprintf (stderr, "%s: `--nbins' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nbins_given && ! override)
            continue;
          local_args_info.nbins_given = 1;
          args_info->nbins_given = 1;
          args_info->nbins_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->nbins_orig)
            free (args_info->nbins_orig); /* free previous string */
          args_info->nbins_orig = gengetopt_strdup (optarg);
          break;

        case 'x':	/* number of bins in x axis.  */
          if (local_args_info.nbins_x_given)
            {
              fprintf (stderr, "%s: `--nbins_x' (`-x') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nbins_x_given && ! override)
            continue;
          local_args_info.nbins_x_given = 1;
          args_info->nbins_x_given = 1;
          args_info->nbins_x_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->nbins_x_orig)
            free (args_info->nbins_x_orig); /* free previous string */
          args_info->nbins_x_orig = gengetopt_strdup (optarg);
          break;

        case 'y':	/* number of bins in y axis.  */
          if (local_args_info.nbins_y_given)
            {
              fprintf (stderr, "%s: `--nbins_y' (`-y') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nbins_y_given && ! override)
            continue;
          local_args_info.nbins_y_given = 1;
          args_info->nbins_y_given = 1;
          args_info->nbins_y_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->nbins_y_orig)
            free (args_info->nbins_y_orig); /* free previous string */
          args_info->nbins_y_orig = gengetopt_strdup (optarg);
          break;

        case 'a':	/* number of bins for cos(angle).  */
          if (local_args_info.nanglebins_given)
            {
              fprintf (stderr, "%s: `--nanglebins' (`-a') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nanglebins_given && ! override)
            continue;
          local_args_info.nanglebins_given = 1;
          args_info->nanglebins_given = 1;
          args_info->nanglebins_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->nanglebins_orig)
            free (args_info->nanglebins_orig); /* free previous string */
          args_info->nanglebins_orig = gengetopt_strdup (optarg);
          break;

        case 'c':	/* cutoff radius (rcut).  */
          if (local_args_info.rcut_given)
            {
              fprintf (stderr, "%s: `--rcut' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->rcut_given && ! override)
            continue;
          local_args_info.rcut_given = 1;
          args_info->rcut_given = 1;
          args_info->rcut_arg = strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->rcut_orig)
            free (args_info->rcut_orig); /* free previous string */
          args_info->rcut_orig = gengetopt_strdup (optarg);
          break;

        case 'z':	/* Where to set the zero for the slab_density calculation.  */
          if (local_args_info.zoffset_given)
            {
              fprintf (stderr, "%s: `--zoffset' (`-z') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->zoffset_given && ! override)
            continue;
          local_args_info.zoffset_given = 1;
          args_info->zoffset_given = 1;
          args_info->zoffset_arg = strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->zoffset_orig)
            free (args_info->zoffset_orig); /* free previous string */
          args_info->zoffset_orig = gengetopt_strdup (optarg);
          break;

        case 'g':	/* g(r).  */
          if (local_args_info.gofr_given)
            {
              fprintf (stderr, "%s: `--gofr' (`-g') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->gofr_given && ! override)
            continue;
          local_args_info.gofr_given = 1;
          args_info->gofr_given = 1;
          if (args_info->staticProps_group_counter && override)
            reset_group_staticProps (args_info);
          args_info->staticProps_group_counter += 1;
          break;

        case 'p':	/* p2 order parameter (--sele1 and --sele2 must be specified).  */
          if (local_args_info.p2_given)
            {
              fprintf (stderr, "%s: `--p2' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->p2_given && ! override)
            continue;
          local_args_info.p2_given = 1;
          args_info->p2_given = 1;
          if (args_info->staticProps_group_counter && override)
            reset_group_staticProps (args_info);
          args_info->staticProps_group_counter += 1;
          break;

        case 's':	/* scd order parameter (either --sele1, --sele2, --sele3 are specified or --molname, --begin, --end are specified).  */
          if (local_args_info.scd_given)
            {
              fprintf (stderr, "%s: `--scd' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->scd_given && ! override)
            continue;
          local_args_info.scd_given = 1;
          args_info->scd_given = 1;
          if (args_info->staticProps_group_counter && override)
            reset_group_staticProps (args_info);
          args_info->staticProps_group_counter += 1;
          break;

        case 'd':	/* density plot.  */
          if (local_args_info.density_given)
            {
              fprintf (stderr, "%s: `--density' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->density_given && ! override)
            continue;
          local_args_info.density_given = 1;
          args_info->density_given = 1;
          if (args_info->staticProps_group_counter && override)
            reset_group_staticProps (args_info);
          args_info->staticProps_group_counter += 1;
          break;


        case 0:	/* Long option with no short option */
          /* maximum length (Defaults to 1/2 smallest length of first frame).  */
          if (strcmp (long_options[option_index].name, "length") == 0)
          {
            if (local_args_info.length_given)
              {
                fprintf (stderr, "%s: `--length' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->length_given && ! override)
              continue;
            local_args_info.length_given = 1;
            args_info->length_given = 1;
            args_info->length_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->length_orig)
              free (args_info->length_orig); /* free previous string */
            args_info->length_orig = gengetopt_strdup (optarg);
          }
          /* select the first stuntdouble set.  */
          else if (strcmp (long_options[option_index].name, "sele1") == 0)
          {
            if (local_args_info.sele1_given)
              {
                fprintf (stderr, "%s: `--sele1' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->sele1_given && ! override)
              continue;
            local_args_info.sele1_given = 1;
            args_info->sele1_given = 1;
            if (args_info->sele1_arg)
              free (args_info->sele1_arg); /* free previous string */
            args_info->sele1_arg = gengetopt_strdup (optarg);
            if (args_info->sele1_orig)
              free (args_info->sele1_orig); /* free previous string */
            args_info->sele1_orig = gengetopt_strdup (optarg);
          }
          /* select the second stuntdouble set.  */
          else if (strcmp (long_options[option_index].name, "sele2") == 0)
          {
            if (local_args_info.sele2_given)
              {
                fprintf (stderr, "%s: `--sele2' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->sele2_given && ! override)
              continue;
            local_args_info.sele2_given = 1;
            args_info->sele2_given = 1;
            if (args_info->sele2_arg)
              free (args_info->sele2_arg); /* free previous string */
            args_info->sele2_arg = gengetopt_strdup (optarg);
            if (args_info->sele2_orig)
              free (args_info->sele2_orig); /* free previous string */
            args_info->sele2_orig = gengetopt_strdup (optarg);
          }
          /* select the third stuntdouble set.  */
          else if (strcmp (long_options[option_index].name, "sele3") == 0)
          {
            if (local_args_info.sele3_given)
              {
                fprintf (stderr, "%s: `--sele3' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->sele3_given && ! override)
              continue;
            local_args_info.sele3_given = 1;
            args_info->sele3_given = 1;
            if (args_info->sele3_arg)
              free (args_info->sele3_arg); /* free previous string */
            args_info->sele3_arg = gengetopt_strdup (optarg);
            if (args_info->sele3_orig)
              free (args_info->sele3_orig); /* free previous string */
            args_info->sele3_orig = gengetopt_strdup (optarg);
          }
          /* select reference (use and only use with --gxyz).  */
          else if (strcmp (long_options[option_index].name, "refsele") == 0)
          {
            if (local_args_info.refsele_given)
              {
                fprintf (stderr, "%s: `--refsele' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->refsele_given && ! override)
              continue;
            local_args_info.refsele_given = 1;
            args_info->refsele_given = 1;
            if (args_info->refsele_arg)
              free (args_info->refsele_arg); /* free previous string */
            args_info->refsele_arg = gengetopt_strdup (optarg);
            if (args_info->refsele_orig)
              free (args_info->refsele_orig); /* free previous string */
            args_info->refsele_orig = gengetopt_strdup (optarg);
          }
          /* molecule name.  */
          else if (strcmp (long_options[option_index].name, "molname") == 0)
          {
            if (local_args_info.molname_given)
              {
                fprintf (stderr, "%s: `--molname' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->molname_given && ! override)
              continue;
            local_args_info.molname_given = 1;
            args_info->molname_given = 1;
            if (args_info->molname_arg)
              free (args_info->molname_arg); /* free previous string */
            args_info->molname_arg = gengetopt_strdup (optarg);
            if (args_info->molname_orig)
              free (args_info->molname_orig); /* free previous string */
            args_info->molname_orig = gengetopt_strdup (optarg);
          }
          /* begin internal index.  */
          else if (strcmp (long_options[option_index].name, "begin") == 0)
          {
            if (local_args_info.begin_given)
              {
                fprintf (stderr, "%s: `--begin' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->begin_given && ! override)
              continue;
            local_args_info.begin_given = 1;
            args_info->begin_given = 1;
            args_info->begin_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->begin_orig)
              free (args_info->begin_orig); /* free previous string */
            args_info->begin_orig = gengetopt_strdup (optarg);
          }
          /* end internal index.  */
          else if (strcmp (long_options[option_index].name, "end") == 0)
          {
            if (local_args_info.end_given)
              {
                fprintf (stderr, "%s: `--end' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->end_given && ! override)
              continue;
            local_args_info.end_given = 1;
            args_info->end_given = 1;
            args_info->end_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->end_orig)
              free (args_info->end_orig); /* free previous string */
            args_info->end_orig = gengetopt_strdup (optarg);
          }
          /* nanoparticle radius.  */
          else if (strcmp (long_options[option_index].name, "radius") == 0)
          {
            if (local_args_info.radius_given)
              {
                fprintf (stderr, "%s: `--radius' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->radius_given && ! override)
              continue;
            local_args_info.radius_given = 1;
            args_info->radius_given = 1;
            args_info->radius_arg = strtod (optarg, &stop_char);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->radius_orig)
              free (args_info->radius_orig); /* free previous string */
            args_info->radius_orig = gengetopt_strdup (optarg);
          }
          /* bond order parameter (--rcut must be specified).  */
          else if (strcmp (long_options[option_index].name, "bo") == 0)
          {
            if (local_args_info.bo_given)
              {
                fprintf (stderr, "%s: `--bo' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->bo_given && ! override)
              continue;
            local_args_info.bo_given = 1;
            args_info->bo_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* bond order parameter as a function of radius (--rcut must be specified).  */
          else if (strcmp (long_options[option_index].name, "bor") == 0)
          {
            if (local_args_info.bor_given)
              {
                fprintf (stderr, "%s: `--bor' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->bor_given && ! override)
              continue;
            local_args_info.bor_given = 1;
            args_info->bor_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* g(r, cos(theta)).  */
          else if (strcmp (long_options[option_index].name, "r_theta") == 0)
          {
            if (local_args_info.r_theta_given)
              {
                fprintf (stderr, "%s: `--r_theta' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->r_theta_given && ! override)
              continue;
            local_args_info.r_theta_given = 1;
            args_info->r_theta_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* g(r, cos(omega)).  */
          else if (strcmp (long_options[option_index].name, "r_omega") == 0)
          {
            if (local_args_info.r_omega_given)
              {
                fprintf (stderr, "%s: `--r_omega' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->r_omega_given && ! override)
              continue;
            local_args_info.r_omega_given = 1;
            args_info->r_omega_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* g(cos(theta), cos(omega)).  */
          else if (strcmp (long_options[option_index].name, "theta_omega") == 0)
          {
            if (local_args_info.theta_omega_given)
              {
                fprintf (stderr, "%s: `--theta_omega' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->theta_omega_given && ! override)
              continue;
            local_args_info.theta_omega_given = 1;
            args_info->theta_omega_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* g(x, y, z).  */
          else if (strcmp (long_options[option_index].name, "gxyz") == 0)
          {
            if (local_args_info.gxyz_given)
              {
                fprintf (stderr, "%s: `--gxyz' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->gxyz_given && ! override)
              continue;
            local_args_info.gxyz_given = 1;
            args_info->gxyz_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* rp2 order parameter (--sele1 and --sele2 must be specified).  */
          else if (strcmp (long_options[option_index].name, "rp2") == 0)
          {
            if (local_args_info.rp2_given)
              {
                fprintf (stderr, "%s: `--rp2' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->rp2_given && ! override)
              continue;
            local_args_info.rp2_given = 1;
            args_info->rp2_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* slab density.  */
          else if (strcmp (long_options[option_index].name, "slab_density") == 0)
          {
            if (local_args_info.slab_density_given)
              {
                fprintf (stderr, "%s: `--slab_density' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->slab_density_given && ! override)
              continue;
            local_args_info.slab_density_given = 1;
            args_info->slab_density_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* hxy.  */
          else if (strcmp (long_options[option_index].name, "hxy") == 0)
          {
            if (local_args_info.hxy_given)
              {
                fprintf (stderr, "%s: `--hxy' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->hxy_given && ! override)
              continue;
            local_args_info.hxy_given = 1;
            args_info->hxy_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          /* rho of R.  */
          else if (strcmp (long_options[option_index].name, "rho_r") == 0)
          {
            if (local_args_info.rho_r_given)
              {
                fprintf (stderr, "%s: `--rho_r' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->rho_r_given && ! override)
              continue;
            local_args_info.rho_r_given = 1;
            args_info->rho_r_given = 1;
            if (args_info->staticProps_group_counter && override)
              reset_group_staticProps (args_info);
            args_info->staticProps_group_counter += 1;
            break;
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->staticProps_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group staticProps were given. One is required.%s\n", argv[0], args_info->staticProps_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
