/* StaticPropsCmd.h */

/* File autogenerated by gengetopt version 2.19.1  */

#ifndef STATICPROPSCMD_H
#define STATICPROPSCMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "StaticProps"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.00"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  char * input_arg;	/* input dump file.  */
  char * input_orig;	/* input dump file original value given at command line.  */
  const char *input_help; /* input dump file help description.  */
  char * output_arg;	/* output file name.  */
  char * output_orig;	/* output file name original value given at command line.  */
  const char *output_help; /* output file name help description.  */
  int step_arg;	/* process every n frame (default='1').  */
  char * step_orig;	/* process every n frame original value given at command line.  */
  const char *step_help; /* process every n frame help description.  */
  int nbins_arg;	/* number of bins (general purpose) (default='100').  */
  char * nbins_orig;	/* number of bins (general purpose) original value given at command line.  */
  const char *nbins_help; /* number of bins (general purpose) help description.  */
  int nbins_x_arg;	/* number of bins in x axis (default='100').  */
  char * nbins_x_orig;	/* number of bins in x axis original value given at command line.  */
  const char *nbins_x_help; /* number of bins in x axis help description.  */
  int nbins_y_arg;	/* number of bins in y axis (default='100').  */
  char * nbins_y_orig;	/* number of bins in y axis original value given at command line.  */
  const char *nbins_y_help; /* number of bins in y axis help description.  */
  int nanglebins_arg;	/* number of bins for cos(angle) (default='50').  */
  char * nanglebins_orig;	/* number of bins for cos(angle) original value given at command line.  */
  const char *nanglebins_help; /* number of bins for cos(angle) help description.  */
  double length_arg;	/* maximum length (Defaults to 1/2 smallest length of first frame).  */
  char * length_orig;	/* maximum length (Defaults to 1/2 smallest length of first frame) original value given at command line.  */
  const char *length_help; /* maximum length (Defaults to 1/2 smallest length of first frame) help description.  */
  double rcut_arg;	/* cutoff radius (rcut).  */
  char * rcut_orig;	/* cutoff radius (rcut) original value given at command line.  */
  const char *rcut_help; /* cutoff radius (rcut) help description.  */
  double zoffset_arg;	/* Where to set the zero for the slab_density calculation (default='0').  */
  char * zoffset_orig;	/* Where to set the zero for the slab_density calculation original value given at command line.  */
  const char *zoffset_help; /* Where to set the zero for the slab_density calculation help description.  */
  char * sele1_arg;	/* select the first stuntdouble set.  */
  char * sele1_orig;	/* select the first stuntdouble set original value given at command line.  */
  const char *sele1_help; /* select the first stuntdouble set help description.  */
  char * sele2_arg;	/* select the second stuntdouble set.  */
  char * sele2_orig;	/* select the second stuntdouble set original value given at command line.  */
  const char *sele2_help; /* select the second stuntdouble set help description.  */
  char * sele3_arg;	/* select the third stuntdouble set.  */
  char * sele3_orig;	/* select the third stuntdouble set original value given at command line.  */
  const char *sele3_help; /* select the third stuntdouble set help description.  */
  char * refsele_arg;	/* select reference (use and only use with --gxyz).  */
  char * refsele_orig;	/* select reference (use and only use with --gxyz) original value given at command line.  */
  const char *refsele_help; /* select reference (use and only use with --gxyz) help description.  */
  char * molname_arg;	/* molecule name.  */
  char * molname_orig;	/* molecule name original value given at command line.  */
  const char *molname_help; /* molecule name help description.  */
  int begin_arg;	/* begin internal index.  */
  char * begin_orig;	/* begin internal index original value given at command line.  */
  const char *begin_help; /* begin internal index help description.  */
  int end_arg;	/* end internal index.  */
  char * end_orig;	/* end internal index original value given at command line.  */
  const char *end_help; /* end internal index help description.  */
  double radius_arg;	/* nanoparticle radius.  */
  char * radius_orig;	/* nanoparticle radius original value given at command line.  */
  const char *radius_help; /* nanoparticle radius help description.  */
  const char *bo_help; /* bond order parameter (--rcut must be specified) help description.  */
  const char *bor_help; /* bond order parameter as a function of radius (--rcut must be specified) help description.  */
  const char *gofr_help; /* g(r) help description.  */
  const char *r_theta_help; /* g(r, cos(theta)) help description.  */
  const char *r_omega_help; /* g(r, cos(omega)) help description.  */
  const char *theta_omega_help; /* g(cos(theta), cos(omega)) help description.  */
  const char *gxyz_help; /* g(x, y, z) help description.  */
  const char *p2_help; /* p2 order parameter (--sele1 and --sele2 must be specified) help description.  */
  const char *rp2_help; /* rp2 order parameter (--sele1 and --sele2 must be specified) help description.  */
  const char *scd_help; /* scd order parameter (either --sele1, --sele2, --sele3 are specified or --molname, --begin, --end are specified) help description.  */
  const char *density_help; /* density plot help description.  */
  const char *slab_density_help; /* slab density help description.  */
  const char *hxy_help; /* hxy help description.  */
  const char *rho_r_help; /* rho of R help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_given ;	/* Whether input was given.  */
  int output_given ;	/* Whether output was given.  */
  int step_given ;	/* Whether step was given.  */
  int nbins_given ;	/* Whether nbins was given.  */
  int nbins_x_given ;	/* Whether nbins_x was given.  */
  int nbins_y_given ;	/* Whether nbins_y was given.  */
  int nanglebins_given ;	/* Whether nanglebins was given.  */
  int length_given ;	/* Whether length was given.  */
  int rcut_given ;	/* Whether rcut was given.  */
  int zoffset_given ;	/* Whether zoffset was given.  */
  int sele1_given ;	/* Whether sele1 was given.  */
  int sele2_given ;	/* Whether sele2 was given.  */
  int sele3_given ;	/* Whether sele3 was given.  */
  int refsele_given ;	/* Whether refsele was given.  */
  int molname_given ;	/* Whether molname was given.  */
  int begin_given ;	/* Whether begin was given.  */
  int end_given ;	/* Whether end was given.  */
  int radius_given ;	/* Whether radius was given.  */
  int bo_given ;	/* Whether bo was given.  */
  int bor_given ;	/* Whether bor was given.  */
  int gofr_given ;	/* Whether gofr was given.  */
  int r_theta_given ;	/* Whether r_theta was given.  */
  int r_omega_given ;	/* Whether r_omega was given.  */
  int theta_omega_given ;	/* Whether theta_omega was given.  */
  int gxyz_given ;	/* Whether gxyz was given.  */
  int p2_given ;	/* Whether p2 was given.  */
  int rp2_given ;	/* Whether rp2 was given.  */
  int scd_given ;	/* Whether scd was given.  */
  int density_given ;	/* Whether density was given.  */
  int slab_density_given ;	/* Whether slab_density was given.  */
  int hxy_given ;	/* Whether hxy was given.  */
  int rho_r_given ;	/* Whether rho_r was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
  int staticProps_group_counter; /* counter for group staticProps */
} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* STATICPROPSCMD_H */
