#ifndef _LIPID_INC_
#define _LIPID_INC_

molecule{
  
  name = "simpleLipid_16";
  

  atom[0]{
    type = "HEAD";
    position( 0.0, 1.01479, 0.65901 );
    orientation( 0.0, 0.0, 0.0 );
  }
  atom[1]{
    type = "CH2";
    position( 0.0, -0.8387, -1.292 );
  }
  atom[2]{
    type = "CH2";
    position( 0.0, 0.0, -2.584 );
  }
  atom[3]{
    type = "CH2";
    position( 0.0, -0.8387, -3.876 );
  }
  atom[4]{
    type = "CH2";
    position( 0.0, 0.0, -5.168 );
  }
  atom[5]{
    type = "CH2";
    position( 0.0, -0.8387, -6.46 );
  }
  atom[6]{
    type = "CH2";
    position( 0.0, 0.0, -7.752 );
  }
  atom[7]{
    type = "CH2";
    position( 0.0, -0.8387, -9.044 );
  }
  atom[8]{
    type = "CH2";
    position( 0.0, 0.0, -10.336 );
  }
  atom[9]{
    type = "CH2";
    position( 0.0, -0.8387, -11.628 );
  }
  atom[10]{
    type = "CH2";
    position( 0.0, 0.0, -12.92 );
  }
  atom[11]{
    type = "CH2";
    position( 0.0, -0.8387, -14.212 );
  }
  atom[12]{
    type = "CH2";
    position( 0.0, 0.0, -15.504 );
  }
  atom[13]{
    type = "CH2";
    position( 0.0, -0.8387, -16.796 );
  }
  atom[14]{
    type = "CH2";
    position( 0.0, 0.0, -18.08 );
  }
  atom[15]{
    type = "CH2";
    position( 0.0, -0.8387, -19.38 );
  }
  atom[16]{
    type = "CH3";
    position( 0.0, 0.0, -20.672 );
  }

  

  bond{
    members( 0, 1 );
  }
  bond{
    members( 1, 2 );
  }
  bond{
    members( 2, 3 );
  }
  bond{
    members( 3, 4 );
  }
  bond{
    members( 4, 5 );
  }
  bond{
    members( 5, 6 );
  }
  bond{
    members( 6, 7 );
  }
  bond{
    members( 7, 8 );
  }
  bond{
    members( 8, 9 );
  }
  bond{
    members( 9, 10 );
  }
  bond{
    members( 10, 11 );
  }
  bond{
    members( 11, 12 );
  }
  bond{
    members( 12, 13 );
  }
  bond{
    members( 13, 14 );
  }
  bond{
    members( 14, 15 );
  }
  bond{
    members( 15, 16 );
  }

  

  bend{
    members( 0, 1, 2 );
  }
  bend{
    members( 1, 2, 3 );
  }
  bend{
    members( 2, 3, 4 );
  }
  bend{
    members( 3, 4, 5 );
  }
  bend{
    members( 4, 5, 6 );
  }
  bend{
    members( 5, 6, 7 );
  }
  bend{
    members( 6, 7, 8 );
  }
  bend{
    members( 7, 8, 9 );
  }
  bend{
    members( 8, 9, 10 );
  }
  bend{
    members( 9, 10, 11 );
  }
  bend{
    members( 10, 11, 12 );
  }
  bend{
    members( 11, 12, 13 );
  }
  bend{
    members( 12, 13, 14 );
  }
  bend{
    members( 13, 14, 15 );
  }
  bend{
    members( 14, 15, 16 );
  }

  

  torsion{
    members( 0, 1, 2, 3 );
  }
  torsion{
    members( 1, 2, 3, 4 );
  }
  torsion{
    members( 2, 3, 4, 5 );
  }
  torsion{
    members( 3, 4, 5, 6 );
  }
  torsion{
    members( 4, 5, 6, 7 );
  }
  torsion{
    members( 5, 6, 7, 8 );
  }
  torsion{
    members( 6, 7, 8, 9 );
  }
  torsion{
    members( 7, 8, 9, 10 );
  }
  torsion{
    members( 8, 9, 10, 11 );
  }
  torsion{
    members( 9, 10, 11, 12 );
  }
  torsion{
    members( 10, 11, 12, 13 );
  }
  torsion{
    members( 11, 12, 13, 14 );
  }
  torsion{
    members( 12, 13, 14, 15 );
  }
  torsion{
    members( 13, 14, 15, 16 );
  }
}

molecule{
  
  name = "simpleLipid_16G";
  

  atom[0]{
    type = "HEAD";
    position( 0.0, 1.01479, 0.65901 );
    orientation( 0.0, 0.0, 0.0 );
  }
  atom[1]{
    type = "CH2";
    position( 0.0, -0.8387, -1.292 );
  }
  atom[2]{
    type = "CH2";
    position( 0.0, 0.0, -2.584 );
  }
  atom[3]{
    type = "CH2";
    position( 0.0, -0.8387, -3.876 );
  }
  atom[4]{
    type = "CH2";
    position( 0.0, 0.0, -5.168 );
  }
  atom[5]{
    type = "CH2";
    position( 0.0, -0.8387, -6.46 );
  }
  atom[6]{
    type = "CH2";
    position( 0.0, 0.0, -7.752 );
  }
  atom[7]{
    type = "CH2";
    position( 0.0, -0.8387, -9.044 );
  }
  atom[8]{
    type = "CH2";
    position( 0.0, 0.0, -10.336 );
  }
  atom[9]{
    type = "CH2";
    position( 0.0, -0.8387, -11.628 );
  }
  atom[10]{
    type = "CH2";
    position( 0.0, 0.0, -12.92 );
  }
  atom[11]{
    type = "CH2";
    position( 0.0, -0.8387, -14.212 );
  }
  atom[12]{
    type = "CH2";
    position( 0.0, 0.0, -15.504 );
  }
  atom[13]{
    type = "CH2";
    position( 0.0, -0.8387, -16.796 );
  }
  atom[14]{
    type = "CH2";
    position( 0.0, 0.0, -18.08 );
  }
  atom[15]{
    type = "CH2";
    position( 0.0, -0.8387, -19.38 );
  }
  atom[16]{
    type = "CH3";
    position( 0.0, 0.0, -20.672 );
  }

  

  bond{
    members( 0, 1 );
  }
  bond{
    members( 1, 2 );
  }
  bond{
    members( 2, 3 );
  }
  bond{
    members( 3, 4 );
  }
  bond{
    members( 4, 5 );
  }
  bond{
    members( 5, 6 );
  }
  bond{
    members( 6, 7 );
  }
  bond{
    members( 7, 8 );
  }
  bond{
    members( 8, 9 );
  }
  bond{
    members( 9, 10 );
  }
  bond{
    members( 10, 11 );
  }
  bond{
    members( 11, 12 );
  }
  bond{
    members( 12, 13 );
  }
  bond{
    members( 13, 14 );
  }
  bond{
    members( 14, 15 );
  }
  bond{
    members( 15, 16 );
  }

  

  bend{
    members( 0, 1, 2 );
  }
  bend{
    members( 1, 2, 3 );
  }
  bend{
    members( 2, 3, 4 );
  }
  bend{
    members( 3, 4, 5 );
  }
  bend{
    members( 4, 5, 6 );
  }
  bend{
    members( 5, 6, 7 );
  }
  bend{
    members( 6, 7, 8 );
  }
  bend{
    members( 7, 8, 9 );
  }
  bend{
    members( 8, 9, 10 );
  }
  bend{
    members( 9, 10, 11 );
  }
  bend{
    members( 10, 11, 12 );
  }
  bend{
    members( 11, 12, 13 );
  }
  bend{
    members( 12, 13, 14 );
  }
  bend{
    members( 13, 14, 15 );
  }
  bend{
    members( 14, 15, 16 );
  }
  bend{
    members( 0, 1 );
    ghostVectorSource = 0;
  }


  

  torsion{
    members( 0, 1, 2, 3 );
  }
  torsion{
    members( 1, 2, 3, 4 );
  }
  torsion{
    members( 2, 3, 4, 5 );
  }
  torsion{
    members( 3, 4, 5, 6 );
  }
  torsion{
    members( 4, 5, 6, 7 );
  }
  torsion{
    members( 5, 6, 7, 8 );
  }
  torsion{
    members( 6, 7, 8, 9 );
  }
  torsion{
    members( 7, 8, 9, 10 );
  }
  torsion{
    members( 8, 9, 10, 11 );
  }
  torsion{
    members( 9, 10, 11, 12 );
  }
  torsion{
    members( 10, 11, 12, 13 );
  }
  torsion{
    members( 11, 12, 13, 14 );
  }
  torsion{
    members( 12, 13, 14, 15 );
  }
  torsion{
    members( 13, 14, 15, 16 );
  }
}

molecule{
  
  name = "twoChain_14G";
  

  atom[0]{
    type = "HEAD";
    position( -0.110050, 1.249033, -0.023976 );
    orientation( 0.0, 0.0, 0.0 );
  }
  atom[1]{
    type = "CH2";
    position( 0.784436, -1.064213, -1.211953 );
  }
  atom[2]{
    type = "CH";
    position( 1.109791, -0.911911, -2.709467 );
  }
  atom[3]{
    type = "CH2";
    position( -0.268917, -0.607952, -3.324586 );
  }
  atom[4]{
    type = "CH2";
    position( -0.331805, 0.044474, -4.718138 );
  }
  atom[5]{
    type = "CH2";
    position( -0.103214, -0.867134, -5.938104 );
  }
  atom[6]{
    type = "CH2";
    position( -0.181619, -0.100307, -7.271307 );
  }
  atom[7]{
    type = "CH2";
    position( 0.042505, -0.939979, -8.542653 );
  }
  atom[8]{
    type = "CH2";
    position( -0.051368, -0.117766, -9.841404 );
  }
  atom[9]{
    type = "CH2";
    position( 0.142860, -0.925076, -11.138372 );
  }
  atom[10]{
    type = "CH2";
    position( 0.019593, -0.083625, -12.422259 );
  }
  atom[11]{
    type = "CH2";
    position( 0.180051, -0.885777, -13.727022 );
  }
  atom[12]{
    type = "CH2";
    position( 0.034763, -0.043486, -15.008052 );
  }
  atom[13]{
    type = "CH2";
    position( 0.173235, -0.851987, -16.311414);
  }
  atom[14]{
    type = "CH2";
    position( 0.018726, -0.013912, -17.594129);
  }
  atom[15]{
    type = "CH2";
    position( 0.148780, -0.828559, -18.894528 );
  }
  atom[16]{
    type = "CH3";
    position( -0.005954, 0.007456, -20.178559 );
  }
  atom[17]{
    type = "CH2";
    position( 2.634030, -1.130837, -2.728703);
  }
  atom[18]{
    type = "CH2";
    position( 3.297380, -1.543544, -4.055820 );
  }
  atom[19]{
    type = "CH2";
    position( 3.457273, -0.451637, -5.129958 );
  }
  atom[20]{
    type = "CH2";
    position( 4.094249, -1.019043, -6.412110 );
  }
  atom[21]{
    type = "CH2";
    position( 4.235779, -0.046073, -7.597395 );
  }
  atom[22]{
    type = "CH2";
    position( 4.820154, -0.745979, -8.838458 );
  }
  atom[23]{
    type = "CH2";
    position( 4.932879, 0.124112, -10.104093 );
  }
  atom[24]{
    type = "CH2";
    position( 5.429202, -0.669482, -11.326988 );
  }
  atom[25]{
    type = "CH2";
    position( 5.471807, 0.135950, -12.638881 );
  }
  atom[26]{
    type = "CH2";
    position( 5.843335, -0.710717, -13.870434 );
  }
  atom[27]{
    type = "CH2";
    position( 5.795449, 0.066888, -15.198830 );
  }
  atom[28]{
    type = "CH2";
    position( 6.056385, -0.801301, -16.443724 );
  }
  atom[29]{
    type = "CH2";
    position( 5.952060, -0.029856, -17.772479 );
  }
  atom[30]{
    type = "CH3";
    position( 6.164077, -0.903155, -19.023077 );
  }

  

  bond{
    members( 0, 1 );
  }
  bond{
    members( 1, 2 );
  }
  bond{
    members( 2, 3 );
  }
  bond{
    members( 3, 4 );
  }
  bond{
    members( 4, 5 );
  }
  bond{
    members( 5, 6 );
  }
  bond{
    members( 6, 7 );
  }
  bond{
    members( 7, 8 );
  }
  bond{
    members( 8, 9 );
  }
  bond{
    members( 9, 10 );
  }
  bond{
    members( 10, 11 );
  }
  bond{
    members( 11, 12 );
  }
  bond{
    members( 12, 13 );
  }
  bond{
    members( 13, 14 );
  }
  bond{
    members( 14, 15 );
  }
  bond{
    members( 15, 16 );
  }
  bond{
    members( 2, 17 );
  }
  bond{
    members( 17, 18 );
  }
  bond{
    members( 18, 19 );
  }
  bond{
    members( 19, 20 );
  }
  bond{
    members( 20, 21 );
  }
  bond{
    members( 21, 22 );
  }
  bond{
    members( 22, 23 );
  }
  bond{
    members( 23, 24 );
  }
  bond{
    members( 24, 25 );
  }
  bond{
    members( 25, 26 );
  }
  bond{
    members( 26, 27 );
  }
  bond{
    members( 27, 28 );
  }
  bond{
    members( 28, 29 );
  }
  bond{
    members( 29, 30 );
  }

  

  bend{
    members( 0, 1, 2 );
  }
  bend{
    members( 1, 2, 3 );
  }
  bend{
    members( 2, 3, 4 );
  }
  bend{
    members( 3, 4, 5 );
  }
  bend{
    members( 4, 5, 6 );
  }
  bend{
    members( 5, 6, 7 );
  }
  bend{
    members( 6, 7, 8 );
  }
  bend{
    members( 7, 8, 9 );
  }
  bend{
    members( 8, 9, 10 );
  }
  bend{
    members( 9, 10, 11 );
  }
  bend{
    members( 10, 11, 12 );
  }
  bend{
    members( 11, 12, 13 );
  }
  bend{
    members( 12, 13, 14 );
  }
  bend{
    members( 13, 14, 15 );
  }
  bend{
    members( 14, 15, 16 );
  }
  bend{
    members( 0, 1 );
    ghostVectorSource = 0;
  }
  bend{
    members( 1, 2, 17 );
  }
  bend{
    members( 2, 17, 18 );
  }
  bend{
    members( 17, 18, 19 );
  }
  bend{
    members( 18, 19, 20 );
  }
  bend{
    members( 19, 20, 21 );
  }
  bend{
    members( 20, 21, 22 );
  }
  bend{
    members( 21, 22, 23 );
  }
  bend{
    members( 22, 23, 24 );
  }
  bend{
    members( 23, 24, 25 );
  }
  bend{
    members( 24, 25, 26 );
  }
  bend{
    members( 25, 26, 27 );
  }
  bend{
    members( 26, 27, 28 );
  }
  bend{
    members( 27, 28, 29 );
  }
  bend{
    members( 28, 29, 30 );
  }




  

  torsion{
    members( 0, 1, 2, 3 );
  }
  torsion{
    members( 1, 2, 3, 4 );
  }
  torsion{
    members( 2, 3, 4, 5 );
  }
  torsion{
    members( 3, 4, 5, 6 );
  }
  torsion{
    members( 4, 5, 6, 7 );
  }
  torsion{
    members( 5, 6, 7, 8 );
  }
  torsion{
    members( 6, 7, 8, 9 );
  }
  torsion{
    members( 7, 8, 9, 10 );
  }
  torsion{
    members( 8, 9, 10, 11 );
  }
  torsion{
    members( 9, 10, 11, 12 );
  }
  torsion{
    members( 10, 11, 12, 13 );
  }
  torsion{
    members( 11, 12, 13, 14 );
  }
  torsion{
    members( 12, 13, 14, 15 );
  }
  torsion{
    members( 13, 14, 15, 16 );
  }
  torsion{
    members( 1, 2, 17, 18 );
  }
  torsion{
    members( 2, 17, 18, 19 );
  }
  torsion{
    members( 17, 18, 19, 20 );
  }
  torsion{
    members( 18, 19, 20, 21 );
  }
  torsion{
    members( 19, 20, 21, 22 );
  }
  torsion{
    members( 20, 21, 22, 23 );
  }
  torsion{
    members( 21, 22, 23, 24 );
  }
  torsion{
    members( 22, 23, 24, 25 );
  }
  torsion{
    members( 23, 24, 25, 26 );
  }
  torsion{
    members( 24, 25, 26, 27 );
  }
  torsion{
    members( 25, 26, 27, 28 );
  }
  torsion{
    members( 26, 27, 28, 29 );
  }
  torsion{
    members( 27, 28, 29, 30 );
  }

}
#endif
