/* HydroCmd.h */

/* File autogenerated by gengetopt version 2.11  */

#ifndef HYDROCMD_H
#define HYDROCMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "Hydro"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * input_arg;	/* input dump file.  */
  char * output_arg;	/* output file prefix (default='hydro').  */
  double viscosity_arg;	/* viscosity of solvent.  */
  double temperature_arg;	/* temperature of the system.  */
  double sigma_arg;	/* diameter of beads(use with rough shell model).  */
  char * model_arg;	/* hydrodynamics model (support RoughShell and BeadModel).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int input_given ;	/* Whether input was given.  */
  int output_given ;	/* Whether output was given.  */
  int viscosity_given ;	/* Whether viscosity was given.  */
  int temperature_given ;	/* Whether temperature was given.  */
  int sigma_given ;	/* Whether sigma was given.  */
  int model_given ;	/* Whether model was given.  */

} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* HYDROCMD_H */
