Package = applications/hydrodynamics

Source    = \
        HydrodynamicsModel.cpp\
        StuntDoubleShape.cpp \
	HydrodynamicsModelFactory.cpp \
	RoughShell.cpp \
	BeadModel.cpp \
	HydroCmd.c \
	Hydro.cpp

BuiltParallelExe = 0 
RmiSource =

Main      = Hydro 

DEV_ROOT=../../..

include $(DEV_ROOT)/make/Makefile

