Package = applications/hydrodynamics

Source    = \
            AnalyticalModel.cpp \
            ApproximationModel.cpp \
            BeadModel.cpp \
            HydrodynamicsModel.cpp \
            RoughShell.cpp \
            CompositeShape.cpp \
            Hydro.cpp \
            HydroCmd.c \
            ShapeBuilder.cpp \
            HydrodynamicsModelFactory.cpp 

BuiltParallelExe = 0 
RmiSource =

Main      = Hydro 

ScriptFiles =  \
        diffExplainer

DEV_ROOT=../../..

include $(DEV_ROOT)/make/Makefile

