Package = applications/velocitizer

Source    = \
	velocitizerCmd.c \
	velocitizer.cpp \
	
BuiltParallelExe = 0

RmiSource =

Main      = velocitizer

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

