/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --no-handle-error --include-getopt --show-required --unamed-opts --file-name=DynamicPropsCmd --c-extension=cpp --header-extension=hpp

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif


#include "DynamicPropsCmd.hpp"

const char *gengetopt_args_info_purpose = "Computes a variety of time correlation functions from the\nconfigurations stored in a dump file. Typical examples of time\ncorrelation functions are the mean square displacement and the\nvelocity autocorrelation functions. The selection syntax can be used\nto specify the StuntDoubles that will be used for the calculation. A\ngeneral time correlation function can be thought of as:\n\n           C(t) =  < A(0) * B(t) >\n\nwhere A(t) and B(t) are time-dependent properties, and the < >\nindicates an average over the initial time and atoms (if A and B are\nproperties of atoms).\n\nExample:\n  DynamicProps -i longRun.dump  --rcorr --sele1=\"select SPCE_RB_0\"";

const char *gengetopt_args_info_usage = "Usage: DynamicProps [OPTION]... [FILE]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=filename          input dump file (mandatory)",
  "  -o, --output=filename         output file name",
  "      --sele1=selection script  select first stuntdouble set",
  "      --sele2=selection script  select second stuntdouble set (if sele2 is not\n                                  set, use script from sele1)",
  "      --order=INT               Lengendre Polynomial Order",
  "  -z, --nzbins=INT              Number of Z bins  (default=`100')",
  "  -c, --rcut=DOUBLE             cutoff radius (angstroms)",
  "      --OOcut=DOUBLE            Oxygen-Oxygen cutoff radius (angstroms)\n                                  (default=`3.5')",
  "      --thetacut=DOUBLE         HOO cutoff angle (degrees)  (default=`30')",
  "      --OHcut=DOUBLE            Oxygen-Hydrogen cutoff radius (angstroms)\n                                  (default=`2.45')",
  "      --privilegedAxis=ENUM     which axis is special for spatial analysis\n                                  (default = z axis)  (possible values=\"x\",\n                                  \"y\", \"z\" default=`z')",
  "      --dipoleX=DOUBLE          X-component of the dipole with respect to body\n                                  frame  (default=`0.0')",
  "      --dipoleY=DOUBLE          Y-component of the dipole with respect to body\n                                  frame  (default=`0.0')",
  "      --dipoleZ=DOUBLE          Z-component of the dipole with respect to body\n                                  frame  (default=`-1.0')",
  "\n Group: correlation function\n   an option of this group is required",
  "  -s, --selecorr                selection correlation function",
  "  -r, --rcorr                   mean squared displacement",
  "      --rcorrZ                  mean squared displacement binned by Z",
  "  -v, --vcorr                   velocity correlation function",
  "      --vcorrZ                  velocity correlation function along z-axis",
  "      --vcorrR                  velocity correlation function projected radially",
  "      --vaOutProdcorr           Velocity - Velocity auto outer product correlation\n                                  function",
  "      --waOutProdcorr           Angular Velocity - Angular Velocity auto outer product correlation\n                                  function",
  "      --vwOutProdcorr           Velocity - Angular Velocity outer product correlation\n                                  function",
  "      --wvOutProdcorr           Angular Velocity - Velocity outer product correlation\n                                  function",
  "  -w, --wcorr                   charge velocity correlation function",
  "  -d, --dcorr                   dipole correlation function",
  "  -l, --lcorr                   Lengendre correlation function",
  "      --lcorrZ                  Lengendre correlation function binned by Z",
  "      --cohZ                    Lengendre correlation function for OH bond\n                                  vectors binned by Z",
  "  -M, --sdcorr                  System dipole correlation function",
  "      --r_rcorr                 Radial msd",
  "      --thetacorr               Angular msd [Cos(theta)]",
  "      --drcorr                  Directional msd for particles with unit vectors",
  "      --stresscorr              Stress tensor correlation function",
  "  -b, --bondcorr                Bond extension correlation function",
  "  -f, --freqfluccorr            Frequency Fluctuation correlation function",
  "  -j, --jumptime                Hydrogen bond jump time correlation function",
  "      --jumptimeZ               Hydrogen bond jump time correlation function\n                                  binned by Z",
  "      --persistence             Hydrogen bond persistence correlation function",
  "      --pjcorr                  Momentum - Angular Momentum cross correlation\n                                  function",
  "      --ftcorr                  Force - Torque cross correlation function",
  "      --ckcorr                  Charge - Kinetic energy cross correlation\n                                  function",
  "      --cscorr                  Charge - Orientation order parameter\n                                  [Cos(theta)] cross correlation function",
  "      --facorr                  Force - Force auto correlation function",
  "      --tfcorr                  Torque - Force Cross correlation function",
  "      --tacorr                  Torque auto correlation function",
  "      --disp                    Displacement correlation function",
  "      --dispZ                   Displacement correlation function binned by Z",
  "      --current                 Current density auto correlation function",
  "      --ddisp                   Collective Dipole displacement function\n                                  (Helfand moment of Current Density)",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_privilegedAxis_values[] = {"x", "y", "z", 0}; /*< Possible values for privilegedAxis. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->sele1_given = 0 ;
  args_info->sele2_given = 0 ;
  args_info->order_given = 0 ;
  args_info->nzbins_given = 0 ;
  args_info->rcut_given = 0 ;
  args_info->OOcut_given = 0 ;
  args_info->thetacut_given = 0 ;
  args_info->OHcut_given = 0 ;
  args_info->privilegedAxis_given = 0 ;
  args_info->dipoleX_given = 0 ;
  args_info->dipoleY_given = 0 ;
  args_info->dipoleZ_given = 0 ;
  args_info->selecorr_given = 0 ;
  args_info->rcorr_given = 0 ;
  args_info->rcorrZ_given = 0 ;
  args_info->vcorr_given = 0 ;
  args_info->vcorrZ_given = 0 ;
  args_info->vcorrR_given = 0 ;
  args_info->wcorr_given = 0 ;
  args_info->dcorr_given = 0 ;
  args_info->lcorr_given = 0 ;
  args_info->lcorrZ_given = 0 ;
  args_info->cohZ_given = 0 ;
  args_info->sdcorr_given = 0 ;
  args_info->r_rcorr_given = 0 ;
  args_info->thetacorr_given = 0 ;
  args_info->drcorr_given = 0 ;
  args_info->stresscorr_given = 0 ;
  args_info->bondcorr_given = 0 ;
  args_info->freqfluccorr_given = 0 ;
  args_info->jumptime_given = 0 ;
  args_info->jumptimeZ_given = 0 ;
  args_info->persistence_given = 0 ;
  args_info->pjcorr_given = 0 ;
  args_info->ftcorr_given = 0 ;
  args_info->ckcorr_given = 0 ;
  args_info->cscorr_given = 0 ;
  args_info->facorr_given = 0 ;
  args_info->tfcorr_given = 0 ;
  args_info->tacorr_given = 0 ;
  args_info->disp_given = 0 ;
  args_info->dispZ_given = 0 ;
  args_info->current_given = 0 ;
  args_info->ddisp_given = 0 ;
  args_info->vaOutProdcorr_given = 0 ;
  args_info->waOutProdcorr_given = 0 ;
  args_info->vwOutProdcorr_given = 0 ;
  args_info->wvOutProdcorr_given = 0 ;
  args_info->correlation_function_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->sele1_arg = NULL;
  args_info->sele1_orig = NULL;
  args_info->sele2_arg = NULL;
  args_info->sele2_orig = NULL;
  args_info->order_orig = NULL;
  args_info->nzbins_arg = 100;
  args_info->nzbins_orig = NULL;
  args_info->rcut_orig = NULL;
  args_info->OOcut_arg = 3.5;
  args_info->OOcut_orig = NULL;
  args_info->thetacut_arg = 30;
  args_info->thetacut_orig = NULL;
  args_info->OHcut_arg = 2.45;
  args_info->OHcut_orig = NULL;
  args_info->privilegedAxis_arg = privilegedAxis_arg_z;
  args_info->privilegedAxis_orig = NULL;
  args_info->dipoleX_arg = 0.0;
  args_info->dipoleX_orig = NULL;
  args_info->dipoleY_arg = 0.0;
  args_info->dipoleY_orig = NULL;
  args_info->dipoleZ_arg = -1.0;
  args_info->dipoleZ_orig = NULL;

}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->output_help = gengetopt_args_info_help[3] ;
  args_info->sele1_help = gengetopt_args_info_help[4] ;
  args_info->sele2_help = gengetopt_args_info_help[5] ;
  args_info->order_help = gengetopt_args_info_help[6] ;
  args_info->nzbins_help = gengetopt_args_info_help[7] ;
  args_info->rcut_help = gengetopt_args_info_help[8] ;
  args_info->OOcut_help = gengetopt_args_info_help[9] ;
  args_info->thetacut_help = gengetopt_args_info_help[10] ;
  args_info->OHcut_help = gengetopt_args_info_help[11] ;
  args_info->privilegedAxis_help = gengetopt_args_info_help[12] ;
  args_info->dipoleX_help = gengetopt_args_info_help[13] ;
  args_info->dipoleY_help = gengetopt_args_info_help[14] ;
  args_info->dipoleZ_help = gengetopt_args_info_help[15] ;
  args_info->selecorr_help = gengetopt_args_info_help[17] ;
  args_info->rcorr_help = gengetopt_args_info_help[18] ;
  args_info->rcorrZ_help = gengetopt_args_info_help[19] ;
  args_info->vcorr_help = gengetopt_args_info_help[20] ;
  args_info->vcorrZ_help = gengetopt_args_info_help[21] ;
  args_info->vcorrR_help = gengetopt_args_info_help[22] ;
  args_info->vaOutProdcorr_help = gengetopt_args_info_help[23] ;
  args_info->waOutProdcorr_help = gengetopt_args_info_help[24] ;
  args_info->vwOutProdcorr_help = gengetopt_args_info_help[25] ;
  args_info->wvOutProdcorr_help = gengetopt_args_info_help[26] ;
  args_info->wcorr_help = gengetopt_args_info_help[27] ;
  args_info->dcorr_help = gengetopt_args_info_help[28] ;
  args_info->lcorr_help = gengetopt_args_info_help[29] ;
  args_info->lcorrZ_help = gengetopt_args_info_help[30] ;
  args_info->cohZ_help = gengetopt_args_info_help[31] ;
  args_info->sdcorr_help = gengetopt_args_info_help[32] ;
  args_info->r_rcorr_help = gengetopt_args_info_help[33] ;
  args_info->thetacorr_help = gengetopt_args_info_help[34] ;
  args_info->drcorr_help = gengetopt_args_info_help[35] ;
  args_info->stresscorr_help = gengetopt_args_info_help[36] ;
  args_info->bondcorr_help = gengetopt_args_info_help[37] ;
  args_info->freqfluccorr_help = gengetopt_args_info_help[38] ;
  args_info->jumptime_help = gengetopt_args_info_help[39] ;
  args_info->jumptimeZ_help = gengetopt_args_info_help[40] ;
  args_info->persistence_help = gengetopt_args_info_help[41] ;
  args_info->pjcorr_help = gengetopt_args_info_help[42] ;
  args_info->ftcorr_help = gengetopt_args_info_help[43] ;
  args_info->ckcorr_help = gengetopt_args_info_help[44] ;
  args_info->cscorr_help = gengetopt_args_info_help[45] ;
  args_info->facorr_help = gengetopt_args_info_help[46] ;
  args_info->tfcorr_help = gengetopt_args_info_help[47] ;
  args_info->tacorr_help = gengetopt_args_info_help[48] ;
  args_info->disp_help = gengetopt_args_info_help[49] ;
  args_info->dispZ_help = gengetopt_args_info_help[50] ;
  args_info->current_help = gengetopt_args_info_help[51] ;
  args_info->ddisp_help = gengetopt_args_info_help[52] ;

}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    {
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params =
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->sele1_arg));
  free_string_field (&(args_info->sele1_orig));
  free_string_field (&(args_info->sele2_arg));
  free_string_field (&(args_info->sele2_orig));
  free_string_field (&(args_info->order_orig));
  free_string_field (&(args_info->nzbins_orig));
  free_string_field (&(args_info->rcut_orig));
  free_string_field (&(args_info->OOcut_orig));
  free_string_field (&(args_info->thetacut_orig));
  free_string_field (&(args_info->OHcut_orig));
  free_string_field (&(args_info->privilegedAxis_orig));
  free_string_field (&(args_info->dipoleX_orig));
  free_string_field (&(args_info->dipoleY_orig));
  free_string_field (&(args_info->dipoleZ_orig));


  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->sele1_given)
    write_into_file(outfile, "sele1", args_info->sele1_orig, 0);
  if (args_info->sele2_given)
    write_into_file(outfile, "sele2", args_info->sele2_orig, 0);
  if (args_info->order_given)
    write_into_file(outfile, "order", args_info->order_orig, 0);
  if (args_info->nzbins_given)
    write_into_file(outfile, "nzbins", args_info->nzbins_orig, 0);
  if (args_info->rcut_given)
    write_into_file(outfile, "rcut", args_info->rcut_orig, 0);
  if (args_info->OOcut_given)
    write_into_file(outfile, "OOcut", args_info->OOcut_orig, 0);
  if (args_info->thetacut_given)
    write_into_file(outfile, "thetacut", args_info->thetacut_orig, 0);
  if (args_info->OHcut_given)
    write_into_file(outfile, "OHcut", args_info->OHcut_orig, 0);
  if (args_info->privilegedAxis_given)
    write_into_file(outfile, "privilegedAxis", args_info->privilegedAxis_orig, cmdline_parser_privilegedAxis_values);
  if (args_info->dipoleX_given)
    write_into_file(outfile, "dipoleX", args_info->dipoleX_orig, 0);
  if (args_info->dipoleY_given)
    write_into_file(outfile, "dipoleY", args_info->dipoleY_orig, 0);
  if (args_info->dipoleZ_given)
    write_into_file(outfile, "dipoleZ", args_info->dipoleZ_orig, 0);
  if (args_info->selecorr_given)
    write_into_file(outfile, "selecorr", 0, 0 );
  if (args_info->rcorr_given)
    write_into_file(outfile, "rcorr", 0, 0 );
  if (args_info->rcorrZ_given)
    write_into_file(outfile, "rcorrZ", 0, 0 );
  if (args_info->vcorr_given)
    write_into_file(outfile, "vcorr", 0, 0 );
  if (args_info->vcorrZ_given)
    write_into_file(outfile, "vcorrZ", 0, 0 );
  if (args_info->vcorrR_given)
    write_into_file(outfile, "vcorrR", 0, 0 );
  if (args_info->wcorr_given)
    write_into_file(outfile, "wcorr", 0, 0 );
  if (args_info->dcorr_given)
    write_into_file(outfile, "dcorr", 0, 0 );
  if (args_info->lcorr_given)
    write_into_file(outfile, "lcorr", 0, 0 );
  if (args_info->lcorrZ_given)
    write_into_file(outfile, "lcorrZ", 0, 0 );
  if (args_info->cohZ_given)
    write_into_file(outfile, "cohZ", 0, 0 );
  if (args_info->sdcorr_given)
    write_into_file(outfile, "sdcorr", 0, 0 );
  if (args_info->r_rcorr_given)
    write_into_file(outfile, "r_rcorr", 0, 0 );
  if (args_info->thetacorr_given)
    write_into_file(outfile, "thetacorr", 0, 0 );
  if (args_info->drcorr_given)
    write_into_file(outfile, "drcorr", 0, 0 );
  if (args_info->stresscorr_given)
    write_into_file(outfile, "stresscorr", 0, 0 );
  if (args_info->bondcorr_given)
    write_into_file(outfile, "bondcorr", 0, 0 );
  if (args_info->freqfluccorr_given)
    write_into_file(outfile, "freqfluccorr", 0, 0 );
  if (args_info->jumptime_given)
    write_into_file(outfile, "jumptime", 0, 0 );
  if (args_info->jumptimeZ_given)
    write_into_file(outfile, "jumptimeZ", 0, 0 );
  if (args_info->persistence_given)
    write_into_file(outfile, "persistence", 0, 0 );
  if (args_info->pjcorr_given)
    write_into_file(outfile, "pjcorr", 0, 0 );
  if (args_info->ftcorr_given)
    write_into_file(outfile, "ftcorr", 0, 0 );
  if (args_info->ckcorr_given)
    write_into_file(outfile, "ckcorr", 0, 0 );
  if (args_info->cscorr_given)
    write_into_file(outfile, "cscorr", 0, 0 );
  if (args_info->facorr_given)
    write_into_file(outfile, "facorr", 0, 0 );
  if (args_info->tfcorr_given)
    write_into_file(outfile, "tfcorr", 0, 0 );
  if (args_info->tacorr_given)
    write_into_file(outfile, "tacorr", 0, 0 );
  if (args_info->disp_given)
    write_into_file(outfile, "disp", 0, 0 );
  if (args_info->dispZ_given)
    write_into_file(outfile, "dispZ", 0, 0 );
  if (args_info->current_given)
    write_into_file(outfile, "current", 0, 0 );
  if (args_info->ddisp_given)
    write_into_file(outfile, "ddisp", 0, 0 );
  if (args_info->vaOutProdcorr_given)
    write_into_file(outfile, "vaOutProdcorr", 0, 0 );
  if (args_info->waOutProdcorr_given)
    write_into_file(outfile, "waOutProdcorr", 0, 0 );
  if (args_info->vwOutProdcorr_given)
    write_into_file(outfile, "vwOutProdcorr", 0, 0 );
  if (args_info->wvOutProdcorr_given)
    write_into_file(outfile, "wvOutProdcorr", 0, 0 );


  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_correlation_function(struct gengetopt_args_info *args_info)
{
  if (! args_info->correlation_function_group_counter)
    return;

  args_info->selecorr_given = 0 ;
  args_info->rcorr_given = 0 ;
  args_info->rcorrZ_given = 0 ;
  args_info->vcorr_given = 0 ;
  args_info->vcorrZ_given = 0 ;
  args_info->vcorrR_given = 0 ;
  args_info->wcorr_given = 0 ;
  args_info->dcorr_given = 0 ;
  args_info->lcorr_given = 0 ;
  args_info->lcorrZ_given = 0 ;
  args_info->cohZ_given = 0 ;
  args_info->sdcorr_given = 0 ;
  args_info->r_rcorr_given = 0 ;
  args_info->thetacorr_given = 0 ;
  args_info->drcorr_given = 0 ;
  args_info->stresscorr_given = 0 ;
  args_info->bondcorr_given = 0 ;
  args_info->freqfluccorr_given = 0 ;
  args_info->jumptime_given = 0 ;
  args_info->jumptimeZ_given = 0 ;
  args_info->persistence_given = 0 ;
  args_info->pjcorr_given = 0 ;
  args_info->ftcorr_given = 0 ;
  args_info->ckcorr_given = 0 ;
  args_info->cscorr_given = 0 ;
  args_info->facorr_given = 0 ;
  args_info->tfcorr_given = 0 ;
  args_info->tacorr_given = 0 ;
  args_info->disp_given = 0 ;
  args_info->dispZ_given = 0 ;
  args_info->current_given = 0 ;
  args_info->ddisp_given = 0 ;
  args_info->vaOutProdcorr_given = 0 ;
  args_info->waOutProdcorr_given = 0 ;
  args_info->vwOutProdcorr_given = 0 ;
  args_info->wvOutProdcorr_given = 0 ;

  args_info->correlation_function_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }

  if (args_info->correlation_function_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group correlation function were given. One is required%s.\n", prog_name, args_info->correlation_function_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }


  /* checks for dependences among options */

  return error_occurred;
}

/*
 * Extracted from the glibc source tree, version 2.3.6
 *
 * Licensed under the GPL as per the whole glibc source tree.
 *
 * This file was modified so that getopt_long can be called
 * many times without risking previous memory to be spoiled.
 *
 * Modified by Andre Noll and Lorenzo Bettini for use in
 * GNU gengetopt generated files.
 *
 */

/*
 * we must include anything we need since this file is not thought to be
 * inserted in a file already using getopt.h
 *
 * Lorenzo
 */

struct option
{
  const char *name;
  /* has_arg can't be an enum because some compilers complain about
     type mismatches in all the code that assumes it is an int.  */
  int has_arg;
  int *flag;
  int val;
};

/* This version of `getopt' appears to the caller like standard Unix `getopt'
   but it behaves differently for the user, since it allows the user
   to intersperse the options with the other arguments.

   As `getopt' works, it permutes the elements of ARGV so that,
   when it is done, all the options precede everything else.  Thus
   all application programs are extended to handle flexible argument order.
*/
/*
   If the field `flag' is not NULL, it points to a variable that is set
   to the value given in the field `val' when the option is found, but
   left unchanged if the option is not found.

   To have a long-named option do something other than set an `int' to
   a compiled-in constant, such as set a value from `custom_optarg', set the
   option's `flag' field to zero and its `val' field to a nonzero
   value (the equivalent single-letter option character, if there is
   one).  For long options that have a zero `flag' field, `getopt'
   returns the contents of the `val' field.  */

/* Names for the values of the `has_arg' field of `struct option'.  */
#ifndef no_argument
#define no_argument		0
#endif

#ifndef required_argument
#define required_argument	1
#endif

#ifndef optional_argument
#define optional_argument	2
#endif

struct custom_getopt_data {
	/*
	 * These have exactly the same meaning as the corresponding global variables,
	 * except that they are used for the reentrant versions of getopt.
	 */
	int custom_optind;
	int custom_opterr;
	int custom_optopt;
	char *custom_optarg;

	/* True if the internal members have been initialized.  */
	int initialized;

	/*
	 * The next char to be scanned in the option-element in which the last option
	 * character we returned was found.  This allows us to pick up the scan where
	 * we left off.  If this is zero, or a null string, it means resume the scan by
	 * advancing to the next ARGV-element.
	 */
	char *nextchar;

	/*
	 * Describe the part of ARGV that contains non-options that have been skipped.
	 * `first_nonopt' is the index in ARGV of the first of them; `last_nonopt' is
	 * the index after the last of them.
	 */
	int first_nonopt;
	int last_nonopt;
};

/*
 * the variables optarg, optind, opterr and optopt are renamed with
 * the custom_ prefix so that they don't interfere with getopt ones.
 *
 * Moreover they're static so they are visible only from within the
 * file where this very file will be included.
 */

/*
 * For communication from `custom_getopt' to the caller.  When `custom_getopt' finds an
 * option that takes an argument, the argument value is returned here.
 */
static char *custom_optarg;

/*
 * Index in ARGV of the next element to be scanned.  This is used for
 * communication to and from the caller and for communication between
 * successive calls to `custom_getopt'.
 *
 * On entry to `custom_getopt', 1 means this is the first call; initialize.
 *
 * When `custom_getopt' returns -1, this is the index of the first of the non-option
 * elements that the caller should itself scan.
 *
 * Otherwise, `custom_optind' communicates from one call to the next how much of ARGV
 * has been scanned so far.
 *
 * 1003.2 says this must be 1 before any call.
 */
static int custom_optind = 1;

/*
 * Callers store zero here to inhibit the error message for unrecognized
 * options.
 */
static int custom_opterr = 1;

/*
 * Set to an option character which was unrecognized.  This must be initialized
 * on some systems to avoid linking in the system's own getopt implementation.
 */
static int custom_optopt = '?';

/*
 * Exchange two adjacent subsequences of ARGV.  One subsequence is elements
 * [first_nonopt,last_nonopt) which contains all the non-options that have been
 * skipped so far.  The other is elements [last_nonopt,custom_optind), which contains
 * all the options processed since those non-options were skipped.
 * `first_nonopt' and `last_nonopt' are relocated so that they describe the new
 * indices of the non-options in ARGV after they are moved.
 */
static void exchange(char **argv, struct custom_getopt_data *d)
{
	int bottom = d->first_nonopt;
	int middle = d->last_nonopt;
	int top = d->custom_optind;
	char *tem;

	/*
	 * Exchange the shorter segment with the far end of the longer segment.
	 * That puts the shorter segment into the right place.  It leaves the
	 * longer segment in the right place overall, but it consists of two
	 * parts that need to be swapped next.
	 */
	while (top > middle && middle > bottom) {
		if (top - middle > middle - bottom) {
			/* Bottom segment is the short one.  */
			int len = middle - bottom;
			int i;

			/* Swap it with the top part of the top segment.  */
			for (i = 0; i < len; i++) {
				tem = argv[bottom + i];
				argv[bottom + i] =
					argv[top - (middle - bottom) + i];
				argv[top - (middle - bottom) + i] = tem;
			}
			/* Exclude the moved bottom segment from further swapping.  */
			top -= len;
		} else {
			/* Top segment is the short one.  */
			int len = top - middle;
			int i;

			/* Swap it with the bottom part of the bottom segment.  */
			for (i = 0; i < len; i++) {
				tem = argv[bottom + i];
				argv[bottom + i] = argv[middle + i];
				argv[middle + i] = tem;
			}
			/* Exclude the moved top segment from further swapping.  */
			bottom += len;
		}
	}
	/* Update records for the slots the non-options now occupy.  */
	d->first_nonopt += (d->custom_optind - d->last_nonopt);
	d->last_nonopt = d->custom_optind;
}

/* Initialize the internal data when the first call is made.  */
static void custom_getopt_initialize(struct custom_getopt_data *d)
{
	/*
	 * Start processing options with ARGV-element 1 (since ARGV-element 0
	 * is the program name); the sequence of previously skipped non-option
	 * ARGV-elements is empty.
	 */
	d->first_nonopt = d->last_nonopt = d->custom_optind;
	d->nextchar = NULL;
	d->initialized = 1;
}

#define NONOPTION_P (argv[d->custom_optind][0] != '-' || argv[d->custom_optind][1] == '\0')

/* return: zero: continue, nonzero: return given value to user */
static int shuffle_argv(int argc, char *const *argv,const struct option *longopts,
	struct custom_getopt_data *d)
{
	/*
	 * Give FIRST_NONOPT & LAST_NONOPT rational values if CUSTOM_OPTIND has been
	 * moved back by the user (who may also have changed the arguments).
	 */
	if (d->last_nonopt > d->custom_optind)
		d->last_nonopt = d->custom_optind;
	if (d->first_nonopt > d->custom_optind)
		d->first_nonopt = d->custom_optind;
	/*
	 * If we have just processed some options following some
	 * non-options, exchange them so that the options come first.
	 */
	if (d->first_nonopt != d->last_nonopt &&
			d->last_nonopt != d->custom_optind)
		exchange((char **) argv, d);
	else if (d->last_nonopt != d->custom_optind)
		d->first_nonopt = d->custom_optind;
	/*
	 * Skip any additional non-options and extend the range of
	 * non-options previously skipped.
	 */
	while (d->custom_optind < argc && NONOPTION_P)
		d->custom_optind++;
	d->last_nonopt = d->custom_optind;
	/*
	 * The special ARGV-element `--' means premature end of options.  Skip
	 * it like a null option, then exchange with previous non-options as if
	 * it were an option, then skip everything else like a non-option.
	 */
	if (d->custom_optind != argc && !strcmp(argv[d->custom_optind], "--")) {
		d->custom_optind++;
		if (d->first_nonopt != d->last_nonopt
				&& d->last_nonopt != d->custom_optind)
			exchange((char **) argv, d);
		else if (d->first_nonopt == d->last_nonopt)
			d->first_nonopt = d->custom_optind;
		d->last_nonopt = argc;
		d->custom_optind = argc;
	}
	/*
	 * If we have done all the ARGV-elements, stop the scan and back over
	 * any non-options that we skipped and permuted.
	 */
	if (d->custom_optind == argc) {
		/*
		 * Set the next-arg-index to point at the non-options that we
		 * previously skipped, so the caller will digest them.
		 */
		if (d->first_nonopt != d->last_nonopt)
			d->custom_optind = d->first_nonopt;
		return -1;
	}
	/*
	 * If we have come to a non-option and did not permute it, either stop
	 * the scan or describe it to the caller and pass it by.
	 */
	if (NONOPTION_P) {
		d->custom_optarg = argv[d->custom_optind++];
		return 1;
	}
	/*
	 * We have found another option-ARGV-element. Skip the initial
	 * punctuation.
	 */
	d->nextchar = (argv[d->custom_optind] + 1 + (longopts != NULL && argv[d->custom_optind][1] == '-'));
	return 0;
}

/*
 * Check whether the ARGV-element is a long option.
 *
 * If there's a long option "fubar" and the ARGV-element is "-fu", consider
 * that an abbreviation of the long option, just like "--fu", and not "-f" with
 * arg "u".
 *
 * This distinction seems to be the most useful approach.
 *
 */
static int check_long_opt(int argc, char *const *argv, const char *optstring,
		const struct option *longopts, int *longind,
		int print_errors, struct custom_getopt_data *d)
{
	char *nameend;
	const struct option *p;
	const struct option *pfound = NULL;
	int exact = 0;
	int ambig = 0;
	int indfound = -1;
	int option_index;

	for (nameend = d->nextchar; *nameend && *nameend != '='; nameend++)
		/* Do nothing.  */ ;

	/* Test all long options for either exact match or abbreviated matches */
	for (p = longopts, option_index = 0; p->name; p++, option_index++)
		if (!strncmp(p->name, d->nextchar, nameend - d->nextchar)) {
			if ((unsigned int) (nameend - d->nextchar)
					== (unsigned int) strlen(p->name)) {
				/* Exact match found.  */
				pfound = p;
				indfound = option_index;
				exact = 1;
				break;
			} else if (pfound == NULL) {
				/* First nonexact match found.  */
				pfound = p;
				indfound = option_index;
			} else if (pfound->has_arg != p->has_arg
					|| pfound->flag != p->flag
					|| pfound->val != p->val)
				/* Second or later nonexact match found.  */
				ambig = 1;
		}
	if (ambig && !exact) {
		if (print_errors) {
			fprintf(stderr,
				"%s: option `%s' is ambiguous\n",
				argv[0], argv[d->custom_optind]);
		}
		d->nextchar += strlen(d->nextchar);
		d->custom_optind++;
		d->custom_optopt = 0;
		return '?';
	}
	if (pfound) {
		option_index = indfound;
		d->custom_optind++;
		if (*nameend) {
			if (pfound->has_arg != no_argument)
				d->custom_optarg = nameend + 1;
			else {
				if (print_errors) {
					if (argv[d->custom_optind - 1][1] == '-') {
						/* --option */
						fprintf(stderr, "%s: option `--%s' doesn't allow an argument\n",
							argv[0], pfound->name);
					} else {
						/* +option or -option */
						fprintf(stderr, "%s: option `%c%s' doesn't allow an argument\n",
							argv[0], argv[d->custom_optind - 1][0], pfound->name);
					}

				}
				d->nextchar += strlen(d->nextchar);
				d->custom_optopt = pfound->val;
				return '?';
			}
		} else if (pfound->has_arg == required_argument) {
			if (d->custom_optind < argc)
				d->custom_optarg = argv[d->custom_optind++];
			else {
				if (print_errors) {
					fprintf(stderr,
						"%s: option `%s' requires an argument\n",
						argv[0],
						argv[d->custom_optind - 1]);
				}
				d->nextchar += strlen(d->nextchar);
				d->custom_optopt = pfound->val;
				return optstring[0] == ':' ? ':' : '?';
			}
		}
		d->nextchar += strlen(d->nextchar);
		if (longind != NULL)
			*longind = option_index;
		if (pfound->flag) {
			*(pfound->flag) = pfound->val;
			return 0;
		}
		return pfound->val;
	}
	/*
	 * Can't find it as a long option.  If this is not getopt_long_only, or
	 * the option starts with '--' or is not a valid short option, then
	 * it's an error.  Otherwise interpret it as a short option.
	 */
	if (print_errors) {
		if (argv[d->custom_optind][1] == '-') {
			/* --option */
			fprintf(stderr,
				"%s: unrecognized option `--%s'\n",
				argv[0], d->nextchar);
		} else {
			/* +option or -option */
			fprintf(stderr,
				"%s: unrecognized option `%c%s'\n",
				argv[0], argv[d->custom_optind][0],
				d->nextchar);
		}
	}
	d->nextchar = (char *) "";
	d->custom_optind++;
	d->custom_optopt = 0;
	return '?';
}

static int check_short_opt(int argc, char *const *argv, const char *optstring,
		int print_errors, struct custom_getopt_data *d)
{
	char c = *d->nextchar++;
	const char *temp = strchr(optstring, c);

	/* Increment `custom_optind' when we start to process its last character.  */
	if (*d->nextchar == '\0')
		++d->custom_optind;
	if (!temp || c == ':') {
		if (print_errors)
			fprintf(stderr, "%s: invalid option -- %c\n", argv[0], c);

		d->custom_optopt = c;
		return '?';
	}
	if (temp[1] == ':') {
		if (temp[2] == ':') {
			/* This is an option that accepts an argument optionally.  */
			if (*d->nextchar != '\0') {
				d->custom_optarg = d->nextchar;
				d->custom_optind++;
			} else
				d->custom_optarg = NULL;
			d->nextchar = NULL;
		} else {
			/* This is an option that requires an argument.  */
			if (*d->nextchar != '\0') {
				d->custom_optarg = d->nextchar;
				/*
				 * If we end this ARGV-element by taking the
				 * rest as an arg, we must advance to the next
				 * element now.
				 */
				d->custom_optind++;
			} else if (d->custom_optind == argc) {
				if (print_errors) {
					fprintf(stderr,
						"%s: option requires an argument -- %c\n",
						argv[0], c);
				}
				d->custom_optopt = c;
				if (optstring[0] == ':')
					c = ':';
				else
					c = '?';
			} else
				/*
				 * We already incremented `custom_optind' once;
				 * increment it again when taking next ARGV-elt
				 * as argument.
				 */
				d->custom_optarg = argv[d->custom_optind++];
			d->nextchar = NULL;
		}
	}
	return c;
}

/*
 * Scan elements of ARGV for option characters given in OPTSTRING.
 *
 * If an element of ARGV starts with '-', and is not exactly "-" or "--",
 * then it is an option element.  The characters of this element
 * (aside from the initial '-') are option characters.  If `getopt'
 * is called repeatedly, it returns successively each of the option characters
 * from each of the option elements.
 *
 * If `getopt' finds another option character, it returns that character,
 * updating `custom_optind' and `nextchar' so that the next call to `getopt' can
 * resume the scan with the following option character or ARGV-element.
 *
 * If there are no more option characters, `getopt' returns -1.
 * Then `custom_optind' is the index in ARGV of the first ARGV-element
 * that is not an option.  (The ARGV-elements have been permuted
 * so that those that are not options now come last.)
 *
 * OPTSTRING is a string containing the legitimate option characters.
 * If an option character is seen that is not listed in OPTSTRING,
 * return '?' after printing an error message.  If you set `custom_opterr' to
 * zero, the error message is suppressed but we still return '?'.
 *
 * If a char in OPTSTRING is followed by a colon, that means it wants an arg,
 * so the following text in the same ARGV-element, or the text of the following
 * ARGV-element, is returned in `custom_optarg'.  Two colons mean an option that
 * wants an optional arg; if there is text in the current ARGV-element,
 * it is returned in `custom_optarg', otherwise `custom_optarg' is set to zero.
 *
 * If OPTSTRING starts with `-' or `+', it requests different methods of
 * handling the non-option ARGV-elements.
 * See the comments about RETURN_IN_ORDER and REQUIRE_ORDER, above.
 *
 * Long-named options begin with `--' instead of `-'.
 * Their names may be abbreviated as long as the abbreviation is unique
 * or is an exact match for some defined option.  If they have an
 * argument, it follows the option name in the same ARGV-element, separated
 * from the option name by a `=', or else the in next ARGV-element.
 * When `getopt' finds a long-named option, it returns 0 if that option's
 * `flag' field is nonzero, the value of the option's `val' field
 * if the `flag' field is zero.
 *
 * The elements of ARGV aren't really const, because we permute them.
 * But we pretend they're const in the prototype to be compatible
 * with other systems.
 *
 * LONGOPTS is a vector of `struct option' terminated by an
 * element containing a name which is zero.
 *
 * LONGIND returns the index in LONGOPT of the long-named option found.
 * It is only valid when a long-named option has been found by the most
 * recent call.
 *
 * Return the option character from OPTS just read.  Return -1 when there are
 * no more options.  For unrecognized options, or options missing arguments,
 * `custom_optopt' is set to the option letter, and '?' is returned.
 *
 * The OPTS string is a list of characters which are recognized option letters,
 * optionally followed by colons, specifying that that letter takes an
 * argument, to be placed in `custom_optarg'.
 *
 * If a letter in OPTS is followed by two colons, its argument is optional.
 * This behavior is specific to the GNU `getopt'.
 *
 * The argument `--' causes premature termination of argument scanning,
 * explicitly telling `getopt' that there are no more options.  If OPTS begins
 * with `--', then non-option arguments are treated as arguments to the option
 * '\0'.  This behavior is specific to the GNU `getopt'.
 */

static int getopt_internal_r(int argc, char *const *argv, const char *optstring,
		const struct option *longopts, int *longind,
		struct custom_getopt_data *d)
{
	int ret, print_errors = d->custom_opterr;

	if (optstring[0] == ':')
		print_errors = 0;
	if (argc < 1)
		return -1;
	d->custom_optarg = NULL;

	/*
	 * This is a big difference with GNU getopt, since optind == 0
	 * means initialization while here 1 means first call.
	 */
	if (d->custom_optind == 0 || !d->initialized) {
		if (d->custom_optind == 0)
			d->custom_optind = 1;	/* Don't scan ARGV[0], the program name.  */
		custom_getopt_initialize(d);
	}
	if (d->nextchar == NULL || *d->nextchar == '\0') {
		ret = shuffle_argv(argc, argv, longopts, d);
		if (ret)
			return ret;
	}
	if (longopts && (argv[d->custom_optind][1] == '-' ))
		return check_long_opt(argc, argv, optstring, longopts,
			longind, print_errors, d);
	return check_short_opt(argc, argv, optstring, print_errors, d);
}

static int custom_getopt_internal(int argc, char *const *argv, const char *optstring,
	const struct option *longopts, int *longind)
{
	int result;
	/* Keep a global copy of all internal members of d */
	static struct custom_getopt_data d;

	d.custom_optind = custom_optind;
	d.custom_opterr = custom_opterr;
	result = getopt_internal_r(argc, argv, optstring, longopts,
		longind, &d);
	custom_optind = d.custom_optind;
	custom_optarg = d.custom_optarg;
	custom_optopt = d.custom_optopt;
	return result;
}

static int custom_getopt_long (int argc, char *const *argv, const char *options,
	const struct option *long_options, int *opt_index)
{
	return custom_getopt_internal(argc, argv, options, long_options,
		opt_index);
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given,
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n",
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n",
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n",
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n",
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;

  int override;
  int initialize;
  int check_required;
  int check_ambiguity;

  char *optarg;
  int optind;
  int opterr;
  int optopt;

  package_name = argv[0];

  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "sele1",	1, NULL, 0 },
        { "sele2",	1, NULL, 0 },
        { "order",	1, NULL, 0 },
        { "nzbins",	1, NULL, 'z' },
        { "rcut",	1, NULL, 'c' },
        { "OOcut",	1, NULL, 0 },
        { "thetacut",	1, NULL, 0 },
        { "OHcut",	1, NULL, 0 },
        { "privilegedAxis",	1, NULL, 0 },
        { "dipoleX",	1, NULL, 0 },
        { "dipoleY",	1, NULL, 0 },
        { "dipoleZ",	1, NULL, 0 },
        { "selecorr",	0, NULL, 's' },
        { "rcorr",	0, NULL, 'r' },
        { "rcorrZ",	0, NULL, 0 },
        { "vcorr",	0, NULL, 'v' },
        { "vcorrZ",	0, NULL, 0 },
        { "vcorrR",	0, NULL, 0 },
        { "wcorr",	0, NULL, 'w' },
        { "dcorr",	0, NULL, 'd' },
        { "lcorr",	0, NULL, 'l' },
        { "lcorrZ",	0, NULL, 0 },
        { "cohZ",	0, NULL, 0 },
        { "sdcorr",	0, NULL, 'M' },
        { "r_rcorr",	0, NULL, 0 },
        { "thetacorr",	0, NULL, 0 },
        { "drcorr",	0, NULL, 0 },
        { "stresscorr",	0, NULL, 0 },
        { "bondcorr",	0, NULL, 'b' },
        { "freqfluccorr",	0, NULL, 'f' },
        { "jumptime",	0, NULL, 'j' },
        { "jumptimeZ",	0, NULL, 0 },
        { "persistence",	0, NULL, 0 },
        { "pjcorr",	0, NULL, 0 },
        { "ftcorr",	0, NULL, 0 },
        { "ckcorr",	0, NULL, 0 },
        { "cscorr",	0, NULL, 0 },
        { "facorr",	0, NULL, 0 },
        { "tfcorr",	0, NULL, 0 },
        { "tacorr",	0, NULL, 0 },
        { "disp",	0, NULL, 0 },
        { "dispZ",	0, NULL, 0 },
        { "current",	0, NULL, 0 },
        { "ddisp",	0, NULL, 0 },
        { "vaOutProdcorr",	0, NULL, 0 },
        { "waOutProdcorr",	0, NULL, 0 },
        { "vwOutProdcorr",	0, NULL, 0 },
        { "wvOutProdcorr",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      custom_optarg = optarg;
      custom_optind = optind;
      custom_opterr = opterr;
      custom_optopt = optopt;

      c = custom_getopt_long (argc, argv, "hVi:o:z:c:srvwdlMbfj", long_options, &option_index);

      optarg = custom_optarg;
      optind = custom_optind;
      opterr = custom_opterr;
      optopt = custom_optopt;

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* input dump file.  */


          if (update_arg( (void *)&(args_info->input_arg),
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;

          break;
        case 'o':	/* output file name.  */


          if (update_arg( (void *)&(args_info->output_arg),
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;

          break;
        case 'z':	/* Number of Z bins.  */


          if (update_arg( (void *)&(args_info->nzbins_arg),
               &(args_info->nzbins_orig), &(args_info->nzbins_given),
              &(local_args_info.nzbins_given), optarg, 0, "100", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nzbins", 'z',
              additional_error))
            goto failure;

          break;
        case 'c':	/* cutoff radius (angstroms).  */


          if (update_arg( (void *)&(args_info->rcut_arg),
               &(args_info->rcut_orig), &(args_info->rcut_given),
              &(local_args_info.rcut_given), optarg, 0, 0, ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "rcut", 'c',
              additional_error))
            goto failure;

          break;
        case 's':	/* selection correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->selecorr_given),
              &(local_args_info.selecorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "selecorr", 's',
              additional_error))
            goto failure;

          break;
        case 'r':	/* mean squared displacement.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->rcorr_given),
              &(local_args_info.rcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "rcorr", 'r',
              additional_error))
            goto failure;

          break;
        case 'v':	/* velocity correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->vcorr_given),
              &(local_args_info.vcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "vcorr", 'v',
              additional_error))
            goto failure;

          break;
        case 'w':	/* charge velocity correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->wcorr_given),
              &(local_args_info.wcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "wcorr", 'w',
              additional_error))
            goto failure;

          break;
        case 'd':	/* dipole correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->dcorr_given),
              &(local_args_info.dcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "dcorr", 'd',
              additional_error))
            goto failure;

          break;
        case 'l':	/* Lengendre correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->lcorr_given),
              &(local_args_info.lcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "lcorr", 'l',
              additional_error))
            goto failure;

          break;
        case 'M':	/* System dipole correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->sdcorr_given),
              &(local_args_info.sdcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "sdcorr", 'M',
              additional_error))
            goto failure;

          break;
        case 'b':	/* Bond extension correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->bondcorr_given),
              &(local_args_info.bondcorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "bondcorr", 'b',
              additional_error))
            goto failure;

          break;
        case 'f':	/* Frequency Fluctuation correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->freqfluccorr_given),
              &(local_args_info.freqfluccorr_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "freqfluccorr", 'f',
              additional_error))
            goto failure;

          break;
        case 'j':	/* Hydrogen bond jump time correlation function.  */

          if (args_info->correlation_function_group_counter && override)
            reset_group_correlation_function (args_info);
          args_info->correlation_function_group_counter += 1;

          if (update_arg( 0 ,
               0 , &(args_info->jumptime_given),
              &(local_args_info.jumptime_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "jumptime", 'j',
              additional_error))
            goto failure;

          break;

        case 0:	/* Long option with no short option */
          /* select first stuntdouble set.  */
          if (strcmp (long_options[option_index].name, "sele1") == 0)
          {


            if (update_arg( (void *)&(args_info->sele1_arg),
                 &(args_info->sele1_orig), &(args_info->sele1_given),
                &(local_args_info.sele1_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "sele1", '-',
                additional_error))
              goto failure;

          }
          /* select second stuntdouble set (if sele2 is not set, use script from sele1).  */
          else if (strcmp (long_options[option_index].name, "sele2") == 0)
          {


            if (update_arg( (void *)&(args_info->sele2_arg),
                 &(args_info->sele2_orig), &(args_info->sele2_given),
                &(local_args_info.sele2_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "sele2", '-',
                additional_error))
              goto failure;

          }
          /* Lengendre Polynomial Order.  */
          else if (strcmp (long_options[option_index].name, "order") == 0)
          {


            if (update_arg( (void *)&(args_info->order_arg),
                 &(args_info->order_orig), &(args_info->order_given),
                &(local_args_info.order_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "order", '-',
                additional_error))
              goto failure;

          }
          /* Oxygen-Oxygen cutoff radius (angstroms).  */
          else if (strcmp (long_options[option_index].name, "OOcut") == 0)
          {


            if (update_arg( (void *)&(args_info->OOcut_arg),
                 &(args_info->OOcut_orig), &(args_info->OOcut_given),
                &(local_args_info.OOcut_given), optarg, 0, "3.5", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "OOcut", '-',
                additional_error))
              goto failure;

          }
          /* HOO cutoff angle (degrees).  */
          else if (strcmp (long_options[option_index].name, "thetacut") == 0)
          {


            if (update_arg( (void *)&(args_info->thetacut_arg),
                 &(args_info->thetacut_orig), &(args_info->thetacut_given),
                &(local_args_info.thetacut_given), optarg, 0, "30", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "thetacut", '-',
                additional_error))
              goto failure;

          }
          /* Oxygen-Hydrogen cutoff radius (angstroms).  */
          else if (strcmp (long_options[option_index].name, "OHcut") == 0)
          {


            if (update_arg( (void *)&(args_info->OHcut_arg),
                 &(args_info->OHcut_orig), &(args_info->OHcut_given),
                &(local_args_info.OHcut_given), optarg, 0, "2.45", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "OHcut", '-',
                additional_error))
              goto failure;

          }
          /* which axis is special for spatial analysis (default = z axis).  */
          else if (strcmp (long_options[option_index].name, "privilegedAxis") == 0)
          {


            if (update_arg( (void *)&(args_info->privilegedAxis_arg),
                 &(args_info->privilegedAxis_orig), &(args_info->privilegedAxis_given),
                &(local_args_info.privilegedAxis_given), optarg, cmdline_parser_privilegedAxis_values, "z", ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "privilegedAxis", '-',
                additional_error))
              goto failure;

          }
          /* X-component of the dipole with respect to body frame.  */
          else if (strcmp (long_options[option_index].name, "dipoleX") == 0)
          {


            if (update_arg( (void *)&(args_info->dipoleX_arg),
                 &(args_info->dipoleX_orig), &(args_info->dipoleX_given),
                &(local_args_info.dipoleX_given), optarg, 0, "0.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "dipoleX", '-',
                additional_error))
              goto failure;

          }
          /* Y-component of the dipole with respect to body frame.  */
          else if (strcmp (long_options[option_index].name, "dipoleY") == 0)
          {


            if (update_arg( (void *)&(args_info->dipoleY_arg),
                 &(args_info->dipoleY_orig), &(args_info->dipoleY_given),
                &(local_args_info.dipoleY_given), optarg, 0, "0.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "dipoleY", '-',
                additional_error))
              goto failure;

          }
          /* Z-component of the dipole with respect to body frame.  */
          else if (strcmp (long_options[option_index].name, "dipoleZ") == 0)
          {


            if (update_arg( (void *)&(args_info->dipoleZ_arg),
                 &(args_info->dipoleZ_orig), &(args_info->dipoleZ_given),
                &(local_args_info.dipoleZ_given), optarg, 0, "-1.0", ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "dipoleZ", '-',
                additional_error))
              goto failure;

          }
          /* mean squared displacement binned by Z.  */
          else if (strcmp (long_options[option_index].name, "rcorrZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->rcorrZ_given),
                &(local_args_info.rcorrZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "rcorrZ", '-',
                additional_error))
              goto failure;

          }
          /* velocity correlation function along z-axis.  */
          else if (strcmp (long_options[option_index].name, "vcorrZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->vcorrZ_given),
                &(local_args_info.vcorrZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "vcorrZ", '-',
                additional_error))
              goto failure;

          }
          /* velocity correlation function projected radially.  */
          else if (strcmp (long_options[option_index].name, "vcorrR") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->vcorrR_given),
                &(local_args_info.vcorrR_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "vcorrR", '-',
                additional_error))
              goto failure;

          }
          /* Lengendre correlation function binned by Z.  */
          else if (strcmp (long_options[option_index].name, "lcorrZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->lcorrZ_given),
                &(local_args_info.lcorrZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "lcorrZ", '-',
                additional_error))
              goto failure;

          }
          /* Lengendre correlation function for OH bond vectors binned by Z.  */
          else if (strcmp (long_options[option_index].name, "cohZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->cohZ_given),
                &(local_args_info.cohZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "cohZ", '-',
                additional_error))
              goto failure;

          }
          /* Radial msd.  */
          else if (strcmp (long_options[option_index].name, "r_rcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->r_rcorr_given),
                &(local_args_info.r_rcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "r_rcorr", '-',
                additional_error))
              goto failure;

          }
          /* Angular msd.  */
          else if (strcmp (long_options[option_index].name, "thetacorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->thetacorr_given),
                &(local_args_info.thetacorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "thetacorr", '-',
                additional_error))
              goto failure;

          }
          /* Directional msd for particles with unit vectors.  */
          else if (strcmp (long_options[option_index].name, "drcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->drcorr_given),
                &(local_args_info.drcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "drcorr", '-',
                additional_error))
              goto failure;

          }
          /* Stress tensor correlation function.  */
          else if (strcmp (long_options[option_index].name, "stresscorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->stresscorr_given),
                &(local_args_info.stresscorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "stresscorr", '-',
                additional_error))
              goto failure;

          }
          /* Hydrogen bond jump time correlation function binned by Z.  */
          else if (strcmp (long_options[option_index].name, "jumptimeZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->jumptimeZ_given),
                &(local_args_info.jumptimeZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "jumptimeZ", '-',
                additional_error))
              goto failure;

          }
          /* Hydrogen bond persistence correlation function.  */
          else if (strcmp (long_options[option_index].name, "persistence") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->persistence_given),
                &(local_args_info.persistence_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "persistence", '-',
                additional_error))
              goto failure;

          }
          /* Momentum - Angular Momentum cross correlation function.  */
          else if (strcmp (long_options[option_index].name, "pjcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->pjcorr_given),
                &(local_args_info.pjcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "pjcorr", '-',
                additional_error))
              goto failure;

          }
          /* Force - Torque cross correlation function.  */
          else if (strcmp (long_options[option_index].name, "ftcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->ftcorr_given),
                &(local_args_info.ftcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ftcorr", '-',
                additional_error))
              goto failure;

          }
          /* Charge - Kinetic energy cross correlation function.  */
          else if (strcmp (long_options[option_index].name, "ckcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->ckcorr_given),
                &(local_args_info.ckcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ckcorr", '-',
                additional_error))
              goto failure;

          }
          /* Charge - Orientation order parameter (Cos\theta) cross correlation function.  */
          else if (strcmp (long_options[option_index].name, "cscorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->cscorr_given),
                &(local_args_info.cscorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "cscorr", '-',
                additional_error))
              goto failure;

          }
          /* Force - Force auto correlation function.  */
          else if (strcmp (long_options[option_index].name, "facorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->facorr_given),
                &(local_args_info.facorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "facorr", '-',
                additional_error))
              goto failure;

          }
          /* Torque - Force Cross correlation function.  */
          else if (strcmp (long_options[option_index].name, "tfcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->tfcorr_given),
                &(local_args_info.tfcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "tfcorr", '-',
                additional_error))
              goto failure;

          }
          /* Torque auto correlation function.  */
          else if (strcmp (long_options[option_index].name, "tacorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->tacorr_given),
                &(local_args_info.tacorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "tacorr", '-',
                additional_error))
              goto failure;

          }
          /* Displacement correlation function.  */
          else if (strcmp (long_options[option_index].name, "disp") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->disp_given),
                &(local_args_info.disp_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "disp", '-',
                additional_error))
              goto failure;

          }
          /* Displacement correlation function binned by Z.  */
          else if (strcmp (long_options[option_index].name, "dispZ") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->dispZ_given),
                &(local_args_info.dispZ_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "dispZ", '-',
                additional_error))
              goto failure;

          }
          /* Current density auto correlation function.  */
          else if (strcmp (long_options[option_index].name, "current") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->current_given),
                &(local_args_info.current_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "current", '-',
                additional_error))
              goto failure;

          }
          /* Collective Dipole displacement function (Helfand moment of Current Density).  */
          else if (strcmp (long_options[option_index].name, "ddisp") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->ddisp_given),
                &(local_args_info.ddisp_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "ddisp", '-',
                additional_error))
              goto failure;

          }
          /* Velocity - Velocity auto outer product correlation function.  */
          else if (strcmp (long_options[option_index].name, "vaOutProdcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->vaOutProdcorr_given),
                &(local_args_info.vaOutProdcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "vaOutProdcorr", '-',
                additional_error))
              goto failure;

          }
          /* Angular Velocity - Angular Velocity auto outer product correlation function.  */
          else if (strcmp (long_options[option_index].name, "waOutProdcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->waOutProdcorr_given),
                &(local_args_info.waOutProdcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "waOutProdcorr", '-',
                additional_error))
              goto failure;

          }
          /* Velocity - Angular Velocity outer product correlation function.  */
          else if (strcmp (long_options[option_index].name, "vwOutProdcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->vwOutProdcorr_given),
                &(local_args_info.vwOutProdcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "vwOutProdcorr", '-',
                additional_error))
              goto failure;

          }
          /* Angular Velocity - Velocity outer product correlation function.  */
          else if (strcmp (long_options[option_index].name, "wvOutProdcorr") == 0)
          {

            if (args_info->correlation_function_group_counter && override)
              reset_group_correlation_function (args_info);
            args_info->correlation_function_group_counter += 1;

            if (update_arg( 0 ,
                 0 , &(args_info->wvOutProdcorr_given),
                &(local_args_info.wvOutProdcorr_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "wvOutProdcorr", '-',
                additional_error))
              goto failure;

          }

          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->correlation_function_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group correlation function were given. One is required%s.\n", argv[0], args_info->correlation_function_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */


      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:

  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
