/*
  File autogenerated by gengetopt version 2.19.1
  generated with the following command:
  gengetopt -F DynamicPropsCmd 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "DynamicPropsCmd.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: DynamicProps [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=filename          input dump file",
  "  -o, --output=filename         output file name",
  "      --sele1=selection script  select first stuntdouble set",
  "      --sele2=selection script  select second stuntdouble set (if sele2 is not \n                                  set, use script from sele1)",
  "      --order=INT               Lengendre Polynomial Order",
  "\n Group: dynamicProps\n   an option of this group is required",
  "  -r, --rcorr                   rmsd",
  "  -v, --vcorr                   velocity correlation function",
  "  -d, --dcorr                   dipole correlation function",
  "  -l, --lcorr                   Lengendre correlation function",
  "      --r_rcorr                 Radial rmsd",
  "      --thetacorr               Angular rmsd",
  "      --drcorr                  Directional rmsd for particles with unit \n                                  vectors",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->sele1_given = 0 ;
  args_info->sele2_given = 0 ;
  args_info->order_given = 0 ;
  args_info->rcorr_given = 0 ;
  args_info->vcorr_given = 0 ;
  args_info->dcorr_given = 0 ;
  args_info->lcorr_given = 0 ;
  args_info->r_rcorr_given = 0 ;
  args_info->thetacorr_given = 0 ;
  args_info->drcorr_given = 0 ;
  args_info->dynamicProps_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->sele1_arg = NULL;
  args_info->sele1_orig = NULL;
  args_info->sele2_arg = NULL;
  args_info->sele2_orig = NULL;
  args_info->order_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->output_help = gengetopt_args_info_help[3] ;
  args_info->sele1_help = gengetopt_args_info_help[4] ;
  args_info->sele2_help = gengetopt_args_info_help[5] ;
  args_info->order_help = gengetopt_args_info_help[6] ;
  args_info->rcorr_help = gengetopt_args_info_help[7] ;
  args_info->vcorr_help = gengetopt_args_info_help[8] ;
  args_info->dcorr_help = gengetopt_args_info_help[9] ;
  args_info->lcorr_help = gengetopt_args_info_help[10] ;
  args_info->r_rcorr_help = gengetopt_args_info_help[11] ;
  args_info->thetacorr_help = gengetopt_args_info_help[12] ;
  args_info->drcorr_help = gengetopt_args_info_help[13] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->input_arg)
    {
      free (args_info->input_arg); /* free previous argument */
      args_info->input_arg = 0;
    }
  if (args_info->input_orig)
    {
      free (args_info->input_orig); /* free previous argument */
      args_info->input_orig = 0;
    }
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->output_orig)
    {
      free (args_info->output_orig); /* free previous argument */
      args_info->output_orig = 0;
    }
  if (args_info->sele1_arg)
    {
      free (args_info->sele1_arg); /* free previous argument */
      args_info->sele1_arg = 0;
    }
  if (args_info->sele1_orig)
    {
      free (args_info->sele1_orig); /* free previous argument */
      args_info->sele1_orig = 0;
    }
  if (args_info->sele2_arg)
    {
      free (args_info->sele2_arg); /* free previous argument */
      args_info->sele2_arg = 0;
    }
  if (args_info->sele2_orig)
    {
      free (args_info->sele2_orig); /* free previous argument */
      args_info->sele2_orig = 0;
    }
  if (args_info->order_orig)
    {
      free (args_info->order_orig); /* free previous argument */
      args_info->order_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->input_given) {
    if (args_info->input_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "input", args_info->input_orig);
    } else {
      fprintf(outfile, "%s\n", "input");
    }
  }
  if (args_info->output_given) {
    if (args_info->output_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "output", args_info->output_orig);
    } else {
      fprintf(outfile, "%s\n", "output");
    }
  }
  if (args_info->sele1_given) {
    if (args_info->sele1_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "sele1", args_info->sele1_orig);
    } else {
      fprintf(outfile, "%s\n", "sele1");
    }
  }
  if (args_info->sele2_given) {
    if (args_info->sele2_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "sele2", args_info->sele2_orig);
    } else {
      fprintf(outfile, "%s\n", "sele2");
    }
  }
  if (args_info->order_given) {
    if (args_info->order_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "order", args_info->order_orig);
    } else {
      fprintf(outfile, "%s\n", "order");
    }
  }
  if (args_info->rcorr_given) {
    fprintf(outfile, "%s\n", "rcorr");
  }
  if (args_info->vcorr_given) {
    fprintf(outfile, "%s\n", "vcorr");
  }
  if (args_info->dcorr_given) {
    fprintf(outfile, "%s\n", "dcorr");
  }
  if (args_info->lcorr_given) {
    fprintf(outfile, "%s\n", "lcorr");
  }
  if (args_info->r_rcorr_given) {
    fprintf(outfile, "%s\n", "r_rcorr");
  }
  if (args_info->thetacorr_given) {
    fprintf(outfile, "%s\n", "thetacorr");
  }
  if (args_info->drcorr_given) {
    fprintf(outfile, "%s\n", "drcorr");
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_dynamicProps(struct gengetopt_args_info *args_info);

static void
reset_group_dynamicProps(struct gengetopt_args_info *args_info)
{
  if (! args_info->dynamicProps_group_counter)
    return;
  
  args_info->rcorr_given = 0 ;
  args_info->vcorr_given = 0 ;
  args_info->dcorr_given = 0 ;
  args_info->lcorr_given = 0 ;
  args_info->r_rcorr_given = 0 ;
  args_info->thetacorr_given = 0 ;
  args_info->drcorr_given = 0 ;

  args_info->dynamicProps_group_counter = 0;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (args_info->dynamicProps_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group dynamicProps were given. One is required.%s\n", prog_name, args_info->dynamicProps_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  

  /* checks for dependences among options */

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "sele1",	1, NULL, 0 },
        { "sele2",	1, NULL, 0 },
        { "order",	1, NULL, 0 },
        { "rcorr",	0, NULL, 'r' },
        { "vcorr",	0, NULL, 'v' },
        { "dcorr",	0, NULL, 'd' },
        { "lcorr",	0, NULL, 'l' },
        { "r_rcorr",	0, NULL, 0 },
        { "thetacorr",	0, NULL, 0 },
        { "drcorr",	0, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:o:rvdl", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* input dump file.  */
          if (local_args_info.input_given)
            {
              fprintf (stderr, "%s: `--input' (`-i') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->input_given && ! override)
            continue;
          local_args_info.input_given = 1;
          args_info->input_given = 1;
          if (args_info->input_arg)
            free (args_info->input_arg); /* free previous string */
          args_info->input_arg = gengetopt_strdup (optarg);
          if (args_info->input_orig)
            free (args_info->input_orig); /* free previous string */
          args_info->input_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* output file name.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          if (args_info->output_orig)
            free (args_info->output_orig); /* free previous string */
          args_info->output_orig = gengetopt_strdup (optarg);
          break;

        case 'r':	/* rmsd.  */
          if (local_args_info.rcorr_given)
            {
              fprintf (stderr, "%s: `--rcorr' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->rcorr_given && ! override)
            continue;
          local_args_info.rcorr_given = 1;
          args_info->rcorr_given = 1;
          if (args_info->dynamicProps_group_counter && override)
            reset_group_dynamicProps (args_info);
          args_info->dynamicProps_group_counter += 1;
          break;

        case 'v':	/* velocity correlation function.  */
          if (local_args_info.vcorr_given)
            {
              fprintf (stderr, "%s: `--vcorr' (`-v') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->vcorr_given && ! override)
            continue;
          local_args_info.vcorr_given = 1;
          args_info->vcorr_given = 1;
          if (args_info->dynamicProps_group_counter && override)
            reset_group_dynamicProps (args_info);
          args_info->dynamicProps_group_counter += 1;
          break;

        case 'd':	/* dipole correlation function.  */
          if (local_args_info.dcorr_given)
            {
              fprintf (stderr, "%s: `--dcorr' (`-d') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->dcorr_given && ! override)
            continue;
          local_args_info.dcorr_given = 1;
          args_info->dcorr_given = 1;
          if (args_info->dynamicProps_group_counter && override)
            reset_group_dynamicProps (args_info);
          args_info->dynamicProps_group_counter += 1;
          break;

        case 'l':	/* Lengendre correlation function.  */
          if (local_args_info.lcorr_given)
            {
              fprintf (stderr, "%s: `--lcorr' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->lcorr_given && ! override)
            continue;
          local_args_info.lcorr_given = 1;
          args_info->lcorr_given = 1;
          if (args_info->dynamicProps_group_counter && override)
            reset_group_dynamicProps (args_info);
          args_info->dynamicProps_group_counter += 1;
          break;


        case 0:	/* Long option with no short option */
          /* select first stuntdouble set.  */
          if (strcmp (long_options[option_index].name, "sele1") == 0)
          {
            if (local_args_info.sele1_given)
              {
                fprintf (stderr, "%s: `--sele1' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->sele1_given && ! override)
              continue;
            local_args_info.sele1_given = 1;
            args_info->sele1_given = 1;
            if (args_info->sele1_arg)
              free (args_info->sele1_arg); /* free previous string */
            args_info->sele1_arg = gengetopt_strdup (optarg);
            if (args_info->sele1_orig)
              free (args_info->sele1_orig); /* free previous string */
            args_info->sele1_orig = gengetopt_strdup (optarg);
          }
          /* select second stuntdouble set (if sele2 is not set, use script from sele1).  */
          else if (strcmp (long_options[option_index].name, "sele2") == 0)
          {
            if (local_args_info.sele2_given)
              {
                fprintf (stderr, "%s: `--sele2' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->sele2_given && ! override)
              continue;
            local_args_info.sele2_given = 1;
            args_info->sele2_given = 1;
            if (args_info->sele2_arg)
              free (args_info->sele2_arg); /* free previous string */
            args_info->sele2_arg = gengetopt_strdup (optarg);
            if (args_info->sele2_orig)
              free (args_info->sele2_orig); /* free previous string */
            args_info->sele2_orig = gengetopt_strdup (optarg);
          }
          /* Lengendre Polynomial Order.  */
          else if (strcmp (long_options[option_index].name, "order") == 0)
          {
            if (local_args_info.order_given)
              {
                fprintf (stderr, "%s: `--order' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->order_given && ! override)
              continue;
            local_args_info.order_given = 1;
            args_info->order_given = 1;
            args_info->order_arg = strtol (optarg, &stop_char, 0);
            if (!(stop_char && *stop_char == '\0')) {
              fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
              goto failure;
            }
            if (args_info->order_orig)
              free (args_info->order_orig); /* free previous string */
            args_info->order_orig = gengetopt_strdup (optarg);
          }
          /* Radial rmsd.  */
          else if (strcmp (long_options[option_index].name, "r_rcorr") == 0)
          {
            if (local_args_info.r_rcorr_given)
              {
                fprintf (stderr, "%s: `--r_rcorr' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->r_rcorr_given && ! override)
              continue;
            local_args_info.r_rcorr_given = 1;
            args_info->r_rcorr_given = 1;
            if (args_info->dynamicProps_group_counter && override)
              reset_group_dynamicProps (args_info);
            args_info->dynamicProps_group_counter += 1;
            break;
          }
          /* Angular rmsd.  */
          else if (strcmp (long_options[option_index].name, "thetacorr") == 0)
          {
            if (local_args_info.thetacorr_given)
              {
                fprintf (stderr, "%s: `--thetacorr' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->thetacorr_given && ! override)
              continue;
            local_args_info.thetacorr_given = 1;
            args_info->thetacorr_given = 1;
            if (args_info->dynamicProps_group_counter && override)
              reset_group_dynamicProps (args_info);
            args_info->dynamicProps_group_counter += 1;
            break;
          }
          /* Directional rmsd for particles with unit vectors.  */
          else if (strcmp (long_options[option_index].name, "drcorr") == 0)
          {
            if (local_args_info.drcorr_given)
              {
                fprintf (stderr, "%s: `--drcorr' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->drcorr_given && ! override)
              continue;
            local_args_info.drcorr_given = 1;
            args_info->drcorr_given = 1;
            if (args_info->dynamicProps_group_counter && override)
              reset_group_dynamicProps (args_info);
            args_info->dynamicProps_group_counter += 1;
            break;
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->dynamicProps_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group dynamicProps were given. One is required.%s\n", argv[0], args_info->dynamicProps_group_counter, (additional_error ? additional_error : ""));
      error = 1;
    }
  


  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
