Package = applications/dynamicProps

Source    = \
            TimeCorrFunc.cpp \
	    CrossTimeCorrFunc.cpp \
	    ParticleTimeCorrFunc.cpp \
	    FrameTimeCorrFunc.cpp \
            DipoleCorrFunc.cpp \
            RCorrFunc.cpp \
            VCorrFunc.cpp \
            DynamicProps.cpp \
            DynamicPropsCmd.c \
            LegendreCorrFunc.cpp \
	    RadialRCorrFunc.cpp \
	    ThetaCorrFunc.cpp \
	    EnergyCorrFunc.cpp \
            DirectionalRCorrFunc.cpp \
            StressCorrFunc.cpp

BuiltParallelExe = 0

RmiSource =

Main      = DynamicProps

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

