Package = mdParser

Source    = \
           FilenameObserver.cpp \
           MDLexer.cpp \
           MDParser.cpp \
           MDTreeParser.cpp 

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

