Package = nonbonded

Source    = LJ.cpp \
	GB.cpp \
	Morse.cpp \
	Sticky.cpp \
	EAM.cpp \
	SC.cpp \
	Electrostatic.cpp \
	InteractionManager.cpp
	
RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

