#ifndef _METALS_INC_
#define _METALS_INC_

molecule{
  name = "Au";
  
  atom[0]{
     type="Au";
     position( 0.0, 0.0, 0.0 );
  }
}
molecule{
  name = "Ag";
  
  atom[0]{
     type="Ag";
     position( 0.0, 0.0, 0.0 );
  }
}
molecule{
  name = "Pt";
  
  atom[0]{
     type="Pt";
     position( 0.0, 0.0, 0.0 );
  }
}

molecule{
  name = "Cu";
  
  atom[0]{
     type="Cu";
     position( 0.0, 0.0, 0.0 );
  }
}

molecule{
  name = "Ni";
  
  atom[0]{
     type="Ni";
     position( 0.0, 0.0, 0.0 );
  }
}

molecule{
  name = "Pd";
  
  atom[0]{
     type="Pd";
     position( 0.0, 0.0, 0.0 );
  }
}
#endif
