Package = applications/nanoRodBuilder

Source    = \
	BaseLattice.cpp \
	GeometryBuilder.cpp \
	Lattice.cpp \
	LatticeCreator.cpp \
	LatticeFactory.cpp \
	MoLocator.cpp \
	nanorodBuilder.cpp \
	nanorodBuilderCmd.c 
	
BuiltParallelExe = 0

RmiSource =

Main      = nanoRodBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

