Package = applications/nanoRodBuilder

Source    = \
	nanorodBuilder.cpp \
	nanorodBuilderCmd.c 
#	GeometryBuilder.cpp 
	
BuiltParallelExe = 0

RmiSource =

Main      = nanoRodBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

