Source    = \

RmiSource =

Main      = 

SampleFiles =  \
             Au_bulk_FBD.md \
             Au_bulk_voter.md \
             Au-Core-Ag-Shell_Nanoparticle.md \
             Au_nanoparticle.md \
             metals.md \
             Au_bulk.in \
             Au-Core-Ag-Shell_Nanoparticle.in \
             Au_nanoparticle.in 


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

