Package = QuickHull

Source    = user.c   \
            global.c \
            stat.c   \
            io.c     \
            geom2.c  \
            poly2.c  \
            merge.c  \
            qhull.c  \
            geom.c   \
            poly.c   \
            qset.c   \
            mem.c
RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

