Package = applications/simpleBuilder

Source    = \
	simpleBuilderCmd.c \
	simpleBuilder.cpp \
	
BuiltParallelExe = 0

RmiSource =

Main      = simpleBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

