Package = applications/simpleBuilder

Source    = \
	BaseLattice.cpp \
	Lattice.cpp \
	LatticeCreator.cpp \
	LatticeFactory.cpp \
	MoLocator.cpp \
	simpleBuilderCmd.c \
	simpleBuilder.cpp \
	
BuiltParallelExe = 0

RmiSource =

Main      = simpleBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

