Source    = \
	BaseLattice.cpp \
	Lattice.cpp \
	LatticeCreator.cpp \
	LatticeFactory.cpp \
	MoLocator.cpp \
	simpleBuilderCmd.c \
	simpleBuilder.cpp \

RmiSource =

Main      = simpleBuilder

include ../../../make/Makefile
