Package = applications/nanoparticleBuilder

Source    = \
	nanoparticleBuilderCmd.c \
	nanoparticleBuilder.cpp \
	shapedLatticeSpherical.cpp
	
BuiltParallelExe = 0

RmiSource =

Main      = nanoparticleBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

