Package = applications/nanoRodBuilder

MySource    = \
	nanorodparticleBuilder.cpp \
	nanoparticleBuilderCmd.c \
	sphericalNanoparticle.cpp

USE_CGAL = no


BuiltParallelExe = 0

RmiSource =

Main      = nanoparticleBuilder

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

