/* nanoparticleBuilderCmd.h */

/* File autogenerated by gengetopt version 2.13  */

#ifndef NANOPARTICLEBUILDERCMD_H
#define NANOPARTICLEBUILDERCMD_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "nanoparticleBuilder"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  char * output_arg;	/* Output file name.  */
  char * latticetype_arg;	/* Lattice type string. Valid types are fcc,hcp,bcc. (default='fcc').  */
  double latticeCnst_arg;	/* Lattice spacing in Angstroms for cubic lattice..  */
  double radius_arg;	/* Nanoparticle radius in Angstroms.  */
  double* ShellRadius_arg;	/* Radius from the center of the particle to start a new shell in multi-component core-shell particle. Specified for each component > 1 in md file..  */
  double* molFraction_arg;	/* (Default) Builds a multi-component random mixed nanoparticle. Mole Fraction must be specified for each componet > 1 in MD file..  */
  double vacancyPCT_arg;	/* Percentage of vacancies to build.  */
  double* vacancyRadius_arg;	/* Radius arround core-shell where vacancies should be located..  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int output_given ;	/* Whether output was given.  */
  int latticetype_given ;	/* Whether latticetype was given.  */
  int latticeCnst_given ;	/* Whether latticeCnst was given.  */
  int radius_given ;	/* Whether radius was given.  */
  unsigned int ShellRadius_given ;	/* Whether ShellRadius was given.  */
  unsigned int molFraction_given ;	/* Whether molFraction was given.  */
  int vacancyPCT_given ;	/* Whether vacancyPCT was given.  */
  unsigned int vacancyRadius_given ;	/* Whether vacancyRadius was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* NANOPARTICLEBUILDERCMD_H */
