/*
  File autogenerated by gengetopt version 2.13.1
  generated with the following command:
  gengetopt -F nanoparticleBuilderCmd --unamed-opts --no-handle-error 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "nanoparticleBuilderCmd.h"

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

struct shellRadius_list
{
  double shellRadius_arg;
  struct shellRadius_list * next;
};

struct molFraction_list
{
  double molFraction_arg;
  struct molFraction_list * next;
};

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->output_given = 0 ;
  args_info->latticeConstant_given = 0 ;
  args_info->radius_given = 0 ;
  args_info->shellRadius_given = 0 ;
  args_info->molFraction_given = 0 ;
  args_info->vacancyPercent_given = 0 ;
  args_info->vacancyInnerRadius_given = 0 ;
  args_info->vacancyOuterRadius_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->output_arg = NULL;
  args_info->shellRadius_arg = NULL;
  args_info->molFraction_arg = NULL;
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n%s\n", "Builds spherical random or core-shell nanoparticles and outputs an OOPSE \nstartup file");
  printf("\nUsage: nanoparticleBuilder [OPTIONS]... [FILES]...\n\n");
  printf("%s\n","  -h, --help                    Print help and exit");
  printf("%s\n","  -V, --version                 Print version and exit");
  printf("%s\n","  -o, --output=STRING           Output file name");
  printf("%s\n","      --latticeConstant=DOUBLE  Lattice spacing in Angstroms for cubic lattice.");
  printf("%s\n","      --radius=DOUBLE           Nanoparticle radius in Angstroms");
  printf("%s\n","      --shellRadius=DOUBLE      Radius containing within it only molecules of a \n                                  specific component. Specified for each \n                                  component > 1 in the template file.");
  printf("%s\n","      --molFraction=DOUBLE      Builds a multi-component random alloy \n                                  nanoparticle. A mole Fraction must be \n                                  specified for each component > 1 in the \n                                  template file.");
  printf("%s\n","      --vacancyPercent=DOUBLE   Percentage of atoms to remove from within \n                                  vacancy range");
  printf("%s\n","      --vacancyInnerRadius=DOUBLE\n                                Radius arround core-shell where vacancies \n                                  should be located.");
  printf("%s\n","      --vacancyOuterRadius=DOUBLE\n                                Radius arround core-shell where vacancies \n                                  should be located.");
  
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);

  args_info->inputs = NULL;
  args_info->inputs_num = 0;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->output_arg)
    {
      free (args_info->output_arg); /* free previous argument */
      args_info->output_arg = 0;
    }
  if (args_info->shellRadius_arg)
    {
      free (args_info->shellRadius_arg); /* free previous argument */
      args_info->shellRadius_arg = 0;
    }
  if (args_info->molFraction_arg)
    {
      free (args_info->molFraction_arg); /* free previous argument */
      args_info->molFraction_arg = 0;
    }
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);
  
  if (args_info->inputs_num)
    free (args_info->inputs);
  
  clear_given (args_info);
}

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  ret = (char *) malloc (len);
  strncpy (ret, arg, len-1);
  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  if (! args_info->output_given)
    {
      fprintf (stderr, "%s: '--output' ('-o') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (! args_info->latticeConstant_given)
    {
      fprintf (stderr, "%s: '--latticeConstant' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (! args_info->radius_given)
    {
      fprintf (stderr, "%s: '--radius' option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  char *multi_token, *multi_next; /* for multiple options */

  int i;        /* Counter */

  struct shellRadius_list * shellRadius_list = NULL,* shellRadius_new = NULL;
  struct molFraction_list * molFraction_list = NULL,* molFraction_new = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "output",	1, NULL, 'o' },
        { "latticeConstant",	1, NULL, 0 },
        { "radius",	1, NULL, 0 },
        { "shellRadius",	1, NULL, 0 },
        { "molFraction",	1, NULL, 0 },
        { "vacancyPercent",	1, NULL, 0 },
        { "vacancyInnerRadius",	1, NULL, 0 },
        { "vacancyOuterRadius",	1, NULL, 0 },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVo:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'o':	/* Output file name.  */
          if (local_args_info.output_given)
            {
              fprintf (stderr, "%s: `--output' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->output_given && ! override)
            continue;
          local_args_info.output_given = 1;
          args_info->output_given = 1;
          if (args_info->output_arg)
            free (args_info->output_arg); /* free previous string */
          args_info->output_arg = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
          /* Lattice spacing in Angstroms for cubic lattice..  */
          if (strcmp (long_options[option_index].name, "latticeConstant") == 0)
          {
            if (local_args_info.latticeConstant_given)
              {
                fprintf (stderr, "%s: `--latticeConstant' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->latticeConstant_given && ! override)
              continue;
            local_args_info.latticeConstant_given = 1;
            args_info->latticeConstant_given = 1;
            args_info->latticeConstant_arg = strtod (optarg, NULL);
          }
          /* Nanoparticle radius in Angstroms.  */
          else if (strcmp (long_options[option_index].name, "radius") == 0)
          {
            if (local_args_info.radius_given)
              {
                fprintf (stderr, "%s: `--radius' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->radius_given && ! override)
              continue;
            local_args_info.radius_given = 1;
            args_info->radius_given = 1;
            args_info->radius_arg = strtod (optarg, NULL);
          }
          /* Radius containing within it only molecules of a specific component. Specified for each component > 1 in the template file..  */
          else if (strcmp (long_options[option_index].name, "shellRadius") == 0)
          {
            local_args_info.shellRadius_given++;
          
            multi_token = get_multiple_arg_token(optarg);
            multi_next = get_multiple_arg_token_next (optarg);
          
            while (1)
              {
                shellRadius_new = (struct shellRadius_list *) malloc (sizeof (struct shellRadius_list));
                shellRadius_new->next = shellRadius_list;
                shellRadius_list = shellRadius_new;
                shellRadius_new->shellRadius_arg = strtod (multi_token, NULL);
                free (multi_token);
          
                if (multi_next)
                  {
                    multi_token = get_multiple_arg_token(multi_next);
                    multi_next = get_multiple_arg_token_next (multi_next);
                    local_args_info.shellRadius_given++;
                  }
                else
                  break;
              }
            break;
          }
          /* Builds a multi-component random alloy nanoparticle. A mole Fraction must be specified for each component > 1 in the template file..  */
          else if (strcmp (long_options[option_index].name, "molFraction") == 0)
          {
            local_args_info.molFraction_given++;
          
            multi_token = get_multiple_arg_token(optarg);
            multi_next = get_multiple_arg_token_next (optarg);
          
            while (1)
              {
                molFraction_new = (struct molFraction_list *) malloc (sizeof (struct molFraction_list));
                molFraction_new->next = molFraction_list;
                molFraction_list = molFraction_new;
                molFraction_new->molFraction_arg = strtod (multi_token, NULL);
                free (multi_token);
          
                if (multi_next)
                  {
                    multi_token = get_multiple_arg_token(multi_next);
                    multi_next = get_multiple_arg_token_next (multi_next);
                    local_args_info.molFraction_given++;
                  }
                else
                  break;
              }
            break;
          }
          /* Percentage of atoms to remove from within vacancy range.  */
          else if (strcmp (long_options[option_index].name, "vacancyPercent") == 0)
          {
            if (local_args_info.vacancyPercent_given)
              {
                fprintf (stderr, "%s: `--vacancyPercent' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->vacancyPercent_given && ! override)
              continue;
            local_args_info.vacancyPercent_given = 1;
            args_info->vacancyPercent_given = 1;
            args_info->vacancyPercent_arg = strtod (optarg, NULL);
          }
          /* Radius arround core-shell where vacancies should be located..  */
          else if (strcmp (long_options[option_index].name, "vacancyInnerRadius") == 0)
          {
            if (local_args_info.vacancyInnerRadius_given)
              {
                fprintf (stderr, "%s: `--vacancyInnerRadius' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->vacancyInnerRadius_given && ! override)
              continue;
            local_args_info.vacancyInnerRadius_given = 1;
            args_info->vacancyInnerRadius_given = 1;
            args_info->vacancyInnerRadius_arg = strtod (optarg, NULL);
          }
          /* Radius arround core-shell where vacancies should be located..  */
          else if (strcmp (long_options[option_index].name, "vacancyOuterRadius") == 0)
          {
            if (local_args_info.vacancyOuterRadius_given)
              {
                fprintf (stderr, "%s: `--vacancyOuterRadius' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->vacancyOuterRadius_given && ! override)
              continue;
            local_args_info.vacancyOuterRadius_given = 1;
            args_info->vacancyOuterRadius_given = 1;
            args_info->vacancyOuterRadius_arg = strtod (optarg, NULL);
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  if (local_args_info.shellRadius_given && shellRadius_list)
    {
      struct shellRadius_list *tmp;
      args_info->shellRadius_arg = (double *) realloc (args_info->shellRadius_arg, (args_info->shellRadius_given + local_args_info.shellRadius_given) * sizeof (double));
      for (i = (local_args_info.shellRadius_given - 1); i >= 0; --i)
        {
          tmp = shellRadius_list;
          args_info->shellRadius_arg [i + args_info->shellRadius_given] = shellRadius_list->shellRadius_arg;
          shellRadius_list = shellRadius_list->next;
          free (tmp);
        }
    }
  
  if (local_args_info.molFraction_given && molFraction_list)
    {
      struct molFraction_list *tmp;
      args_info->molFraction_arg = (double *) realloc (args_info->molFraction_arg, (args_info->molFraction_given + local_args_info.molFraction_given) * sizeof (double));
      for (i = (local_args_info.molFraction_given - 1); i >= 0; --i)
        {
          tmp = molFraction_list;
          args_info->molFraction_arg [i + args_info->molFraction_given] = molFraction_list->molFraction_arg;
          molFraction_list = molFraction_list->next;
          free (tmp);
        }
    }
  

  args_info->shellRadius_given += local_args_info.shellRadius_given;
  local_args_info.shellRadius_given = 0;
  args_info->molFraction_given += local_args_info.molFraction_given;
  local_args_info.molFraction_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_free (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:
  if (shellRadius_list)
    {
      struct shellRadius_list *tmp;
      while (shellRadius_list)
        {
          tmp = shellRadius_list;
          shellRadius_list = shellRadius_list->next;
          free (tmp);
        }
    }
  if (molFraction_list)
    {
      struct molFraction_list *tmp;
      while (molFraction_list)
        {
          tmp = molFraction_list;
          molFraction_list = molFraction_list->next;
          free (tmp);
        }
    }
  
  cmdline_parser_free (&local_args_info);
  return (EXIT_FAILURE);
}
