Package = visitors

Source    = \
	AtomVisitor.cpp \
	ReplacementVisitor.cpp \
	CompositeVisitor.cpp \
	OtherVisitor.cpp \
	RigidBodyVisitor.cpp \
	ZconsVisitor.cpp \
	LipidTransVisitor.cpp \
	AtomNameVisitor.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile
