Package = visitors

Source    = \
	AtomVisitor.cpp \
	CompositeVisitor.cpp \
	OtherVisitor.cpp \
	RigidBodyVisitor.cpp \
	ZconsVisitor.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile
