Package = applications/atom2mdin

Source    = \
	atom2mdin.cpp
	
BuiltParallelExe = 0

RmiSource =

Main      =atom2mdin 

LinkTargets = \
              pdb2in \
              xyz2in \
	      smi2in \
	      prep2in

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

