Package = parallel

Source    = \
        ForceDecomposition.cpp \
        ForceMatrixDecomposition.cpp \

ParallelSource = \
	ForceMatrixDecomposition.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

