Package = UseTheForce/DarkSide

Source    = \
	simParallel.F90 \
	simParallel_interface.F90 \
	neighborLists.F90 \
	neighborLists_interface.F90 \
	force_globals.F90 \
	simulation.F90 \
	simulation_interface.F90 \

ParallelSource = \
	simParallel.F90 \
	simParallel_interface.F90 \
	neighborLists.F90 \
	force_globals.F90 \
	simulation.F90 \

Modules = \
	force_globals \
	fforceoptions \
	neighborLists \
	mpiSimulation \
	simulation \

RmiSource =

Main      =

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

