Source    = \
	mpiSimulation.F90 \
	neighborLists.F90 \
	atype.F90 \
	force_globals.F90 \
	switcheroo.F90 \
	simulation.F90 \
	charge.F90 \
	dipole.F90 \
	eam.F90 \
	gb.F90 \
	LJ.F90 \
	reactionField.F90 \
	sticky.F90 \
	shapes.F90 \

RmiSource =

Main      =

DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

