/* cmdline.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "sysbuilder"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  int nanoparticle_flag;	/* Build nanoparticle model (default=off).  */
  double vacancies_arg;	/* Build nanoparticle with vacancies %..  */
  double vacancyradius_arg;	/* Radius(A) between core-shell interface to build vacancies..  */
  char * core_arg;	/* Core model name. For a single component particle, the model for the particle..  */
  char * shell_arg;	/* Shell model name..  */
  double randomparticle_arg;	/* Create an random configuration mole fraction %..  */
  int bilayer_flag;	/* Tries to build a basic bilayer with the specified number of lipids in the input bass file. The bilayer will be surrounded by the number of solvent molecules specified in the bass file. -note: combined with -r the simulation will start the lipids randomly oriented in a sea of water. (default=off).  */
  char * lipid_arg;	/* Lipid model in BASS file.  */
  char * water_arg;	/* Water model in BASS file.  */
  int random_flag;	/* Build randomly oriented  lipids in a sea of water (default=off).  */
  char ** include_arg;	/* File name that should be included at the top of the output bass file..  */
  char * output_arg;	/* Output file name.  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int nanoparticle_given ;	/* Whether nanoparticle was given.  */
  int vacancies_given ;	/* Whether vacancies was given.  */
  int vacancyradius_given ;	/* Whether vacancyradius was given.  */
  int core_given ;	/* Whether core was given.  */
  int shell_given ;	/* Whether shell was given.  */
  int randomparticle_given ;	/* Whether randomparticle was given.  */
  int bilayer_given ;	/* Whether bilayer was given.  */
  int lipid_given ;	/* Whether lipid was given.  */
  int water_given ;	/* Whether water was given.  */
  int random_given ;	/* Whether random was given.  */
  int include_given ;	/* Whether include was given.  */
  int output_given ;	/* Whether output was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
