Source    = \
	BaseLattice.cpp \
	cmdline.c \
	Dump2XYZCmd.c \
	Dump2XYZ.cpp \
	getopt1.c \
	getopt.c \
	Lattice.cpp \
	LatticeCreator.cpp \
	LatticeFactory.cpp \
	MoLocator.cpp \
	nanoBuilder.cpp \
	oopse.cpp \
	quickLate.c \
	simpleBuilderCmd.c \
	simpleBuilder.cpp \

RmiSource =

Main      =

include $(DEV_ROOT)/Makefile