Source    = \

RmiSource =

Main      = 

SampleFiles = Ag_Cu_bulkslab_lattice.md \
              bcc.md \
              fcc.md \
              hcp.md \
              icosahedron.md \
              metals.md \
              sc.md \
              surface_icosahedron.md \
              tet.md \
              Readme.txt   


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

