Package = forceFields

Source    = \

RmiSource =

Main      = 

ForcefieldFiles = \
        CLAYFF.frc \
        DUFF2.frc \
        EAM.frc \
        EAM.u3.frc \
        EAM.u6.frc \
        EAM.VC.frc \
        SuttonChen.frc \
        SuttonChen.QSC.frc \
        SuttonChen.SC.frc \
        WATER.frc \
        Ag.u3.funcfl \
        Ag.u6.funcfl \
        Ag.VC.funcfl \
        Al.VC.funcfl \
        Au.u3.funcfl \
        Au.u6.funcfl \
        Au.VC.funcfl \
        Cu.u3.funcfl \
        Cu.u6.funcfl \
        Cu.VC.funcfl \
        Ni.u3.funcfl \
        Ni.u6.funcfl \
        Ni.VC.funcfl \
        Pd.u3.funcfl \
        Pd.u6.funcfl \
        Pd.VC.funcfl \
        Pt.u3.funcfl \
        Pt.u6.funcfl \
        Pt.VC.funcfl \
        aromatic.txt \
        atomtyp.txt \
        bondtyp.txt \
        element.txt \
        isotope-small.txt \
        isotope.txt \
        patterns.txt \
        phmodel.txt \
        resdata.txt \
        SMARTS_InteLigand.txt \
        torlib.txt \
        types.txt 

DEV_ROOT=..
include $(DEV_ROOT)/make/Makefile

