/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt -F Dump2XYZCmd -u 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#ifdef WIN32
#include "utils/wingetopt.h"
#else
#include <getopt.h>
#endif

#include "Dump2XYZCmd.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: Dump2XYZ [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -i, --input=filename          input dump file",
  "  -o, --output=filename         output file name",
  "  -n, --frame=INT               print every n frame  (default=`1')",
  "  -w, --water                   skip the the waters  (default=off)",
  "  -m, --periodicBox             map to the periodic box  (default=off)",
  "  -z, --zconstraint             replace the atom types of zconstraint molecules \n                                   (default=off)",
  "  -r, --rigidbody               add a pseudo COM atom to rigidbody  \n                                  (default=off)",
  "  -t, --watertype               replace the atom type of water model  \n                                  (default=on)",
  "  -s, --selection=selection script\n                                general selection syntax",
  "      --originsele=selection script\n                                select origin",
  "      --refsele=selection script\n                                select reference",
  "      --repeatX=INT             The number of images to repeat in the x \n                                  direction  (default=`0')",
  "      --repeatY=INT             The number of images to repeat in the y \n                                  direction  (default=`0')",
  "      --repeatZ=INT             The number of images to repeat in the z \n                                  direction  (default=`0')",
  "  -b, --basetype                Convert to base atom type  (default=off)",
  "  -v, --velocities              Print velocities in xyz file  (default=off)",
  "  -f, --forces                  Print forces xyz file  (default=off)",
  "  -u, --vectors                 Print vectors (dipoles, etc) in xyz file  \n                                  (default=off)",
  "  -c, --charges                 Print charges in xyz file  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->frame_given = 0 ;
  args_info->water_given = 0 ;
  args_info->periodicBox_given = 0 ;
  args_info->zconstraint_given = 0 ;
  args_info->rigidbody_given = 0 ;
  args_info->watertype_given = 0 ;
  args_info->selection_given = 0 ;
  args_info->originsele_given = 0 ;
  args_info->refsele_given = 0 ;
  args_info->repeatX_given = 0 ;
  args_info->repeatY_given = 0 ;
  args_info->repeatZ_given = 0 ;
  args_info->basetype_given = 0 ;
  args_info->velocities_given = 0 ;
  args_info->forces_given = 0 ;
  args_info->vectors_given = 0 ;
  args_info->charges_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->frame_arg = 1;
  args_info->frame_orig = NULL;
  args_info->water_flag = 0;
  args_info->periodicBox_flag = 0;
  args_info->zconstraint_flag = 0;
  args_info->rigidbody_flag = 0;
  args_info->watertype_flag = 1;
  args_info->selection_arg = NULL;
  args_info->selection_orig = NULL;
  args_info->originsele_arg = NULL;
  args_info->originsele_orig = NULL;
  args_info->refsele_arg = NULL;
  args_info->refsele_orig = NULL;
  args_info->repeatX_arg = 0;
  args_info->repeatX_orig = NULL;
  args_info->repeatY_arg = 0;
  args_info->repeatY_orig = NULL;
  args_info->repeatZ_arg = 0;
  args_info->repeatZ_orig = NULL;
  args_info->basetype_flag = 0;
  args_info->velocities_flag = 0;
  args_info->forces_flag = 0;
  args_info->vectors_flag = 0;
  args_info->charges_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->input_help = gengetopt_args_info_help[2] ;
  args_info->output_help = gengetopt_args_info_help[3] ;
  args_info->frame_help = gengetopt_args_info_help[4] ;
  args_info->water_help = gengetopt_args_info_help[5] ;
  args_info->periodicBox_help = gengetopt_args_info_help[6] ;
  args_info->zconstraint_help = gengetopt_args_info_help[7] ;
  args_info->rigidbody_help = gengetopt_args_info_help[8] ;
  args_info->watertype_help = gengetopt_args_info_help[9] ;
  args_info->selection_help = gengetopt_args_info_help[10] ;
  args_info->originsele_help = gengetopt_args_info_help[11] ;
  args_info->refsele_help = gengetopt_args_info_help[12] ;
  args_info->repeatX_help = gengetopt_args_info_help[13] ;
  args_info->repeatY_help = gengetopt_args_info_help[14] ;
  args_info->repeatZ_help = gengetopt_args_info_help[15] ;
  args_info->basetype_help = gengetopt_args_info_help[16] ;
  args_info->velocities_help = gengetopt_args_info_help[17] ;
  args_info->forces_help = gengetopt_args_info_help[18] ;
  args_info->vectors_help = gengetopt_args_info_help[19] ;
  args_info->charges_help = gengetopt_args_info_help[20] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->frame_orig));
  free_string_field (&(args_info->selection_arg));
  free_string_field (&(args_info->selection_orig));
  free_string_field (&(args_info->originsele_arg));
  free_string_field (&(args_info->originsele_orig));
  free_string_field (&(args_info->refsele_arg));
  free_string_field (&(args_info->refsele_orig));
  free_string_field (&(args_info->repeatX_orig));
  free_string_field (&(args_info->repeatY_orig));
  free_string_field (&(args_info->repeatZ_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->frame_given)
    write_into_file(outfile, "frame", args_info->frame_orig, 0);
  if (args_info->water_given)
    write_into_file(outfile, "water", 0, 0 );
  if (args_info->periodicBox_given)
    write_into_file(outfile, "periodicBox", 0, 0 );
  if (args_info->zconstraint_given)
    write_into_file(outfile, "zconstraint", 0, 0 );
  if (args_info->rigidbody_given)
    write_into_file(outfile, "rigidbody", 0, 0 );
  if (args_info->watertype_given)
    write_into_file(outfile, "watertype", 0, 0 );
  if (args_info->selection_given)
    write_into_file(outfile, "selection", args_info->selection_orig, 0);
  if (args_info->originsele_given)
    write_into_file(outfile, "originsele", args_info->originsele_orig, 0);
  if (args_info->refsele_given)
    write_into_file(outfile, "refsele", args_info->refsele_orig, 0);
  if (args_info->repeatX_given)
    write_into_file(outfile, "repeatX", args_info->repeatX_orig, 0);
  if (args_info->repeatY_given)
    write_into_file(outfile, "repeatY", args_info->repeatY_orig, 0);
  if (args_info->repeatZ_given)
    write_into_file(outfile, "repeatZ", args_info->repeatZ_orig, 0);
  if (args_info->basetype_given)
    write_into_file(outfile, "basetype", 0, 0 );
  if (args_info->velocities_given)
    write_into_file(outfile, "velocities", 0, 0 );
  if (args_info->forces_given)
    write_into_file(outfile, "forces", 0, 0 );
  if (args_info->vectors_given)
    write_into_file(outfile, "vectors", 0, 0 );
  if (args_info->charges_given)
    write_into_file(outfile, "charges", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->input_given)
    {
      fprintf (stderr, "%s: '--input' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "frame",	1, NULL, 'n' },
        { "water",	0, NULL, 'w' },
        { "periodicBox",	0, NULL, 'm' },
        { "zconstraint",	0, NULL, 'z' },
        { "rigidbody",	0, NULL, 'r' },
        { "watertype",	0, NULL, 't' },
        { "selection",	1, NULL, 's' },
        { "originsele",	1, NULL, 0 },
        { "refsele",	1, NULL, 0 },
        { "repeatX",	1, NULL, 0 },
        { "repeatY",	1, NULL, 0 },
        { "repeatZ",	1, NULL, 0 },
        { "basetype",	0, NULL, 'b' },
        { "velocities",	0, NULL, 'v' },
        { "forces",	0, NULL, 'f' },
        { "vectors",	0, NULL, 'u' },
        { "charges",	0, NULL, 'c' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVi:o:n:wmzrts:bvfuc", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* input dump file.  */
        
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* output file name.  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* print every n frame.  */
        
        
          if (update_arg( (void *)&(args_info->frame_arg), 
               &(args_info->frame_orig), &(args_info->frame_given),
              &(local_args_info.frame_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "frame", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* skip the the waters.  */
        
        
          if (update_arg((void *)&(args_info->water_flag), 0, &(args_info->water_given),
              &(local_args_info.water_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "water", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* map to the periodic box.  */
        
        
          if (update_arg((void *)&(args_info->periodicBox_flag), 0, &(args_info->periodicBox_given),
              &(local_args_info.periodicBox_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "periodicBox", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'z':	/* replace the atom types of zconstraint molecules.  */
        
        
          if (update_arg((void *)&(args_info->zconstraint_flag), 0, &(args_info->zconstraint_given),
              &(local_args_info.zconstraint_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "zconstraint", 'z',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* add a pseudo COM atom to rigidbody.  */
        
        
          if (update_arg((void *)&(args_info->rigidbody_flag), 0, &(args_info->rigidbody_given),
              &(local_args_info.rigidbody_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "rigidbody", 'r',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* replace the atom type of water model.  */
        
        
          if (update_arg((void *)&(args_info->watertype_flag), 0, &(args_info->watertype_given),
              &(local_args_info.watertype_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "watertype", 't',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* general selection syntax.  */
        
        
          if (update_arg( (void *)&(args_info->selection_arg), 
               &(args_info->selection_orig), &(args_info->selection_given),
              &(local_args_info.selection_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "selection", 's',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Convert to base atom type.  */
        
        
          if (update_arg((void *)&(args_info->basetype_flag), 0, &(args_info->basetype_given),
              &(local_args_info.basetype_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "basetype", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Print velocities in xyz file.  */
        
        
          if (update_arg((void *)&(args_info->velocities_flag), 0, &(args_info->velocities_given),
              &(local_args_info.velocities_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "velocities", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Print forces xyz file.  */
        
        
          if (update_arg((void *)&(args_info->forces_flag), 0, &(args_info->forces_given),
              &(local_args_info.forces_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "forces", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Print vectors (dipoles, etc) in xyz file.  */
        
        
          if (update_arg((void *)&(args_info->vectors_flag), 0, &(args_info->vectors_given),
              &(local_args_info.vectors_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "vectors", 'u',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Print charges in xyz file.  */
        
        
          if (update_arg((void *)&(args_info->charges_flag), 0, &(args_info->charges_given),
              &(local_args_info.charges_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "charges", 'c',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* select origin.  */
          if (strcmp (long_options[option_index].name, "originsele") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->originsele_arg), 
                 &(args_info->originsele_orig), &(args_info->originsele_given),
                &(local_args_info.originsele_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "originsele", '-',
                additional_error))
              goto failure;
          
          }
          /* select reference.  */
          else if (strcmp (long_options[option_index].name, "refsele") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->refsele_arg), 
                 &(args_info->refsele_orig), &(args_info->refsele_given),
                &(local_args_info.refsele_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "refsele", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of images to repeat in the x direction.  */
          else if (strcmp (long_options[option_index].name, "repeatX") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->repeatX_arg), 
                 &(args_info->repeatX_orig), &(args_info->repeatX_given),
                &(local_args_info.repeatX_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "repeatX", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of images to repeat in the y direction.  */
          else if (strcmp (long_options[option_index].name, "repeatY") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->repeatY_arg), 
                 &(args_info->repeatY_orig), &(args_info->repeatY_given),
                &(local_args_info.repeatY_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "repeatY", '-',
                additional_error))
              goto failure;
          
          }
          /* The number of images to repeat in the z direction.  */
          else if (strcmp (long_options[option_index].name, "repeatZ") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->repeatZ_arg), 
                 &(args_info->repeatZ_orig), &(args_info->repeatZ_given),
                &(local_args_info.repeatZ_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "repeatZ", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
