Source    = \
	AtomStamp.cpp \
	BendStamp.cpp \
	BondStamp.cpp \
	Component.cpp \
	CutoffGroupStamp.cpp \
	MakeStamps.cpp \
	MoleculeStamp.cpp \
	RigidBodyStamp.cpp \
	TorsionStamp.cpp \
	ZconStamp.cpp \

RmiSource =

Main      =

include $(DEV_ROOT)/Makefile