Source    = \
	AtomStamp.cpp \
	BendStamp.cpp \
	BondStamp.cpp \
	Component.cpp \
	CutoffGroupStamp.cpp \
	MakeStamps.cpp \
	MoleculeStamp.cpp \
	RigidBodyStamp.cpp \
	TorsionStamp.cpp \
	ZconStamp.cpp \
	ShapeType.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

