Package = types

Source    = \
	AtomStamp.cpp \
	BendStamp.cpp \
	BondStamp.cpp \
	Component.cpp \
	CutoffGroupStamp.cpp \
	MoleculeStamp.cpp \
	RigidBodyStamp.cpp \
	TorsionStamp.cpp \
	InversionStamp.cpp \
	ZconsStamp.cpp \
	RestraintStamp.cpp \
	AtomType.cpp \
	DirectionalAtomType.cpp \
	ShapeAtomType.cpp \
	CharmmTorsionType.cpp \
 	ImproperCosineInversionType.cpp \
	FragmentStamp.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

