Package = openbabel

Source    = \
    obatom.cpp\
    base.cpp \
    bitvec.cpp\
    obbond.cpp\
    bondtyper.cpp\
    chains.cpp\
    chiral.cpp\
    data.cpp\
    fingerprint.cpp\
    generic.cpp\
    grid.cpp\
    kekulize.cpp\
    matrix.cpp\
    molchrg.cpp\
    mol.cpp\
    oberror.cpp\
    obiter.cpp\
    obutil.cpp\
    parsmart.cpp\
    patty.cpp\
    phmodel.cpp\
    rand.cpp\
    residue.cpp\
    ring.cpp\
    rotamer.cpp\
    rotor.cpp\
    tokenst.cpp\
    transform.cpp\
    typer.cpp\
    vector3.cpp\
    matrix3x3.cpp\
    obconversion.cpp \
    oopseformat.cpp\
    pdbformat.cpp\
    tinkerformat.cpp\
    xyzformat.cpp\
    amberformat.cpp\
    fingerprintformat.cpp\
    gromos96format.cpp\
    povrayformat.cpp\
    smilesformat.cpp\
    tinkerformat.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

