Source    = \

RmiSource =

Main      = 

SampleFiles = \
	cutoff_test.in \
	gb-ar.in \
	GB-Ar-max.md \
	GB-Ar-mix.md \
	GB-Ar-traditional.md \
	gb.md \
	lj.md \
	max.md \
	mix.md \
	traditional.md \


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

