Package = integrators

Source    = \
	Integrator.cpp \
        IntegratorFactory.cpp \
	Velocitizer.cpp \
	VelocityVerletIntegrator.cpp \
	DLM.cpp \
        NVE.cpp \
	NVT.cpp \
        NPT.cpp \
	NPTi.cpp \
	NPTf.cpp \
	NPTxyz.cpp \
	NPAT.cpp \
	NPrT.cpp \
	NgammaT.cpp \
	LDForceManager.cpp \
	SMIPDForceManager.cpp \
        SMIPDynamics.cpp \
        LangevinDynamics.cpp	

ParallelSource = \
	Velocitizer.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

