Source    = \
	Integrator.cpp \
        IntegratorFactory.cpp \
	Velocitizer.cpp \
	VelocityVerletIntegrator.cpp \
	DLM.cpp \
        NVE.cpp \
	NVT.cpp \
        NPT.cpp \
	NPTi.cpp \
	NPTf.cpp \
	NPTxyz.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

