Source    = \
	do_Forces.F90 \
	DUFF.cpp \
	EAM_FF.cpp \
	ForceFields.cpp \
	fortranWrappers.cpp \
	LJFF.cpp \
	mpiForceField.c \
	mpiSimulation_module.F90 \
	WATER.cpp \
	notifyCutoffs.F90 \
	wrappers.F90 \

RmiSource =

Main      =

include $(DEV_ROOT)/Makefile
