Source    = \
	doForces.F90 \
	doForces_interface.F90 \
        ForceField.cpp \
        ForceFieldFactory.cpp \
        DUFF.cpp \
	EAM.cpp \
	notifyCutoffs.F90 \
	notifyCutoffs_interface.F90

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

