Source    = \
	do_Forces.F90 \
	DUFF.cpp \
	EAM_FF.cpp \
	ForceFields.cpp \
	fortranWrappers.cpp \
	LJFF.cpp \
	mpiForceField.c \
	WATER.cpp \
	Shapes_FF.cpp \
	notifyCutoffs.F90 \
	wrappers.F90 \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

