Source    = \

RmiSource =

Main      = 

SampleFiles =  \
	Au_nanoparticle_0Pa.md \
	Au_nanoparticle_10GPa.md \
	Au_nanoparticle_2GPa.md \
	Au_nanoparticle_4GPa.md \
	Au_nanoparticle_6GPa.md \
	Au_nanoparticle_8GPa.md \
	metals.md \
	spce.diff \
	spce.md \
	spce_cluster.diff \
	spce_cluster.md \
	thiols.md \
	water.md

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

