Source    = \

RmiSource =

Main      = 

SampleFiles =  \
              Lipid.frc \
              Makefile \
              splitDipole.md \
              splitInWater.in \
              splitInWater.md \
              split_SSD.in \
              split_SSD.md \
              twoSplitDipole.in \
              twoSplitDipole.md \
              water.md 


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

