Package = restraints

Source    = \
	ObjectRestraint.cpp \
	MolecularRestraint.cpp \
	RestraintForceManager.cpp \
	ThermoIntegrationForceManager.cpp

ParallelSource = \
	RestraintForceManager.cpp \
	ThermoIntegrationForceManager.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

