Package = restraints

Source    = \
	Restraints.cpp \
	ThermoIntegrationForceManager.cpp

ParallelSource = \
	ThermoIntegrationForceManager.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

