Package = selection

Source    = \
	SelectionToken.cpp \
	TokenMap.cpp \
	SelectionCompiler.cpp \
	SelectionEvaluator.cpp \
	NameFinder.cpp \
	DistanceFinder.cpp \
	HullFinder.cpp \
	IndexFinder.cpp \
	SelectionManager.cpp \
	

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile
