Package = selection

Source    = \
	Token.cpp \
	TokenMap.cpp \
	SelectionCompiler.cpp \
	SelectionEvaluator.cpp \
	NameFinder.cpp \
	DistanceFinder.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile
