Source    = \
	definitions.F90 \
	fError.c \
	GenericData.cpp \
	oopseMPI.F90 \
	simError.c \
	status.F90 \
	StreamTokenizer.cpp \
	StringUtils.cpp \
	Utility.cpp \
	vector_class.F90 \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile
