Package = minimizers

Source    = \
        MinimizerParameterSet.cpp \
        Minimizer.cpp \
	MinimizerFactory.cpp \
	CGFamilyMinimizer.cpp \
	PRCG.cpp \
	SDMinimizer.cpp \

ParallelSource = \
	CGFamilyMinimizer.cpp \
	Minimizer.cpp \
	PRCG.cpp \
	SDMinimizer.cpp 

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

