Source    = \

RmiSource =

Main      = 

SampleFiles = 500.in   \
              500.md   \
              ar864.in \
              ar864.md \
              argonNVT.dump \
              argonNVT.eor \
              argonNVT.in \
              argonNVT.md


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

