Package = lattice

Source    = \
	Lattice.cpp \
	CubicLattice.cpp \
	FCCLattice.cpp \
	LatticeFactory.cpp \
	shapedLattice.cpp 

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

