Source    = \

RmiSource =

Main      = 

SampleFiles =  \
        two.md \
        two.in \
        water.md \
        cl.in \
        cl.md \
        mix2.in \
        mix2.md \
        mix.in \
        mix.md \
        ssd.in \
        ssd.md \


DEV_ROOT=../../..
include $(DEV_ROOT)/make/Makefile

