Package = math

Source    = \
				ParallelRandNumGen.cpp \
                                SeqRandNumGen.cpp \
				RealSphericalHarmonic.cpp \
				ChebyshevPolynomials.cpp \
                                LegendrePolynomial.cpp \
                                linearAlgebra.F90 \
                                Wigner3jm.F90 

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

