Package = math

Source    = \
				ParallelRandNumGen.cpp \
                                SeqRandNumGen.cpp \
				RealSphericalHarmonic.cpp \
				ChebyshevPolynomials.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

