// Built using NPG-Builder
#ifndef P20_INC
#define P20_INC

molecule{
  name = "p20";

  atom[0] { type = "CB"; position( 1.18645, 0, 0); }
  atom[1] { type = "CB"; position( 1.18645, 1.37, 0); }
  atom[2] { type = "CB"; position( 0, 2.055, 0); }
  atom[3] { type = "CB"; position( 0, 3.425, 0); }
  atom[4] { type = "CB"; position( 3.55936, 0, 0); }
  atom[5] { type = "CB"; position( 3.55936, 1.37, 0); }
  atom[6] { type = "CB"; position( 2.37291, 2.055, 0); }
  atom[7] { type = "CB"; position( 2.37291, 3.425, 0); }
  atom[8] { type = "CB"; position( 5.93227, 0, 0); }
  atom[9] { type = "CB"; position( 5.93227, 1.37, 0); }
  atom[10] { type = "CB"; position( 4.74582, 2.055, 0); }
  atom[11] { type = "CB"; position( 4.74582, 3.425, 0); }
  atom[12] { type = "CB"; position( 8.30518, 0, 0); }
  atom[13] { type = "CB"; position( 8.30518, 1.37, 0); }
  atom[14] { type = "CB"; position( 7.11873, 2.055, 0); }
  atom[15] { type = "CB"; position( 7.11873, 3.425, 0); }
  atom[16] { type = "CB"; position( 10.6781, 0, 0); }
  atom[17] { type = "CB"; position( 10.6781, 1.37, 0); }
  atom[18] { type = "CB"; position( 9.49164, 2.055, 0); }
  atom[19] { type = "CB"; position( 9.49164, 3.425, 0); }
  atom[20] { type = "CB"; position( 13.051, 0, 0); }
  atom[21] { type = "CB"; position( 13.051, 1.37, 0); }
  atom[22] { type = "CB"; position( 11.8645, 2.055, 0); }
  atom[23] { type = "CB"; position( 11.8645, 3.425, 0); }
  atom[24] { type = "CB"; position( 15.4239, 0, 0); }
  atom[25] { type = "CB"; position( 15.4239, 1.37, 0); }
  atom[26] { type = "CB"; position( 14.2375, 2.055, 0); }
  atom[27] { type = "CB"; position( 14.2375, 3.425, 0); }
  atom[28] { type = "CB"; position( 17.7968, 0, 0); }
  atom[29] { type = "CB"; position( 17.7968, 1.37, 0); }
  atom[30] { type = "CB"; position( 16.6104, 2.055, 0); }
  atom[31] { type = "CB"; position( 16.6104, 3.425, 0); }
  atom[32] { type = "CB"; position( 20.1697, 0, 0); }
  atom[33] { type = "CB"; position( 20.1697, 1.37, 0); }
  atom[34] { type = "CB"; position( 18.9833, 2.055, 0); }
  atom[35] { type = "CB"; position( 18.9833, 3.425, 0); }
  atom[36] { type = "CB"; position( 22.5426, 0, 0); }
  atom[37] { type = "CB"; position( 22.5426, 1.37, 0); }
  atom[38] { type = "CB"; position( 21.3562, 2.055, 0); }
  atom[39] { type = "CB"; position( 21.3562, 3.425, 0); }
  atom[40] { type = "CB"; position( 24.9156, 0, 0); }
  atom[41] { type = "CB"; position( 24.9156, 1.37, 0); }
  atom[42] { type = "CB"; position( 23.7291, 2.055, 0); }
  atom[43] { type = "CB"; position( 23.7291, 3.425, 0); }
  atom[44] { type = "CB"; position( 27.2885, 0, 0); }
  atom[45] { type = "CB"; position( 27.2885, 1.37, 0); }
  atom[46] { type = "CB"; position( 26.102, 2.055, 0); }
  atom[47] { type = "CB"; position( 26.102, 3.425, 0); }
  atom[48] { type = "CB"; position( 29.6614, 0, 0); }
  atom[49] { type = "CB"; position( 29.6614, 1.37, 0); }
  atom[50] { type = "CB"; position( 28.4749, 2.055, 0); }
  atom[51] { type = "CB"; position( 28.4749, 3.425, 0); }
  atom[52] { type = "CB"; position( 32.0343, 0, 0); }
  atom[53] { type = "CB"; position( 32.0343, 1.37, 0); }
  atom[54] { type = "CB"; position( 30.8478, 2.055, 0); }
  atom[55] { type = "CB"; position( 30.8478, 3.425, 0); }
  atom[56] { type = "CB"; position( 34.4072, 0, 0); }
  atom[57] { type = "CB"; position( 34.4072, 1.37, 0); }
  atom[58] { type = "CB"; position( 33.2207, 2.055, 0); }
  atom[59] { type = "CB"; position( 33.2207, 3.425, 0); }
  atom[60] { type = "CB"; position( 36.7801, 0, 0); }
  atom[61] { type = "CB"; position( 36.7801, 1.37, 0); }
  atom[62] { type = "CB"; position( 35.5936, 2.055, 0); }
  atom[63] { type = "CB"; position( 35.5936, 3.425, 0); }
  atom[64] { type = "CB"; position( 39.153, 0, 0); }
  atom[65] { type = "CB"; position( 39.153, 1.37, 0); }
  atom[66] { type = "CB"; position( 37.9666, 2.055, 0); }
  atom[67] { type = "CB"; position( 37.9666, 3.425, 0); }
  atom[68] { type = "CB"; position( 1.18645, 4.11, 0); }
  atom[69] { type = "CB"; position( 1.18645, 5.48, 0); }
  atom[70] { type = "CB"; position( 0, 6.165, 0); }
  atom[71] { type = "CB"; position( 0, 7.535, 0); }
  atom[72] { type = "CB"; position( 3.55936, 4.11, 0); }
  atom[73] { type = "CB"; position( 3.55936, 5.48, 0); }
  atom[74] { type = "CB"; position( 2.37291, 6.165, 0); }
  atom[75] { type = "CB"; position( 2.37291, 7.535, 0); }
  atom[76] { type = "CB"; position( 5.93227, 4.11, 0); }
  atom[77] { type = "CB"; position( 5.93227, 5.48, 0); }
  atom[78] { type = "CB"; position( 4.74582, 6.165, 0); }
  atom[79] { type = "CB"; position( 4.74582, 7.535, 0); }
  atom[80] { type = "CB"; position( 8.30518, 4.11, 0); }
  atom[81] { type = "CB"; position( 8.30518, 5.48, 0); }
  atom[82] { type = "CB"; position( 7.11873, 6.165, 0); }
  atom[83] { type = "CB"; position( 7.11873, 7.535, 0); }
  atom[84] { type = "CB"; position( 10.6781, 4.11, 0); }
  atom[85] { type = "CB"; position( 10.6781, 5.48, 0); }
  atom[86] { type = "CB"; position( 9.49164, 6.165, 0); }
  atom[87] { type = "CB"; position( 9.49164, 7.535, 0); }
  atom[88] { type = "CB"; position( 13.051, 4.11, 0); }
  atom[89] { type = "CB"; position( 13.051, 5.48, 0); }
  atom[90] { type = "CB"; position( 11.8645, 6.165, 0); }
  atom[91] { type = "CB"; position( 11.8645, 7.535, 0); }
  atom[92] { type = "CB"; position( 15.4239, 4.11, 0); }
  atom[93] { type = "CB"; position( 15.4239, 5.48, 0); }
  atom[94] { type = "CB"; position( 14.2375, 6.165, 0); }
  atom[95] { type = "CB"; position( 14.2375, 7.535, 0); }
  atom[96] { type = "CB"; position( 17.7968, 4.11, 0); }
  atom[97] { type = "CB"; position( 17.7968, 5.48, 0); }
  atom[98] { type = "CB"; position( 16.6104, 6.165, 0); }
  atom[99] { type = "CB"; position( 16.6104, 7.535, 0); }
  atom[100] { type = "CB"; position( 20.1697, 4.11, 0); }
  atom[101] { type = "CB"; position( 20.1697, 5.48, 0); }
  atom[102] { type = "CB"; position( 18.9833, 6.165, 0); }
  atom[103] { type = "CB"; position( 18.9833, 7.535, 0); }
  atom[104] { type = "CB"; position( 22.5426, 4.11, 0); }
  atom[105] { type = "CB"; position( 22.5426, 5.48, 0); }
  atom[106] { type = "CB"; position( 21.3562, 6.165, 0); }
  atom[107] { type = "CB"; position( 21.3562, 7.535, 0); }
  atom[108] { type = "CB"; position( 24.9156, 4.11, 0); }
  atom[109] { type = "CB"; position( 24.9156, 5.48, 0); }
  atom[110] { type = "CB"; position( 23.7291, 6.165, 0); }
  atom[111] { type = "CB"; position( 23.7291, 7.535, 0); }
  atom[112] { type = "CB"; position( 27.2885, 4.11, 0); }
  atom[113] { type = "CB"; position( 27.2885, 5.48, 0); }
  atom[114] { type = "CB"; position( 26.102, 6.165, 0); }
  atom[115] { type = "CB"; position( 26.102, 7.535, 0); }
  atom[116] { type = "CB"; position( 29.6614, 4.11, 0); }
  atom[117] { type = "CB"; position( 29.6614, 5.48, 0); }
  atom[118] { type = "CB"; position( 28.4749, 6.165, 0); }
  atom[119] { type = "CB"; position( 28.4749, 7.535, 0); }
  atom[120] { type = "CB"; position( 32.0343, 4.11, 0); }
  atom[121] { type = "CB"; position( 32.0343, 5.48, 0); }
  atom[122] { type = "CB"; position( 30.8478, 6.165, 0); }
  atom[123] { type = "CB"; position( 30.8478, 7.535, 0); }
  atom[124] { type = "CB"; position( 34.4072, 4.11, 0); }
  atom[125] { type = "CB"; position( 34.4072, 5.48, 0); }
  atom[126] { type = "CB"; position( 33.2207, 6.165, 0); }
  atom[127] { type = "CB"; position( 33.2207, 7.535, 0); }
  atom[128] { type = "CB"; position( 36.7801, 4.11, 0); }
  atom[129] { type = "CB"; position( 36.7801, 5.48, 0); }
  atom[130] { type = "CB"; position( 35.5936, 6.165, 0); }
  atom[131] { type = "CB"; position( 35.5936, 7.535, 0); }
  atom[132] { type = "CB"; position( 39.153, 4.11, 0); }
  atom[133] { type = "CB"; position( 39.153, 5.48, 0); }
  atom[134] { type = "CB"; position( 37.9666, 6.165, 0); }
  atom[135] { type = "CB"; position( 37.9666, 7.535, 0); }
  atom[136] { type = "CB"; position( 1.18645, 8.22, 0); }
  atom[137] { type = "CB"; position( 1.18645, 9.59, 0); }
  atom[138] { type = "CB"; position( 0, 10.275, 0); }
  atom[139] { type = "CB"; position( 0, 11.645, 0); }
  atom[140] { type = "CB"; position( 3.55936, 8.22, 0); }
  atom[141] { type = "CB"; position( 3.55936, 9.59, 0); }
  atom[142] { type = "CB"; position( 2.37291, 10.275, 0); }
  atom[143] { type = "CB"; position( 2.37291, 11.645, 0); }
  atom[144] { type = "CB"; position( 5.93227, 8.22, 0); }
  atom[145] { type = "CB"; position( 5.93227, 9.59, 0); }
  atom[146] { type = "CB"; position( 4.74582, 10.275, 0); }
  atom[147] { type = "CB"; position( 4.74582, 11.645, 0); }
  atom[148] { type = "CB"; position( 8.30518, 8.22, 0); }
  atom[149] { type = "CB"; position( 8.30518, 9.59, 0); }
  atom[150] { type = "CB"; position( 7.11873, 10.275, 0); }
  atom[151] { type = "CB"; position( 7.11873, 11.645, 0); }
  atom[152] { type = "CB"; position( 10.6781, 8.22, 0); }
  atom[153] { type = "CB"; position( 10.6781, 9.59, 0); }
  atom[154] { type = "CB"; position( 9.49164, 10.275, 0); }
  atom[155] { type = "CB"; position( 9.49164, 11.645, 0); }
  atom[156] { type = "CB"; position( 13.051, 8.22, 0); }
  atom[157] { type = "CB"; position( 13.051, 9.59, 0); }
  atom[158] { type = "CB"; position( 11.8645, 10.275, 0); }
  atom[159] { type = "CB"; position( 11.8645, 11.645, 0); }
  atom[160] { type = "CB"; position( 15.4239, 8.22, 0); }
  atom[161] { type = "CB"; position( 15.4239, 9.59, 0); }
  atom[162] { type = "CB"; position( 14.2375, 10.275, 0); }
  atom[163] { type = "CB"; position( 14.2375, 11.645, 0); }
  atom[164] { type = "CB"; position( 17.7968, 8.22, 0); }
  atom[165] { type = "CB"; position( 17.7968, 9.59, 0); }
  atom[166] { type = "CB"; position( 16.6104, 10.275, 0); }
  atom[167] { type = "CB"; position( 16.6104, 11.645, 0); }
  atom[168] { type = "CB"; position( 20.1697, 8.22, 0); }
  atom[169] { type = "CB"; position( 20.1697, 9.59, 0); }
  atom[170] { type = "CB"; position( 18.9833, 10.275, 0); }
  atom[171] { type = "CB"; position( 18.9833, 11.645, 0); }
  atom[172] { type = "CB"; position( 22.5426, 8.22, 0); }
  atom[173] { type = "CB"; position( 22.5426, 9.59, 0); }
  atom[174] { type = "CB"; position( 21.3562, 10.275, 0); }
  atom[175] { type = "CB"; position( 21.3562, 11.645, 0); }
  atom[176] { type = "CB"; position( 24.9156, 8.22, 0); }
  atom[177] { type = "CB"; position( 24.9156, 9.59, 0); }
  atom[178] { type = "CB"; position( 23.7291, 10.275, 0); }
  atom[179] { type = "CB"; position( 23.7291, 11.645, 0); }
  atom[180] { type = "CB"; position( 27.2885, 8.22, 0); }
  atom[181] { type = "CB"; position( 27.2885, 9.59, 0); }
  atom[182] { type = "CB"; position( 26.102, 10.275, 0); }
  atom[183] { type = "CB"; position( 26.102, 11.645, 0); }
  atom[184] { type = "CB"; position( 29.6614, 8.22, 0); }
  atom[185] { type = "CB"; position( 29.6614, 9.59, 0); }
  atom[186] { type = "CB"; position( 28.4749, 10.275, 0); }
  atom[187] { type = "CB"; position( 28.4749, 11.645, 0); }
  atom[188] { type = "CB"; position( 32.0343, 8.22, 0); }
  atom[189] { type = "CB"; position( 32.0343, 9.59, 0); }
  atom[190] { type = "CB"; position( 30.8478, 10.275, 0); }
  atom[191] { type = "CB"; position( 30.8478, 11.645, 0); }
  atom[192] { type = "CB"; position( 34.4072, 8.22, 0); }
  atom[193] { type = "CB"; position( 34.4072, 9.59, 0); }
  atom[194] { type = "CB"; position( 33.2207, 10.275, 0); }
  atom[195] { type = "CB"; position( 33.2207, 11.645, 0); }
  atom[196] { type = "CB"; position( 36.7801, 8.22, 0); }
  atom[197] { type = "CB"; position( 36.7801, 9.59, 0); }
  atom[198] { type = "CB"; position( 35.5936, 10.275, 0); }
  atom[199] { type = "CB"; position( 35.5936, 11.645, 0); }
  atom[200] { type = "CB"; position( 39.153, 8.22, 0); }
  atom[201] { type = "CB"; position( 39.153, 9.59, 0); }
  atom[202] { type = "CB"; position( 37.9666, 10.275, 0); }
  atom[203] { type = "CB"; position( 37.9666, 11.645, 0); }
  atom[204] { type = "CB"; position( 1.18645, 12.33, 0); }
  atom[205] { type = "CB"; position( 1.18645, 13.7, 0); }
  atom[206] { type = "CB"; position( 0, 14.385, 0); }
  atom[207] { type = "CB"; position( 0, 15.755, 0); }
  atom[208] { type = "CB"; position( 3.55936, 12.33, 0); }
  atom[209] { type = "CB"; position( 3.55936, 13.7, 0); }
  atom[210] { type = "CB"; position( 2.37291, 14.385, 0); }
  atom[211] { type = "CB"; position( 2.37291, 15.755, 0); }
  atom[212] { type = "CB"; position( 5.93227, 12.33, 0); }
  atom[213] { type = "CB"; position( 5.93227, 13.7, 0); }
  atom[214] { type = "CB"; position( 4.74582, 14.385, 0); }
  atom[215] { type = "CB"; position( 4.74582, 15.755, 0); }
  atom[216] { type = "CB"; position( 8.30518, 12.33, 0); }
  atom[217] { type = "CB"; position( 8.30518, 13.7, 0); }
  atom[218] { type = "CB"; position( 7.11873, 14.385, 0); }
  atom[219] { type = "CB"; position( 7.11873, 15.755, 0); }
  atom[220] { type = "CB"; position( 10.6781, 12.33, 0); }
  atom[221] { type = "CB"; position( 10.6781, 13.7, 0); }
  atom[222] { type = "CB"; position( 9.49164, 14.385, 0); }
  atom[223] { type = "CB"; position( 9.49164, 15.755, 0); }
  atom[224] { type = "CB"; position( 13.051, 12.33, 0); }
  atom[225] { type = "CB"; position( 13.051, 13.7, 0); }
  atom[226] { type = "CB"; position( 11.8645, 14.385, 0); }
  atom[227] { type = "CB"; position( 11.8645, 15.755, 0); }
  atom[228] { type = "CB"; position( 15.4239, 12.33, 0); }
  atom[229] { type = "CB"; position( 15.4239, 13.7, 0); }
  atom[230] { type = "CB"; position( 14.2375, 14.385, 0); }
  atom[231] { type = "CB"; position( 14.2375, 15.755, 0); }
  atom[232] { type = "CB"; position( 17.7968, 12.33, 0); }
  atom[233] { type = "CB"; position( 17.7968, 13.7, 0); }
  atom[234] { type = "CB"; position( 16.6104, 14.385, 0); }
  atom[235] { type = "CB"; position( 16.6104, 15.755, 0); }
  atom[236] { type = "CB"; position( 20.1697, 12.33, 0); }
  atom[237] { type = "CB"; position( 20.1697, 13.7, 0); }
  atom[238] { type = "CB"; position( 18.9833, 14.385, 0); }
  atom[239] { type = "CB"; position( 18.9833, 15.755, 0); }
  atom[240] { type = "CB"; position( 22.5426, 12.33, 0); }
  atom[241] { type = "CB"; position( 22.5426, 13.7, 0); }
  atom[242] { type = "CB"; position( 21.3562, 14.385, 0); }
  atom[243] { type = "CB"; position( 21.3562, 15.755, 0); }
  atom[244] { type = "CB"; position( 24.9156, 12.33, 0); }
  atom[245] { type = "CB"; position( 24.9156, 13.7, 0); }
  atom[246] { type = "CB"; position( 23.7291, 14.385, 0); }
  atom[247] { type = "CB"; position( 23.7291, 15.755, 0); }
  atom[248] { type = "CB"; position( 27.2885, 12.33, 0); }
  atom[249] { type = "CB"; position( 27.2885, 13.7, 0); }
  atom[250] { type = "CB"; position( 26.102, 14.385, 0); }
  atom[251] { type = "CB"; position( 26.102, 15.755, 0); }
  atom[252] { type = "CB"; position( 29.6614, 12.33, 0); }
  atom[253] { type = "CB"; position( 29.6614, 13.7, 0); }
  atom[254] { type = "CB"; position( 28.4749, 14.385, 0); }
  atom[255] { type = "CB"; position( 28.4749, 15.755, 0); }
  atom[256] { type = "CB"; position( 32.0343, 12.33, 0); }
  atom[257] { type = "CB"; position( 32.0343, 13.7, 0); }
  atom[258] { type = "CB"; position( 30.8478, 14.385, 0); }
  atom[259] { type = "CB"; position( 30.8478, 15.755, 0); }
  atom[260] { type = "CB"; position( 34.4072, 12.33, 0); }
  atom[261] { type = "CB"; position( 34.4072, 13.7, 0); }
  atom[262] { type = "CB"; position( 33.2207, 14.385, 0); }
  atom[263] { type = "CB"; position( 33.2207, 15.755, 0); }
  atom[264] { type = "CB"; position( 36.7801, 12.33, 0); }
  atom[265] { type = "CB"; position( 36.7801, 13.7, 0); }
  atom[266] { type = "CB"; position( 35.5936, 14.385, 0); }
  atom[267] { type = "CB"; position( 35.5936, 15.755, 0); }
  atom[268] { type = "CB"; position( 39.153, 12.33, 0); }
  atom[269] { type = "CB"; position( 39.153, 13.7, 0); }
  atom[270] { type = "CB"; position( 37.9666, 14.385, 0); }
  atom[271] { type = "CB"; position( 37.9666, 15.755, 0); }
  atom[272] { type = "CB"; position( 1.18645, 16.44, 0); }
  atom[273] { type = "CB"; position( 1.18645, 17.81, 0); }
  atom[274] { type = "CB"; position( 0, 18.495, 0); }
  atom[275] { type = "CB"; position( 0, 19.865, 0); }
  atom[276] { type = "CB"; position( 3.55936, 16.44, 0); }
  atom[277] { type = "CB"; position( 3.55936, 17.81, 0); }
  atom[278] { type = "CB"; position( 2.37291, 18.495, 0); }
  atom[279] { type = "CB"; position( 2.37291, 19.865, 0); }
  atom[280] { type = "CB"; position( 5.93227, 16.44, 0); }
  atom[281] { type = "CB"; position( 5.93227, 17.81, 0); }
  atom[282] { type = "CB"; position( 4.74582, 18.495, 0); }
  atom[283] { type = "CB"; position( 4.74582, 19.865, 0); }
  atom[284] { type = "CB"; position( 8.30518, 16.44, 0); }
  atom[285] { type = "CB"; position( 8.30518, 17.81, 0); }
  atom[286] { type = "CB"; position( 7.11873, 18.495, 0); }
  atom[287] { type = "CB"; position( 7.11873, 19.865, 0); }
  atom[288] { type = "CB"; position( 10.6781, 16.44, 0); }
  atom[289] { type = "CB"; position( 10.6781, 17.81, 0); }
  atom[290] { type = "CB"; position( 9.49164, 18.495, 0); }
  atom[291] { type = "CB"; position( 9.49164, 19.865, 0); }
  atom[292] { type = "CB"; position( 13.051, 16.44, 0); }
  atom[293] { type = "CB"; position( 13.051, 17.81, 0); }
  atom[294] { type = "CB"; position( 11.8645, 18.495, 0); }
  atom[295] { type = "CB"; position( 11.8645, 19.865, 0); }
  atom[296] { type = "CB"; position( 15.4239, 16.44, 0); }
  atom[297] { type = "CB"; position( 14.2375, 18.495, 0); }
  atom[298] { type = "CB"; position( 14.2375, 19.865, 0); }
  atom[299] { type = "CB"; position( 24.9156, 16.44, 0); }
  atom[300] { type = "CB"; position( 27.2885, 16.44, 0); }
  atom[301] { type = "CB"; position( 27.2885, 17.81, 0); }
  atom[302] { type = "CB"; position( 26.102, 18.495, 0); }
  atom[303] { type = "CB"; position( 26.102, 19.865, 0); }
  atom[304] { type = "CB"; position( 29.6614, 16.44, 0); }
  atom[305] { type = "CB"; position( 29.6614, 17.81, 0); }
  atom[306] { type = "CB"; position( 28.4749, 18.495, 0); }
  atom[307] { type = "CB"; position( 28.4749, 19.865, 0); }
  atom[308] { type = "CB"; position( 32.0343, 16.44, 0); }
  atom[309] { type = "CB"; position( 32.0343, 17.81, 0); }
  atom[310] { type = "CB"; position( 30.8478, 18.495, 0); }
  atom[311] { type = "CB"; position( 30.8478, 19.865, 0); }
  atom[312] { type = "CB"; position( 34.4072, 16.44, 0); }
  atom[313] { type = "CB"; position( 34.4072, 17.81, 0); }
  atom[314] { type = "CB"; position( 33.2207, 18.495, 0); }
  atom[315] { type = "CB"; position( 33.2207, 19.865, 0); }
  atom[316] { type = "CB"; position( 36.7801, 16.44, 0); }
  atom[317] { type = "CB"; position( 36.7801, 17.81, 0); }
  atom[318] { type = "CB"; position( 35.5936, 18.495, 0); }
  atom[319] { type = "CB"; position( 35.5936, 19.865, 0); }
  atom[320] { type = "CB"; position( 39.153, 16.44, 0); }
  atom[321] { type = "CB"; position( 39.153, 17.81, 0); }
  atom[322] { type = "CB"; position( 37.9666, 18.495, 0); }
  atom[323] { type = "CB"; position( 37.9666, 19.865, 0); }
  atom[324] { type = "CB"; position( 1.18645, 20.55, 0); }
  atom[325] { type = "CB"; position( 1.18645, 21.92, 0); }
  atom[326] { type = "CB"; position( 0, 22.605, 0); }
  atom[327] { type = "CB"; position( 0, 23.975, 0); }
  atom[328] { type = "CB"; position( 3.55936, 20.55, 0); }
  atom[329] { type = "CB"; position( 3.55936, 21.92, 0); }
  atom[330] { type = "CB"; position( 2.37291, 22.605, 0); }
  atom[331] { type = "CB"; position( 2.37291, 23.975, 0); }
  atom[332] { type = "CB"; position( 5.93227, 20.55, 0); }
  atom[333] { type = "CB"; position( 5.93227, 21.92, 0); }
  atom[334] { type = "CB"; position( 4.74582, 22.605, 0); }
  atom[335] { type = "CB"; position( 4.74582, 23.975, 0); }
  atom[336] { type = "CB"; position( 8.30518, 20.55, 0); }
  atom[337] { type = "CB"; position( 8.30518, 21.92, 0); }
  atom[338] { type = "CB"; position( 7.11873, 22.605, 0); }
  atom[339] { type = "CB"; position( 7.11873, 23.975, 0); }
  atom[340] { type = "CB"; position( 10.6781, 20.55, 0); }
  atom[341] { type = "CB"; position( 10.6781, 21.92, 0); }
  atom[342] { type = "CB"; position( 9.49164, 22.605, 0); }
  atom[343] { type = "CB"; position( 9.49164, 23.975, 0); }
  atom[344] { type = "CB"; position( 13.051, 20.55, 0); }
  atom[345] { type = "CB"; position( 13.051, 21.92, 0); }
  atom[346] { type = "CB"; position( 11.8645, 22.605, 0); }
  atom[347] { type = "CB"; position( 11.8645, 23.975, 0); }
  atom[348] { type = "CB"; position( 14.2375, 22.605, 0); }
  atom[349] { type = "CB"; position( 14.2375, 23.975, 0); }
  atom[350] { type = "CB"; position( 24.9156, 21.92, 0); }
  atom[351] { type = "CB"; position( 23.7291, 23.975, 0); }
  atom[352] { type = "CB"; position( 27.2885, 20.55, 0); }
  atom[353] { type = "CB"; position( 27.2885, 21.92, 0); }
  atom[354] { type = "CB"; position( 26.102, 22.605, 0); }
  atom[355] { type = "CB"; position( 26.102, 23.975, 0); }
  atom[356] { type = "CB"; position( 29.6614, 20.55, 0); }
  atom[357] { type = "CB"; position( 29.6614, 21.92, 0); }
  atom[358] { type = "CB"; position( 28.4749, 22.605, 0); }
  atom[359] { type = "CB"; position( 28.4749, 23.975, 0); }
  atom[360] { type = "CB"; position( 32.0343, 20.55, 0); }
  atom[361] { type = "CB"; position( 32.0343, 21.92, 0); }
  atom[362] { type = "CB"; position( 30.8478, 22.605, 0); }
  atom[363] { type = "CB"; position( 30.8478, 23.975, 0); }
  atom[364] { type = "CB"; position( 34.4072, 20.55, 0); }
  atom[365] { type = "CB"; position( 34.4072, 21.92, 0); }
  atom[366] { type = "CB"; position( 33.2207, 22.605, 0); }
  atom[367] { type = "CB"; position( 33.2207, 23.975, 0); }
  atom[368] { type = "CB"; position( 36.7801, 20.55, 0); }
  atom[369] { type = "CB"; position( 36.7801, 21.92, 0); }
  atom[370] { type = "CB"; position( 35.5936, 22.605, 0); }
  atom[371] { type = "CB"; position( 35.5936, 23.975, 0); }
  atom[372] { type = "CB"; position( 39.153, 20.55, 0); }
  atom[373] { type = "CB"; position( 39.153, 21.92, 0); }
  atom[374] { type = "CB"; position( 37.9666, 22.605, 0); }
  atom[375] { type = "CB"; position( 37.9666, 23.975, 0); }
  atom[376] { type = "CB"; position( 1.18645, 24.66, 0); }
  atom[377] { type = "CB"; position( 1.18645, 26.03, 0); }
  atom[378] { type = "CB"; position( 0, 26.715, 0); }
  atom[379] { type = "CB"; position( 0, 28.085, 0); }
  atom[380] { type = "CB"; position( 3.55936, 24.66, 0); }
  atom[381] { type = "CB"; position( 3.55936, 26.03, 0); }
  atom[382] { type = "CB"; position( 2.37291, 26.715, 0); }
  atom[383] { type = "CB"; position( 2.37291, 28.085, 0); }
  atom[384] { type = "CB"; position( 5.93227, 24.66, 0); }
  atom[385] { type = "CB"; position( 5.93227, 26.03, 0); }
  atom[386] { type = "CB"; position( 4.74582, 26.715, 0); }
  atom[387] { type = "CB"; position( 4.74582, 28.085, 0); }
  atom[388] { type = "CB"; position( 8.30518, 24.66, 0); }
  atom[389] { type = "CB"; position( 8.30518, 26.03, 0); }
  atom[390] { type = "CB"; position( 7.11873, 26.715, 0); }
  atom[391] { type = "CB"; position( 7.11873, 28.085, 0); }
  atom[392] { type = "CB"; position( 10.6781, 24.66, 0); }
  atom[393] { type = "CB"; position( 10.6781, 26.03, 0); }
  atom[394] { type = "CB"; position( 9.49164, 26.715, 0); }
  atom[395] { type = "CB"; position( 9.49164, 28.085, 0); }
  atom[396] { type = "CB"; position( 13.051, 24.66, 0); }
  atom[397] { type = "CB"; position( 13.051, 26.03, 0); }
  atom[398] { type = "CB"; position( 11.8645, 26.715, 0); }
  atom[399] { type = "CB"; position( 11.8645, 28.085, 0); }
  atom[400] { type = "CB"; position( 15.4239, 26.03, 0); }
  atom[401] { type = "CB"; position( 14.2375, 26.715, 0); }
  atom[402] { type = "CB"; position( 14.2375, 28.085, 0); }
  atom[403] { type = "CB"; position( 16.6104, 26.715, 0); }
  atom[404] { type = "CB"; position( 16.6104, 28.085, 0); }
  atom[405] { type = "CB"; position( 18.9833, 26.715, 0); }
  atom[406] { type = "CB"; position( 18.9833, 28.085, 0); }
  atom[407] { type = "CB"; position( 22.5426, 26.03, 0); }
  atom[408] { type = "CB"; position( 21.3562, 26.715, 0); }
  atom[409] { type = "CB"; position( 21.3562, 28.085, 0); }
  atom[410] { type = "CB"; position( 24.9156, 24.66, 0); }
  atom[411] { type = "CB"; position( 24.9156, 26.03, 0); }
  atom[412] { type = "CB"; position( 23.7291, 26.715, 0); }
  atom[413] { type = "CB"; position( 23.7291, 28.085, 0); }
  atom[414] { type = "CB"; position( 27.2885, 24.66, 0); }
  atom[415] { type = "CB"; position( 27.2885, 26.03, 0); }
  atom[416] { type = "CB"; position( 26.102, 26.715, 0); }
  atom[417] { type = "CB"; position( 26.102, 28.085, 0); }
  atom[418] { type = "CB"; position( 29.6614, 24.66, 0); }
  atom[419] { type = "CB"; position( 29.6614, 26.03, 0); }
  atom[420] { type = "CB"; position( 28.4749, 26.715, 0); }
  atom[421] { type = "CB"; position( 28.4749, 28.085, 0); }
  atom[422] { type = "CB"; position( 32.0343, 24.66, 0); }
  atom[423] { type = "CB"; position( 32.0343, 26.03, 0); }
  atom[424] { type = "CB"; position( 30.8478, 26.715, 0); }
  atom[425] { type = "CB"; position( 30.8478, 28.085, 0); }
  atom[426] { type = "CB"; position( 34.4072, 24.66, 0); }
  atom[427] { type = "CB"; position( 34.4072, 26.03, 0); }
  atom[428] { type = "CB"; position( 33.2207, 26.715, 0); }
  atom[429] { type = "CB"; position( 33.2207, 28.085, 0); }
  atom[430] { type = "CB"; position( 36.7801, 24.66, 0); }
  atom[431] { type = "CB"; position( 36.7801, 26.03, 0); }
  atom[432] { type = "CB"; position( 35.5936, 26.715, 0); }
  atom[433] { type = "CB"; position( 35.5936, 28.085, 0); }
  atom[434] { type = "CB"; position( 39.153, 24.66, 0); }
  atom[435] { type = "CB"; position( 39.153, 26.03, 0); }
  atom[436] { type = "CB"; position( 37.9666, 26.715, 0); }
  atom[437] { type = "CB"; position( 37.9666, 28.085, 0); }
  atom[438] { type = "CB"; position( 1.18645, 28.77, 0); }
  atom[439] { type = "CB"; position( 1.18645, 30.14, 0); }
  atom[440] { type = "CB"; position( 0, 30.825, 0); }
  atom[441] { type = "CB"; position( 0, 32.195, 0); }
  atom[442] { type = "CB"; position( 3.55936, 28.77, 0); }
  atom[443] { type = "CB"; position( 3.55936, 30.14, 0); }
  atom[444] { type = "CB"; position( 2.37291, 30.825, 0); }
  atom[445] { type = "CB"; position( 2.37291, 32.195, 0); }
  atom[446] { type = "CB"; position( 5.93227, 28.77, 0); }
  atom[447] { type = "CB"; position( 5.93227, 30.14, 0); }
  atom[448] { type = "CB"; position( 4.74582, 30.825, 0); }
  atom[449] { type = "CB"; position( 4.74582, 32.195, 0); }
  atom[450] { type = "CB"; position( 8.30518, 28.77, 0); }
  atom[451] { type = "CB"; position( 8.30518, 30.14, 0); }
  atom[452] { type = "CB"; position( 7.11873, 30.825, 0); }
  atom[453] { type = "CB"; position( 7.11873, 32.195, 0); }
  atom[454] { type = "CB"; position( 10.6781, 28.77, 0); }
  atom[455] { type = "CB"; position( 10.6781, 30.14, 0); }
  atom[456] { type = "CB"; position( 9.49164, 30.825, 0); }
  atom[457] { type = "CB"; position( 9.49164, 32.195, 0); }
  atom[458] { type = "CB"; position( 13.051, 28.77, 0); }
  atom[459] { type = "CB"; position( 13.051, 30.14, 0); }
  atom[460] { type = "CB"; position( 11.8645, 30.825, 0); }
  atom[461] { type = "CB"; position( 11.8645, 32.195, 0); }
  atom[462] { type = "CB"; position( 15.4239, 28.77, 0); }
  atom[463] { type = "CB"; position( 15.4239, 30.14, 0); }
  atom[464] { type = "CB"; position( 14.2375, 30.825, 0); }
  atom[465] { type = "CB"; position( 14.2375, 32.195, 0); }
  atom[466] { type = "CB"; position( 17.7968, 28.77, 0); }
  atom[467] { type = "CB"; position( 17.7968, 30.14, 0); }
  atom[468] { type = "CB"; position( 16.6104, 30.825, 0); }
  atom[469] { type = "CB"; position( 16.6104, 32.195, 0); }
  atom[470] { type = "CB"; position( 20.1697, 28.77, 0); }
  atom[471] { type = "CB"; position( 20.1697, 30.14, 0); }
  atom[472] { type = "CB"; position( 18.9833, 30.825, 0); }
  atom[473] { type = "CB"; position( 18.9833, 32.195, 0); }
  atom[474] { type = "CB"; position( 22.5426, 28.77, 0); }
  atom[475] { type = "CB"; position( 22.5426, 30.14, 0); }
  atom[476] { type = "CB"; position( 21.3562, 30.825, 0); }
  atom[477] { type = "CB"; position( 21.3562, 32.195, 0); }
  atom[478] { type = "CB"; position( 24.9156, 28.77, 0); }
  atom[479] { type = "CB"; position( 24.9156, 30.14, 0); }
  atom[480] { type = "CB"; position( 23.7291, 30.825, 0); }
  atom[481] { type = "CB"; position( 23.7291, 32.195, 0); }
  atom[482] { type = "CB"; position( 27.2885, 28.77, 0); }
  atom[483] { type = "CB"; position( 27.2885, 30.14, 0); }
  atom[484] { type = "CB"; position( 26.102, 30.825, 0); }
  atom[485] { type = "CB"; position( 26.102, 32.195, 0); }
  atom[486] { type = "CB"; position( 29.6614, 28.77, 0); }
  atom[487] { type = "CB"; position( 29.6614, 30.14, 0); }
  atom[488] { type = "CB"; position( 28.4749, 30.825, 0); }
  atom[489] { type = "CB"; position( 28.4749, 32.195, 0); }
  atom[490] { type = "CB"; position( 32.0343, 28.77, 0); }
  atom[491] { type = "CB"; position( 32.0343, 30.14, 0); }
  atom[492] { type = "CB"; position( 30.8478, 30.825, 0); }
  atom[493] { type = "CB"; position( 30.8478, 32.195, 0); }
  atom[494] { type = "CB"; position( 34.4072, 28.77, 0); }
  atom[495] { type = "CB"; position( 34.4072, 30.14, 0); }
  atom[496] { type = "CB"; position( 33.2207, 30.825, 0); }
  atom[497] { type = "CB"; position( 33.2207, 32.195, 0); }
  atom[498] { type = "CB"; position( 36.7801, 28.77, 0); }
  atom[499] { type = "CB"; position( 36.7801, 30.14, 0); }
  atom[500] { type = "CB"; position( 35.5936, 30.825, 0); }
  atom[501] { type = "CB"; position( 35.5936, 32.195, 0); }
  atom[502] { type = "CB"; position( 39.153, 28.77, 0); }
  atom[503] { type = "CB"; position( 39.153, 30.14, 0); }
  atom[504] { type = "CB"; position( 37.9666, 30.825, 0); }
  atom[505] { type = "CB"; position( 37.9666, 32.195, 0); }
  atom[506] { type = "CB"; position( 1.18645, 32.88, 0); }
  atom[507] { type = "CB"; position( 1.18645, 34.25, 0); }
  atom[508] { type = "CB"; position( 0, 34.935, 0); }
  atom[509] { type = "CB"; position( 0, 36.305, 0); }
  atom[510] { type = "CB"; position( 3.55936, 32.88, 0); }
  atom[511] { type = "CB"; position( 3.55936, 34.25, 0); }
  atom[512] { type = "CB"; position( 2.37291, 34.935, 0); }
  atom[513] { type = "CB"; position( 2.37291, 36.305, 0); }
  atom[514] { type = "CB"; position( 5.93227, 32.88, 0); }
  atom[515] { type = "CB"; position( 5.93227, 34.25, 0); }
  atom[516] { type = "CB"; position( 4.74582, 34.935, 0); }
  atom[517] { type = "CB"; position( 4.74582, 36.305, 0); }
  atom[518] { type = "CB"; position( 8.30518, 32.88, 0); }
  atom[519] { type = "CB"; position( 8.30518, 34.25, 0); }
  atom[520] { type = "CB"; position( 7.11873, 34.935, 0); }
  atom[521] { type = "CB"; position( 7.11873, 36.305, 0); }
  atom[522] { type = "CB"; position( 10.6781, 32.88, 0); }
  atom[523] { type = "CB"; position( 10.6781, 34.25, 0); }
  atom[524] { type = "CB"; position( 9.49164, 34.935, 0); }
  atom[525] { type = "CB"; position( 9.49164, 36.305, 0); }
  atom[526] { type = "CB"; position( 13.051, 32.88, 0); }
  atom[527] { type = "CB"; position( 13.051, 34.25, 0); }
  atom[528] { type = "CB"; position( 11.8645, 34.935, 0); }
  atom[529] { type = "CB"; position( 11.8645, 36.305, 0); }
  atom[530] { type = "CB"; position( 15.4239, 32.88, 0); }
  atom[531] { type = "CB"; position( 15.4239, 34.25, 0); }
  atom[532] { type = "CB"; position( 14.2375, 34.935, 0); }
  atom[533] { type = "CB"; position( 14.2375, 36.305, 0); }
  atom[534] { type = "CB"; position( 17.7968, 32.88, 0); }
  atom[535] { type = "CB"; position( 17.7968, 34.25, 0); }
  atom[536] { type = "CB"; position( 16.6104, 34.935, 0); }
  atom[537] { type = "CB"; position( 16.6104, 36.305, 0); }
  atom[538] { type = "CB"; position( 20.1697, 32.88, 0); }
  atom[539] { type = "CB"; position( 20.1697, 34.25, 0); }
  atom[540] { type = "CB"; position( 18.9833, 34.935, 0); }
  atom[541] { type = "CB"; position( 18.9833, 36.305, 0); }
  atom[542] { type = "CB"; position( 22.5426, 32.88, 0); }
  atom[543] { type = "CB"; position( 22.5426, 34.25, 0); }
  atom[544] { type = "CB"; position( 21.3562, 34.935, 0); }
  atom[545] { type = "CB"; position( 21.3562, 36.305, 0); }
  atom[546] { type = "CB"; position( 24.9156, 32.88, 0); }
  atom[547] { type = "CB"; position( 24.9156, 34.25, 0); }
  atom[548] { type = "CB"; position( 23.7291, 34.935, 0); }
  atom[549] { type = "CB"; position( 23.7291, 36.305, 0); }
  atom[550] { type = "CB"; position( 27.2885, 32.88, 0); }
  atom[551] { type = "CB"; position( 27.2885, 34.25, 0); }
  atom[552] { type = "CB"; position( 26.102, 34.935, 0); }
  atom[553] { type = "CB"; position( 26.102, 36.305, 0); }
  atom[554] { type = "CB"; position( 29.6614, 32.88, 0); }
  atom[555] { type = "CB"; position( 29.6614, 34.25, 0); }
  atom[556] { type = "CB"; position( 28.4749, 34.935, 0); }
  atom[557] { type = "CB"; position( 28.4749, 36.305, 0); }
  atom[558] { type = "CB"; position( 32.0343, 32.88, 0); }
  atom[559] { type = "CB"; position( 32.0343, 34.25, 0); }
  atom[560] { type = "CB"; position( 30.8478, 34.935, 0); }
  atom[561] { type = "CB"; position( 30.8478, 36.305, 0); }
  atom[562] { type = "CB"; position( 34.4072, 32.88, 0); }
  atom[563] { type = "CB"; position( 34.4072, 34.25, 0); }
  atom[564] { type = "CB"; position( 33.2207, 34.935, 0); }
  atom[565] { type = "CB"; position( 33.2207, 36.305, 0); }
  atom[566] { type = "CB"; position( 36.7801, 32.88, 0); }
  atom[567] { type = "CB"; position( 36.7801, 34.25, 0); }
  atom[568] { type = "CB"; position( 35.5936, 34.935, 0); }
  atom[569] { type = "CB"; position( 35.5936, 36.305, 0); }
  atom[570] { type = "CB"; position( 39.153, 32.88, 0); }
  atom[571] { type = "CB"; position( 39.153, 34.25, 0); }
  atom[572] { type = "CB"; position( 37.9666, 34.935, 0); }
  atom[573] { type = "CB"; position( 37.9666, 36.305, 0); }
  atom[574] { type = "CB"; position( 1.18645, 36.99, 0); }
  atom[575] { type = "CB"; position( 1.18645, 38.36, 0); }
  atom[576] { type = "CB"; position( 0, 39.045, 0); }
  atom[577] { type = "CB"; position( 0, 40.415, 0); }
  atom[578] { type = "CB"; position( 3.55936, 36.99, 0); }
  atom[579] { type = "CB"; position( 3.55936, 38.36, 0); }
  atom[580] { type = "CB"; position( 2.37291, 39.045, 0); }
  atom[581] { type = "CB"; position( 2.37291, 40.415, 0); }
  atom[582] { type = "CB"; position( 5.93227, 36.99, 0); }
  atom[583] { type = "CB"; position( 5.93227, 38.36, 0); }
  atom[584] { type = "CB"; position( 4.74582, 39.045, 0); }
  atom[585] { type = "CB"; position( 4.74582, 40.415, 0); }
  atom[586] { type = "CB"; position( 8.30518, 36.99, 0); }
  atom[587] { type = "CB"; position( 8.30518, 38.36, 0); }
  atom[588] { type = "CB"; position( 7.11873, 39.045, 0); }
  atom[589] { type = "CB"; position( 7.11873, 40.415, 0); }
  atom[590] { type = "CB"; position( 10.6781, 36.99, 0); }
  atom[591] { type = "CB"; position( 10.6781, 38.36, 0); }
  atom[592] { type = "CB"; position( 9.49164, 39.045, 0); }
  atom[593] { type = "CB"; position( 9.49164, 40.415, 0); }
  atom[594] { type = "CB"; position( 13.051, 36.99, 0); }
  atom[595] { type = "CB"; position( 13.051, 38.36, 0); }
  atom[596] { type = "CB"; position( 11.8645, 39.045, 0); }
  atom[597] { type = "CB"; position( 11.8645, 40.415, 0); }
  atom[598] { type = "CB"; position( 15.4239, 36.99, 0); }
  atom[599] { type = "CB"; position( 15.4239, 38.36, 0); }
  atom[600] { type = "CB"; position( 14.2375, 39.045, 0); }
  atom[601] { type = "CB"; position( 14.2375, 40.415, 0); }
  atom[602] { type = "CB"; position( 17.7968, 36.99, 0); }
  atom[603] { type = "CB"; position( 17.7968, 38.36, 0); }
  atom[604] { type = "CB"; position( 16.6104, 39.045, 0); }
  atom[605] { type = "CB"; position( 16.6104, 40.415, 0); }
  atom[606] { type = "CB"; position( 20.1697, 36.99, 0); }
  atom[607] { type = "CB"; position( 20.1697, 38.36, 0); }
  atom[608] { type = "CB"; position( 18.9833, 39.045, 0); }
  atom[609] { type = "CB"; position( 18.9833, 40.415, 0); }
  atom[610] { type = "CB"; position( 22.5426, 36.99, 0); }
  atom[611] { type = "CB"; position( 22.5426, 38.36, 0); }
  atom[612] { type = "CB"; position( 21.3562, 39.045, 0); }
  atom[613] { type = "CB"; position( 21.3562, 40.415, 0); }
  atom[614] { type = "CB"; position( 24.9156, 36.99, 0); }
  atom[615] { type = "CB"; position( 24.9156, 38.36, 0); }
  atom[616] { type = "CB"; position( 23.7291, 39.045, 0); }
  atom[617] { type = "CB"; position( 23.7291, 40.415, 0); }
  atom[618] { type = "CB"; position( 27.2885, 36.99, 0); }
  atom[619] { type = "CB"; position( 27.2885, 38.36, 0); }
  atom[620] { type = "CB"; position( 26.102, 39.045, 0); }
  atom[621] { type = "CB"; position( 26.102, 40.415, 0); }
  atom[622] { type = "CB"; position( 29.6614, 36.99, 0); }
  atom[623] { type = "CB"; position( 29.6614, 38.36, 0); }
  atom[624] { type = "CB"; position( 28.4749, 39.045, 0); }
  atom[625] { type = "CB"; position( 28.4749, 40.415, 0); }
  atom[626] { type = "CB"; position( 32.0343, 36.99, 0); }
  atom[627] { type = "CB"; position( 32.0343, 38.36, 0); }
  atom[628] { type = "CB"; position( 30.8478, 39.045, 0); }
  atom[629] { type = "CB"; position( 30.8478, 40.415, 0); }
  atom[630] { type = "CB"; position( 34.4072, 36.99, 0); }
  atom[631] { type = "CB"; position( 34.4072, 38.36, 0); }
  atom[632] { type = "CB"; position( 33.2207, 39.045, 0); }
  atom[633] { type = "CB"; position( 33.2207, 40.415, 0); }
  atom[634] { type = "CB"; position( 36.7801, 36.99, 0); }
  atom[635] { type = "CB"; position( 36.7801, 38.36, 0); }
  atom[636] { type = "CB"; position( 35.5936, 39.045, 0); }
  atom[637] { type = "CB"; position( 35.5936, 40.415, 0); }
  atom[638] { type = "CB"; position( 39.153, 36.99, 0); }
  atom[639] { type = "CB"; position( 39.153, 38.36, 0); }
  atom[640] { type = "CB"; position( 37.9666, 39.045, 0); }
  atom[641] { type = "CB"; position( 37.9666, 40.415, 0); }
  atom[642] { type = "CA"; position( 17.7968, 16.44, 0); }
  atom[643] { type = "CA"; position( 20.1697, 16.44, 0); }
  atom[644] { type = "CA"; position( 22.5426, 16.44, 0); }
  atom[645] { type = "CA"; position( 24.9156, 17.81, 0); }
  atom[646] { type = "CA"; position( 24.9156, 20.55, 0); }
  atom[647] { type = "CA"; position( 23.7291, 22.605, 0); }
  atom[648] { type = "CA"; position( 22.5426, 24.66, 0); }
  atom[649] { type = "CA"; position( 20.1697, 26.03, 0); }
  atom[650] { type = "CA"; position( 17.7968, 26.03, 0); }
  atom[651] { type = "CA"; position( 15.4239, 24.66, 0); }
  atom[652] { type = "CA"; position( 15.4239, 21.92, 0); }
  atom[653] { type = "CA"; position( 15.4239, 20.55, 0); }
  atom[654] { type = "CA"; position( 15.4239, 17.81, 0); }
  atom[655] { type = "HA"; position( 17.7968, 17.81, 0); }
  atom[656] { type = "HA"; position( 20.1697, 17.81, 0); }
  atom[657] { type = "HA"; position( 22.5426, 17.81, 0); }
  atom[658] { type = "HA"; position( 23.7291, 18.495, 0); }
  atom[659] { type = "HA"; position( 23.7291, 19.865, 0); }
  atom[660] { type = "HA"; position( 22.5426, 21.92, 0); }
  atom[661] { type = "HA"; position( 21.3562, 23.975, 0); }
  atom[662] { type = "HA"; position( 20.1697, 24.66, 0); }
  atom[663] { type = "HA"; position( 17.7968, 24.66, 0); }
  atom[664] { type = "HA"; position( 16.6104, 23.975, 0); }
  atom[665] { type = "HA"; position( 16.6104, 22.605, 0); }
  atom[666] { type = "HA"; position( 16.6104, 19.865, 0); }
  atom[667] { type = "HA"; position( 16.6104, 18.495, 0); }

  // This list includes bonds that span the box
  bond { members(0, 1); }
  bond { members(1, 2); }
  bond { members(1, 6); }
  bond { members(2, 3); }
  bond { members(3, 68); }
  bond { members(4, 5); }
  bond { members(5, 6); }
  bond { members(5, 10); }
  bond { members(6, 7); }
  bond { members(7, 68); }
  bond { members(7, 72); }
  bond { members(8, 9); }
  bond { members(9, 10); }
  bond { members(9, 14); }
  bond { members(10, 11); }
  bond { members(11, 72); }
  bond { members(11, 76); }
  bond { members(12, 13); }
  bond { members(13, 14); }
  bond { members(13, 18); }
  bond { members(14, 15); }
  bond { members(15, 76); }
  bond { members(15, 80); }
  bond { members(16, 17); }
  bond { members(17, 18); }
  bond { members(17, 22); }
  bond { members(18, 19); }
  bond { members(19, 80); }
  bond { members(19, 84); }
  bond { members(20, 21); }
  bond { members(21, 22); }
  bond { members(21, 26); }
  bond { members(22, 23); }
  bond { members(23, 84); }
  bond { members(23, 88); }
  bond { members(24, 25); }
  bond { members(25, 26); }
  bond { members(25, 30); }
  bond { members(26, 27); }
  bond { members(27, 88); }
  bond { members(27, 92); }
  bond { members(28, 29); }
  bond { members(29, 30); }
  bond { members(29, 34); }
  bond { members(30, 31); }
  bond { members(31, 92); }
  bond { members(31, 96); }
  bond { members(32, 33); }
  bond { members(33, 34); }
  bond { members(33, 38); }
  bond { members(34, 35); }
  bond { members(35, 96); }
  bond { members(35, 100); }
  bond { members(36, 37); }
  bond { members(37, 38); }
  bond { members(37, 42); }
  bond { members(38, 39); }
  bond { members(39, 100); }
  bond { members(39, 104); }
  bond { members(40, 41); }
  bond { members(41, 42); }
  bond { members(41, 46); }
  bond { members(42, 43); }
  bond { members(43, 104); }
  bond { members(43, 108); }
  bond { members(44, 45); }
  bond { members(45, 46); }
  bond { members(45, 50); }
  bond { members(46, 47); }
  bond { members(47, 108); }
  bond { members(47, 112); }
  bond { members(48, 49); }
  bond { members(49, 50); }
  bond { members(49, 54); }
  bond { members(50, 51); }
  bond { members(51, 112); }
  bond { members(51, 116); }
  bond { members(52, 53); }
  bond { members(53, 54); }
  bond { members(53, 58); }
  bond { members(54, 55); }
  bond { members(55, 116); }
  bond { members(55, 120); }
  bond { members(56, 57); }
  bond { members(57, 58); }
  bond { members(57, 62); }
  bond { members(58, 59); }
  bond { members(59, 120); }
  bond { members(59, 124); }
  bond { members(60, 61); }
  bond { members(61, 62); }
  bond { members(61, 66); }
  bond { members(62, 63); }
  bond { members(63, 124); }
  bond { members(63, 128); }
  bond { members(64, 65); }
  bond { members(65, 66); }
  bond { members(66, 67); }
  bond { members(67, 128); }
  bond { members(67, 132); }
  bond { members(68, 69); }
  bond { members(69, 70); }
  bond { members(69, 74); }
  bond { members(70, 71); }
  bond { members(71, 136); }
  bond { members(72, 73); }
  bond { members(73, 74); }
  bond { members(73, 78); }
  bond { members(74, 75); }
  bond { members(75, 136); }
  bond { members(75, 140); }
  bond { members(76, 77); }
  bond { members(77, 78); }
  bond { members(77, 82); }
  bond { members(78, 79); }
  bond { members(79, 140); }
  bond { members(79, 144); }
  bond { members(80, 81); }
  bond { members(81, 82); }
  bond { members(81, 86); }
  bond { members(82, 83); }
  bond { members(83, 144); }
  bond { members(83, 148); }
  bond { members(84, 85); }
  bond { members(85, 86); }
  bond { members(85, 90); }
  bond { members(86, 87); }
  bond { members(87, 148); }
  bond { members(87, 152); }
  bond { members(88, 89); }
  bond { members(89, 90); }
  bond { members(89, 94); }
  bond { members(90, 91); }
  bond { members(91, 152); }
  bond { members(91, 156); }
  bond { members(92, 93); }
  bond { members(93, 94); }
  bond { members(93, 98); }
  bond { members(94, 95); }
  bond { members(95, 156); }
  bond { members(95, 160); }
  bond { members(96, 97); }
  bond { members(97, 98); }
  bond { members(97, 102); }
  bond { members(98, 99); }
  bond { members(99, 160); }
  bond { members(99, 164); }
  bond { members(100, 101); }
  bond { members(101, 102); }
  bond { members(101, 106); }
  bond { members(102, 103); }
  bond { members(103, 164); }
  bond { members(103, 168); }
  bond { members(104, 105); }
  bond { members(105, 106); }
  bond { members(105, 110); }
  bond { members(106, 107); }
  bond { members(107, 168); }
  bond { members(107, 172); }
  bond { members(108, 109); }
  bond { members(109, 110); }
  bond { members(109, 114); }
  bond { members(110, 111); }
  bond { members(111, 172); }
  bond { members(111, 176); }
  bond { members(112, 113); }
  bond { members(113, 114); }
  bond { members(113, 118); }
  bond { members(114, 115); }
  bond { members(115, 176); }
  bond { members(115, 180); }
  bond { members(116, 117); }
  bond { members(117, 118); }
  bond { members(117, 122); }
  bond { members(118, 119); }
  bond { members(119, 180); }
  bond { members(119, 184); }
  bond { members(120, 121); }
  bond { members(121, 122); }
  bond { members(121, 126); }
  bond { members(122, 123); }
  bond { members(123, 184); }
  bond { members(123, 188); }
  bond { members(124, 125); }
  bond { members(125, 126); }
  bond { members(125, 130); }
  bond { members(126, 127); }
  bond { members(127, 188); }
  bond { members(127, 192); }
  bond { members(128, 129); }
  bond { members(129, 130); }
  bond { members(129, 134); }
  bond { members(130, 131); }
  bond { members(131, 192); }
  bond { members(131, 196); }
  bond { members(132, 133); }
  bond { members(133, 134); }
  bond { members(134, 135); }
  bond { members(135, 196); }
  bond { members(135, 200); }
  bond { members(136, 137); }
  bond { members(137, 138); }
  bond { members(137, 142); }
  bond { members(138, 139); }
  bond { members(139, 204); }
  bond { members(140, 141); }
  bond { members(141, 142); }
  bond { members(141, 146); }
  bond { members(142, 143); }
  bond { members(143, 204); }
  bond { members(143, 208); }
  bond { members(144, 145); }
  bond { members(145, 146); }
  bond { members(145, 150); }
  bond { members(146, 147); }
  bond { members(147, 208); }
  bond { members(147, 212); }
  bond { members(148, 149); }
  bond { members(149, 150); }
  bond { members(149, 154); }
  bond { members(150, 151); }
  bond { members(151, 212); }
  bond { members(151, 216); }
  bond { members(152, 153); }
  bond { members(153, 154); }
  bond { members(153, 158); }
  bond { members(154, 155); }
  bond { members(155, 216); }
  bond { members(155, 220); }
  bond { members(156, 157); }
  bond { members(157, 158); }
  bond { members(157, 162); }
  bond { members(158, 159); }
  bond { members(159, 220); }
  bond { members(159, 224); }
  bond { members(160, 161); }
  bond { members(161, 162); }
  bond { members(161, 166); }
  bond { members(162, 163); }
  bond { members(163, 224); }
  bond { members(163, 228); }
  bond { members(164, 165); }
  bond { members(165, 166); }
  bond { members(165, 170); }
  bond { members(166, 167); }
  bond { members(167, 228); }
  bond { members(167, 232); }
  bond { members(168, 169); }
  bond { members(169, 170); }
  bond { members(169, 174); }
  bond { members(170, 171); }
  bond { members(171, 232); }
  bond { members(171, 236); }
  bond { members(172, 173); }
  bond { members(173, 174); }
  bond { members(173, 178); }
  bond { members(174, 175); }
  bond { members(175, 236); }
  bond { members(175, 240); }
  bond { members(176, 177); }
  bond { members(177, 178); }
  bond { members(177, 182); }
  bond { members(178, 179); }
  bond { members(179, 240); }
  bond { members(179, 244); }
  bond { members(180, 181); }
  bond { members(181, 182); }
  bond { members(181, 186); }
  bond { members(182, 183); }
  bond { members(183, 244); }
  bond { members(183, 248); }
  bond { members(184, 185); }
  bond { members(185, 186); }
  bond { members(185, 190); }
  bond { members(186, 187); }
  bond { members(187, 248); }
  bond { members(187, 252); }
  bond { members(188, 189); }
  bond { members(189, 190); }
  bond { members(189, 194); }
  bond { members(190, 191); }
  bond { members(191, 252); }
  bond { members(191, 256); }
  bond { members(192, 193); }
  bond { members(193, 194); }
  bond { members(193, 198); }
  bond { members(194, 195); }
  bond { members(195, 256); }
  bond { members(195, 260); }
  bond { members(196, 197); }
  bond { members(197, 198); }
  bond { members(197, 202); }
  bond { members(198, 199); }
  bond { members(199, 260); }
  bond { members(199, 264); }
  bond { members(200, 201); }
  bond { members(201, 202); }
  bond { members(202, 203); }
  bond { members(203, 264); }
  bond { members(203, 268); }
  bond { members(204, 205); }
  bond { members(205, 206); }
  bond { members(205, 210); }
  bond { members(206, 207); }
  bond { members(207, 272); }
  bond { members(208, 209); }
  bond { members(209, 210); }
  bond { members(209, 214); }
  bond { members(210, 211); }
  bond { members(211, 272); }
  bond { members(211, 276); }
  bond { members(212, 213); }
  bond { members(213, 214); }
  bond { members(213, 218); }
  bond { members(214, 215); }
  bond { members(215, 276); }
  bond { members(215, 280); }
  bond { members(216, 217); }
  bond { members(217, 218); }
  bond { members(217, 222); }
  bond { members(218, 219); }
  bond { members(219, 280); }
  bond { members(219, 284); }
  bond { members(220, 221); }
  bond { members(221, 222); }
  bond { members(221, 226); }
  bond { members(222, 223); }
  bond { members(223, 284); }
  bond { members(223, 288); }
  bond { members(224, 225); }
  bond { members(225, 226); }
  bond { members(225, 230); }
  bond { members(226, 227); }
  bond { members(227, 288); }
  bond { members(227, 292); }
  bond { members(228, 229); }
  bond { members(229, 230); }
  bond { members(229, 234); }
  bond { members(230, 231); }
  bond { members(231, 292); }
  bond { members(231, 296); }
  bond { members(232, 233); }
  bond { members(233, 234); }
  bond { members(233, 238); }
  bond { members(234, 235); }
  bond { members(235, 296); }
  bond { members(235, 642); }
  bond { members(236, 237); }
  bond { members(237, 238); }
  bond { members(237, 242); }
  bond { members(238, 239); }
  bond { members(239, 642); }
  bond { members(239, 643); }
  bond { members(240, 241); }
  bond { members(241, 242); }
  bond { members(241, 246); }
  bond { members(242, 243); }
  bond { members(243, 643); }
  bond { members(243, 644); }
  bond { members(244, 245); }
  bond { members(245, 246); }
  bond { members(245, 250); }
  bond { members(246, 247); }
  bond { members(247, 299); }
  bond { members(247, 644); }
  bond { members(248, 249); }
  bond { members(249, 250); }
  bond { members(249, 254); }
  bond { members(250, 251); }
  bond { members(251, 299); }
  bond { members(251, 300); }
  bond { members(252, 253); }
  bond { members(253, 254); }
  bond { members(253, 258); }
  bond { members(254, 255); }
  bond { members(255, 300); }
  bond { members(255, 304); }
  bond { members(256, 257); }
  bond { members(257, 258); }
  bond { members(257, 262); }
  bond { members(258, 259); }
  bond { members(259, 304); }
  bond { members(259, 308); }
  bond { members(260, 261); }
  bond { members(261, 262); }
  bond { members(261, 266); }
  bond { members(262, 263); }
  bond { members(263, 308); }
  bond { members(263, 312); }
  bond { members(264, 265); }
  bond { members(265, 266); }
  bond { members(265, 270); }
  bond { members(266, 267); }
  bond { members(267, 312); }
  bond { members(267, 316); }
  bond { members(268, 269); }
  bond { members(269, 270); }
  bond { members(270, 271); }
  bond { members(271, 316); }
  bond { members(271, 320); }
  bond { members(272, 273); }
  bond { members(273, 274); }
  bond { members(273, 278); }
  bond { members(274, 275); }
  bond { members(275, 324); }
  bond { members(276, 277); }
  bond { members(277, 278); }
  bond { members(277, 282); }
  bond { members(278, 279); }
  bond { members(279, 324); }
  bond { members(279, 328); }
  bond { members(280, 281); }
  bond { members(281, 282); }
  bond { members(281, 286); }
  bond { members(282, 283); }
  bond { members(283, 328); }
  bond { members(283, 332); }
  bond { members(284, 285); }
  bond { members(285, 286); }
  bond { members(285, 290); }
  bond { members(286, 287); }
  bond { members(287, 332); }
  bond { members(287, 336); }
  bond { members(288, 289); }
  bond { members(289, 290); }
  bond { members(289, 294); }
  bond { members(290, 291); }
  bond { members(291, 336); }
  bond { members(291, 340); }
  bond { members(292, 293); }
  bond { members(293, 294); }
  bond { members(293, 297); }
  bond { members(294, 295); }
  bond { members(295, 340); }
  bond { members(295, 344); }
  bond { members(296, 654); }
  bond { members(297, 298); }
  bond { members(298, 344); }
  bond { members(298, 653); }
  bond { members(299, 645); }
  bond { members(300, 301); }
  bond { members(301, 302); }
  bond { members(301, 306); }
  bond { members(302, 303); }
  bond { members(303, 352); }
  bond { members(303, 646); }
  bond { members(304, 305); }
  bond { members(305, 306); }
  bond { members(305, 310); }
  bond { members(306, 307); }
  bond { members(307, 352); }
  bond { members(307, 356); }
  bond { members(308, 309); }
  bond { members(309, 310); }
  bond { members(309, 314); }
  bond { members(310, 311); }
  bond { members(311, 356); }
  bond { members(311, 360); }
  bond { members(312, 313); }
  bond { members(313, 314); }
  bond { members(313, 318); }
  bond { members(314, 315); }
  bond { members(315, 360); }
  bond { members(315, 364); }
  bond { members(316, 317); }
  bond { members(317, 318); }
  bond { members(317, 322); }
  bond { members(318, 319); }
  bond { members(319, 364); }
  bond { members(319, 368); }
  bond { members(320, 321); }
  bond { members(321, 322); }
  bond { members(322, 323); }
  bond { members(323, 368); }
  bond { members(323, 372); }
  bond { members(324, 325); }
  bond { members(325, 326); }
  bond { members(325, 330); }
  bond { members(326, 327); }
  bond { members(327, 376); }
  bond { members(328, 329); }
  bond { members(329, 330); }
  bond { members(329, 334); }
  bond { members(330, 331); }
  bond { members(331, 376); }
  bond { members(331, 380); }
  bond { members(332, 333); }
  bond { members(333, 334); }
  bond { members(333, 338); }
  bond { members(334, 335); }
  bond { members(335, 380); }
  bond { members(335, 384); }
  bond { members(336, 337); }
  bond { members(337, 338); }
  bond { members(337, 342); }
  bond { members(338, 339); }
  bond { members(339, 384); }
  bond { members(339, 388); }
  bond { members(340, 341); }
  bond { members(341, 342); }
  bond { members(341, 346); }
  bond { members(342, 343); }
  bond { members(343, 388); }
  bond { members(343, 392); }
  bond { members(344, 345); }
  bond { members(345, 346); }
  bond { members(345, 348); }
  bond { members(346, 347); }
  bond { members(347, 392); }
  bond { members(347, 396); }
  bond { members(348, 349); }
  bond { members(349, 396); }
  bond { members(349, 651); }
  bond { members(350, 354); }
  bond { members(350, 647); }
  bond { members(351, 410); }
  bond { members(351, 648); }
  bond { members(352, 353); }
  bond { members(353, 354); }
  bond { members(353, 358); }
  bond { members(354, 355); }
  bond { members(355, 410); }
  bond { members(355, 414); }
  bond { members(356, 357); }
  bond { members(357, 358); }
  bond { members(357, 362); }
  bond { members(358, 359); }
  bond { members(359, 414); }
  bond { members(359, 418); }
  bond { members(360, 361); }
  bond { members(361, 362); }
  bond { members(361, 366); }
  bond { members(362, 363); }
  bond { members(363, 418); }
  bond { members(363, 422); }
  bond { members(364, 365); }
  bond { members(365, 366); }
  bond { members(365, 370); }
  bond { members(366, 367); }
  bond { members(367, 422); }
  bond { members(367, 426); }
  bond { members(368, 369); }
  bond { members(369, 370); }
  bond { members(369, 374); }
  bond { members(370, 371); }
  bond { members(371, 426); }
  bond { members(371, 430); }
  bond { members(372, 373); }
  bond { members(373, 374); }
  bond { members(374, 375); }
  bond { members(375, 430); }
  bond { members(375, 434); }
  bond { members(376, 377); }
  bond { members(377, 378); }
  bond { members(377, 382); }
  bond { members(378, 379); }
  bond { members(379, 438); }
  bond { members(380, 381); }
  bond { members(381, 382); }
  bond { members(381, 386); }
  bond { members(382, 383); }
  bond { members(383, 438); }
  bond { members(383, 442); }
  bond { members(384, 385); }
  bond { members(385, 386); }
  bond { members(385, 390); }
  bond { members(386, 387); }
  bond { members(387, 442); }
  bond { members(387, 446); }
  bond { members(388, 389); }
  bond { members(389, 390); }
  bond { members(389, 394); }
  bond { members(390, 391); }
  bond { members(391, 446); }
  bond { members(391, 450); }
  bond { members(392, 393); }
  bond { members(393, 394); }
  bond { members(393, 398); }
  bond { members(394, 395); }
  bond { members(395, 450); }
  bond { members(395, 454); }
  bond { members(396, 397); }
  bond { members(397, 398); }
  bond { members(397, 401); }
  bond { members(398, 399); }
  bond { members(399, 454); }
  bond { members(399, 458); }
  bond { members(400, 401); }
  bond { members(400, 403); }
  bond { members(401, 402); }
  bond { members(402, 458); }
  bond { members(402, 462); }
  bond { members(403, 404); }
  bond { members(404, 462); }
  bond { members(404, 466); }
  bond { members(405, 406); }
  bond { members(406, 466); }
  bond { members(406, 470); }
  bond { members(407, 408); }
  bond { members(407, 412); }
  bond { members(408, 409); }
  bond { members(409, 470); }
  bond { members(409, 474); }
  bond { members(410, 411); }
  bond { members(411, 412); }
  bond { members(411, 416); }
  bond { members(412, 413); }
  bond { members(413, 474); }
  bond { members(413, 478); }
  bond { members(414, 415); }
  bond { members(415, 416); }
  bond { members(415, 420); }
  bond { members(416, 417); }
  bond { members(417, 478); }
  bond { members(417, 482); }
  bond { members(418, 419); }
  bond { members(419, 420); }
  bond { members(419, 424); }
  bond { members(420, 421); }
  bond { members(421, 482); }
  bond { members(421, 486); }
  bond { members(422, 423); }
  bond { members(423, 424); }
  bond { members(423, 428); }
  bond { members(424, 425); }
  bond { members(425, 486); }
  bond { members(425, 490); }
  bond { members(426, 427); }
  bond { members(427, 428); }
  bond { members(427, 432); }
  bond { members(428, 429); }
  bond { members(429, 490); }
  bond { members(429, 494); }
  bond { members(430, 431); }
  bond { members(431, 432); }
  bond { members(431, 436); }
  bond { members(432, 433); }
  bond { members(433, 494); }
  bond { members(433, 498); }
  bond { members(434, 435); }
  bond { members(435, 436); }
  bond { members(436, 437); }
  bond { members(437, 498); }
  bond { members(437, 502); }
  bond { members(438, 439); }
  bond { members(439, 440); }
  bond { members(439, 444); }
  bond { members(440, 441); }
  bond { members(441, 506); }
  bond { members(442, 443); }
  bond { members(443, 444); }
  bond { members(443, 448); }
  bond { members(444, 445); }
  bond { members(445, 506); }
  bond { members(445, 510); }
  bond { members(446, 447); }
  bond { members(447, 448); }
  bond { members(447, 452); }
  bond { members(448, 449); }
  bond { members(449, 510); }
  bond { members(449, 514); }
  bond { members(450, 451); }
  bond { members(451, 452); }
  bond { members(451, 456); }
  bond { members(452, 453); }
  bond { members(453, 514); }
  bond { members(453, 518); }
  bond { members(454, 455); }
  bond { members(455, 456); }
  bond { members(455, 460); }
  bond { members(456, 457); }
  bond { members(457, 518); }
  bond { members(457, 522); }
  bond { members(458, 459); }
  bond { members(459, 460); }
  bond { members(459, 464); }
  bond { members(460, 461); }
  bond { members(461, 522); }
  bond { members(461, 526); }
  bond { members(462, 463); }
  bond { members(463, 464); }
  bond { members(463, 468); }
  bond { members(464, 465); }
  bond { members(465, 526); }
  bond { members(465, 530); }
  bond { members(466, 467); }
  bond { members(467, 468); }
  bond { members(467, 472); }
  bond { members(468, 469); }
  bond { members(469, 530); }
  bond { members(469, 534); }
  bond { members(470, 471); }
  bond { members(471, 472); }
  bond { members(471, 476); }
  bond { members(472, 473); }
  bond { members(473, 534); }
  bond { members(473, 538); }
  bond { members(474, 475); }
  bond { members(475, 476); }
  bond { members(475, 480); }
  bond { members(476, 477); }
  bond { members(477, 538); }
  bond { members(477, 542); }
  bond { members(478, 479); }
  bond { members(479, 480); }
  bond { members(479, 484); }
  bond { members(480, 481); }
  bond { members(481, 542); }
  bond { members(481, 546); }
  bond { members(482, 483); }
  bond { members(483, 484); }
  bond { members(483, 488); }
  bond { members(484, 485); }
  bond { members(485, 546); }
  bond { members(485, 550); }
  bond { members(486, 487); }
  bond { members(487, 488); }
  bond { members(487, 492); }
  bond { members(488, 489); }
  bond { members(489, 550); }
  bond { members(489, 554); }
  bond { members(490, 491); }
  bond { members(491, 492); }
  bond { members(491, 496); }
  bond { members(492, 493); }
  bond { members(493, 554); }
  bond { members(493, 558); }
  bond { members(494, 495); }
  bond { members(495, 496); }
  bond { members(495, 500); }
  bond { members(496, 497); }
  bond { members(497, 558); }
  bond { members(497, 562); }
  bond { members(498, 499); }
  bond { members(499, 500); }
  bond { members(499, 504); }
  bond { members(500, 501); }
  bond { members(501, 562); }
  bond { members(501, 566); }
  bond { members(502, 503); }
  bond { members(503, 504); }
  bond { members(504, 505); }
  bond { members(505, 566); }
  bond { members(505, 570); }
  bond { members(506, 507); }
  bond { members(507, 508); }
  bond { members(507, 512); }
  bond { members(508, 509); }
  bond { members(509, 574); }
  bond { members(510, 511); }
  bond { members(511, 512); }
  bond { members(511, 516); }
  bond { members(512, 513); }
  bond { members(513, 574); }
  bond { members(513, 578); }
  bond { members(514, 515); }
  bond { members(515, 516); }
  bond { members(515, 520); }
  bond { members(516, 517); }
  bond { members(517, 578); }
  bond { members(517, 582); }
  bond { members(518, 519); }
  bond { members(519, 520); }
  bond { members(519, 524); }
  bond { members(520, 521); }
  bond { members(521, 582); }
  bond { members(521, 586); }
  bond { members(522, 523); }
  bond { members(523, 524); }
  bond { members(523, 528); }
  bond { members(524, 525); }
  bond { members(525, 586); }
  bond { members(525, 590); }
  bond { members(526, 527); }
  bond { members(527, 528); }
  bond { members(527, 532); }
  bond { members(528, 529); }
  bond { members(529, 590); }
  bond { members(529, 594); }
  bond { members(530, 531); }
  bond { members(531, 532); }
  bond { members(531, 536); }
  bond { members(532, 533); }
  bond { members(533, 594); }
  bond { members(533, 598); }
  bond { members(534, 535); }
  bond { members(535, 536); }
  bond { members(535, 540); }
  bond { members(536, 537); }
  bond { members(537, 598); }
  bond { members(537, 602); }
  bond { members(538, 539); }
  bond { members(539, 540); }
  bond { members(539, 544); }
  bond { members(540, 541); }
  bond { members(541, 602); }
  bond { members(541, 606); }
  bond { members(542, 543); }
  bond { members(543, 544); }
  bond { members(543, 548); }
  bond { members(544, 545); }
  bond { members(545, 606); }
  bond { members(545, 610); }
  bond { members(546, 547); }
  bond { members(547, 548); }
  bond { members(547, 552); }
  bond { members(548, 549); }
  bond { members(549, 610); }
  bond { members(549, 614); }
  bond { members(550, 551); }
  bond { members(551, 552); }
  bond { members(551, 556); }
  bond { members(552, 553); }
  bond { members(553, 614); }
  bond { members(553, 618); }
  bond { members(554, 555); }
  bond { members(555, 556); }
  bond { members(555, 560); }
  bond { members(556, 557); }
  bond { members(557, 618); }
  bond { members(557, 622); }
  bond { members(558, 559); }
  bond { members(559, 560); }
  bond { members(559, 564); }
  bond { members(560, 561); }
  bond { members(561, 622); }
  bond { members(561, 626); }
  bond { members(562, 563); }
  bond { members(563, 564); }
  bond { members(563, 568); }
  bond { members(564, 565); }
  bond { members(565, 626); }
  bond { members(565, 630); }
  bond { members(566, 567); }
  bond { members(567, 568); }
  bond { members(567, 572); }
  bond { members(568, 569); }
  bond { members(569, 630); }
  bond { members(569, 634); }
  bond { members(570, 571); }
  bond { members(571, 572); }
  bond { members(572, 573); }
  bond { members(573, 634); }
  bond { members(573, 638); }
  bond { members(574, 575); }
  bond { members(575, 576); }
  bond { members(575, 580); }
  bond { members(576, 577); }
  bond { members(578, 579); }
  bond { members(579, 580); }
  bond { members(579, 584); }
  bond { members(580, 581); }
  bond { members(582, 583); }
  bond { members(583, 584); }
  bond { members(583, 588); }
  bond { members(584, 585); }
  bond { members(586, 587); }
  bond { members(587, 588); }
  bond { members(587, 592); }
  bond { members(588, 589); }
  bond { members(590, 591); }
  bond { members(591, 592); }
  bond { members(591, 596); }
  bond { members(592, 593); }
  bond { members(594, 595); }
  bond { members(595, 596); }
  bond { members(595, 600); }
  bond { members(596, 597); }
  bond { members(598, 599); }
  bond { members(599, 600); }
  bond { members(599, 604); }
  bond { members(600, 601); }
  bond { members(602, 603); }
  bond { members(603, 604); }
  bond { members(603, 608); }
  bond { members(604, 605); }
  bond { members(606, 607); }
  bond { members(607, 608); }
  bond { members(607, 612); }
  bond { members(608, 609); }
  bond { members(610, 611); }
  bond { members(611, 612); }
  bond { members(611, 616); }
  bond { members(612, 613); }
  bond { members(614, 615); }
  bond { members(615, 616); }
  bond { members(615, 620); }
  bond { members(616, 617); }
  bond { members(618, 619); }
  bond { members(619, 620); }
  bond { members(619, 624); }
  bond { members(620, 621); }
  bond { members(622, 623); }
  bond { members(623, 624); }
  bond { members(623, 628); }
  bond { members(624, 625); }
  bond { members(626, 627); }
  bond { members(627, 628); }
  bond { members(627, 632); }
  bond { members(628, 629); }
  bond { members(630, 631); }
  bond { members(631, 632); }
  bond { members(631, 636); }
  bond { members(632, 633); }
  bond { members(634, 635); }
  bond { members(635, 636); }
  bond { members(635, 640); }
  bond { members(636, 637); }
  bond { members(638, 639); }
  bond { members(639, 640); }
  bond { members(640, 641); }
  bond { members(645, 302); }
  bond { members(646, 350); }
  bond { members(647, 351); }
  bond { members(648, 407); }
  bond { members(649, 405); }
  bond { members(649, 408); }
  bond { members(650, 403); }
  bond { members(650, 405); }
  bond { members(651, 400); }
  bond { members(652, 348); }
  bond { members(653, 652); }
  bond { members(654, 297); }
  bond { members(655, 642); }
  bond { members(656, 643); }
  bond { members(657, 644); }
  bond { members(658, 645); }
  bond { members(659, 646); }
  bond { members(660, 647); }
  bond { members(661, 648); }
  bond { members(662, 649); }
  bond { members(663, 650); }
  bond { members(664, 651); }
  bond { members(665, 652); }
  bond { members(666, 653); }
  bond { members(667, 654); }
  bond { members(64, 577); }
  bond { members(65, 2); }
  bond { members(132, 3); }
  bond { members(133, 70); }
  bond { members(200, 71); }
  bond { members(201, 138); }
  bond { members(268, 139); }
  bond { members(269, 206); }
  bond { members(320, 207); }
  bond { members(321, 274); }
  bond { members(372, 275); }
  bond { members(373, 326); }
  bond { members(434, 327); }
  bond { members(435, 378); }
  bond { members(502, 379); }
  bond { members(503, 440); }
  bond { members(570, 441); }
  bond { members(571, 508); }
  bond { members(577, 0); }
  bond { members(581, 0); }
  bond { members(581, 4); }
  bond { members(585, 4); }
  bond { members(585, 8); }
  bond { members(589, 8); }
  bond { members(589, 12); }
  bond { members(593, 12); }
  bond { members(593, 16); }
  bond { members(597, 16); }
  bond { members(597, 20); }
  bond { members(601, 20); }
  bond { members(601, 24); }
  bond { members(605, 24); }
  bond { members(605, 28); }
  bond { members(609, 28); }
  bond { members(609, 32); }
  bond { members(613, 32); }
  bond { members(613, 36); }
  bond { members(617, 36); }
  bond { members(617, 40); }
  bond { members(621, 40); }
  bond { members(621, 44); }
  bond { members(625, 44); }
  bond { members(625, 48); }
  bond { members(629, 48); }
  bond { members(629, 52); }
  bond { members(633, 52); }
  bond { members(633, 56); }
  bond { members(637, 56); }
  bond { members(637, 60); }
  bond { members(638, 509); }
  bond { members(639, 576); }
  bond { members(641, 60); }
  bond { members(641, 64); }
}

#endif
