Source    = \

RmiSource =

Main      = 

SampleFiles =  \
              zconsFixed.in \
	      zconsFixed.md \
	      zconsMoving.in \
	      zconsMoving.in \
	      water.md

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

