Package = brains

Source    = \
	Exclude.cpp \
	SimInfo.cpp \
        DataStorage.cpp \
        SimSnapshotManager.cpp \
        Snapshot.cpp \
        Stats.cpp \
        Thermo.cpp \
        ForceManager.cpp \
        MoleculeCreator.cpp \
        SimCreator.cpp \
	Register.cpp \
	BlockSnapshotManager.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

