Package = io

Source    = \
  AtomTypesSectionParser.cpp \
	DirectionalAtomTypesSectionParser.cpp \
	SectionParser.cpp \
	EAMAtomTypesSectionParser.cpp \
	SectionParserManager.cpp \
	ChargeAtomTypesSectionParser.cpp \
	MultipoleAtomTypesSectionParser.cpp \
	StickyAtomTypesSectionParser.cpp \
	TorsionTypesSectionParser.cpp \
	LennardJonesAtomTypesSectionParser.cpp\
  BondTypesSectionParser.cpp \
  BendTypesSectionParser.cpp \
  BASSlex.l \
	BASSyacc.y \
	BASS_interface.cpp \
	BASS_parse.c \
	Globals.cpp \
	interface.c \
	LinkedAssign.cpp \
	make_nodes.c \
	mpiBASS.c \
	parse_tree.c \
	DumpReader.cpp \
	DumpWriter.cpp \
	StatWriter.cpp \
	ZConsReader.cpp \
	ZConsWriter.cpp \
	RestReader.cpp \
	RestWriter.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

