Package = io

Source    = \
	AtomTypesSectionParser.cpp \
	BaseAtomTypesSectionParser.cpp \
	DirectionalAtomTypesSectionParser.cpp \
	SectionParser.cpp \
	EAMAtomTypesSectionParser.cpp \
	SectionParserManager.cpp \
	ChargeAtomTypesSectionParser.cpp \
	MultipoleAtomTypesSectionParser.cpp \
	StickyAtomTypesSectionParser.cpp \
	GayBerneAtomTypesSectionParser.cpp \
	TorsionTypesSectionParser.cpp \
	InversionTypesSectionParser.cpp \
	StickyPowerAtomTypesSectionParser.cpp \
	ShapeAtomTypesSectionParser.cpp \
	LennardJonesAtomTypesSectionParser.cpp\
	SCAtomTypesSectionParser.cpp \
	NonBondedInteractionsSectionParser.cpp \
	BondTypesSectionParser.cpp \
	BendTypesSectionParser.cpp \
	Globals.cpp \
	DumpReader.cpp \
	DumpWriter.cpp \
	StatWriter.cpp \
	ZConsReader.cpp \
	ZConsWriter.cpp \
	RestReader.cpp \
	RestWriter.cpp \
	gzstream.cpp\
	ParamConstraint.cpp \
	OptionSectionParser.cpp \
	ForceFieldOptions.cpp

ParallelSource = \
	DumpReader.cpp \
	DumpWriter.cpp \
	RestReader.cpp \
	StatWriter.cpp \
	ZConsWriter.cpp

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

