Source    = \
	BASSlex.l \
	BASSyacc.y \
	BASS_interface.cpp \
	BASS_parse.c \
	DumpReader.cpp \
	DumpWriter.cpp \
	Globals.cpp \
	InitializeFromFile.cpp \
	interface.c \
	LinkedAssign.cpp \
	LinkedCommand.cpp \
	make_nodes.c \
	mpiBASS.c \
	parse_tree.c \
	RestraintReader.cpp \
	RestraintWriter.cpp \
	StatWriter.cpp \
	ZConsReader.cpp \
	ZConsWriter.cpp \

RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

