Source    = \

RmiSource =

Main      = 

SampleFiles =  \
              5CB.shape \
              8CB.shape \
              C60.shape \
              C70.shape \
              cholesterol.shape \
              ethylBenzene.shape \
              linear.in \
              linear.md \
              linear.shape \
              Shapes.frc \
              toluene.shape

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

