Source    = \

RmiSource =

Main      = 

SampleFiles =  \
	Au_300K.md \
	Au_highvisc.md \
	Au_lowvisc.md \
	spce_1atm.md \
	spce_100atm.md \
	spce_Au_1atm.md \
	spce_Au_100atm.md \
	metals.md \
	thiols.md \
	water.md

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

