Source    = \

RmiSource =

Main      = 

SampleFiles =  \
              ssdEM.in \
              ssdEM.md \
              tip4p_two.in \
              tip4p_two.md \
              water.md


DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

