Source = \
        ByteSwapper.java \
        Ebcdic.java \
        Formatter.java \
        IntMap.java \
        javacup.gif \
        properties.txt \

RmiSource =

Main      = ByteSwapper

include $(DEV_ROOT)/Makefile
