Package = primitives

Source    = \
	StuntDouble.cpp \
	Atom.cpp \
	DirectionalAtom.cpp \
	RigidBody.cpp \
	Molecule.cpp \
	Bend.cpp \
	GhostBend.cpp \
	Torsion.cpp \
	GhostTorsion.cpp \
        UreyBradleyBend.cpp \


RmiSource =

Main      =

DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

