Source    = \

RmiSource =

Main      = 

ScriptFiles = runMe

SampleFiles = bimetallic.md \
		gold.md \
		lj.md \
		metals.md \
		one_component.md \
		three_component.md \



DEV_ROOT=../..
include $(DEV_ROOT)/make/Makefile

