name: clang-format-check
on:
 schedule:
 - cron: "0 5 * * 6"
 
jobs:
 formatting-check:
  name: Formatting Check
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: if needed, commit clang-formatter changes
    run: |
     sudo apt-get install clang-format
     find . -name "*.cpp" -o -name "*.c" -o -name "*.h" -name "*.hpp"|xargs clang-format --style="{BasedOnStyle: Google, Standard: c++11, ColumnLimit: 80}" -i
     git config --global user.name 'OpenMD'
     git config --global user.email 'OpenMD@users.noreply.github.com'
     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
     git checkout $GITHUB_HEAD_REF
     git commit -am "fixup: Format code using clang-format styles as 'Google'" || true
     git push
